### ISSUE TITLE
Extraction of custom files/tree from archive is not done during domain creation

### ISSUE THREAD

**Issue by kenneth-olwing** [oracle/weblogic-deploy-tooling#1004]
Hi,

The 1.9.18 release touts this feature:

  * User can create a folder in the archive to store custom files like application config, see #944

This is then intended to be implemented by PR https://github.com/oracle/weblogic-deploy-tooling/pull/969

Unfortunately, it doesn't work. Looking at the PR, it adds a line of 'self.library_helper.extract_custom_files()' in topology_updater.py, which (I assume) will do extraction during an update. But during a create, this code is not called. Instead there is an addition of just an *empty* line in domain_creator.py; I'm assuming the intention was to insert the same extract_custom_files() call there and a test confirms this will indeed cause the files to extract during create.

Thanks, 
ken1

**Comment by CarolynRountree** [comment]
Working on this bug

**Comment by belfo** [comment]
@CarolynRountree i tested the nw WDT (1.9.19).
I had a running domain created with 1.9.18, i added a new auxilary image, and was expecting the custom folder to be expanded on the $DOMAIN_HOME, but not the case.
Could you confirm the update scenario should work? 

In the pod
[oracle@sample-domain1-managed-server1 weblogic-deploy]$ pwd
/auxiliary/weblogic-deploy
[oracle@sample-domain1-managed-server1 weblogic-deploy]$ cat VERSION.txt 
WebLogic Deploy Tooling 1.9.19[oracle@sample-domain1-managed-server1 weblogic-deploy]$ 

[oracle@sample-domain1-managed-server1 base_domain]$ pwd
/u01/domains/base_domain
[oracle@sample-domain1-managed-server1 base_domain]$ ls -lrt
total 488
-rw-r----- 1 oracle oracle    327 Apr 26  2019 fileRealm.properties
drwxr-x--- 2 oracle oracle   4096 Jan  7 10:09 console-ext
drwxr-x--- 3 oracle oracle   4096 Jan  7 10:09 common
drwxr-x--- 2 oracle oracle   4096 Jan  7 10:09 autodeploy
-rwxr-x--- 1 oracle oracle    240 Jan  7 10:09 startWebLogic.sh
drwxr-x--- 2 oracle oracle   4096 Jan  7 10:09 security
drwxr-x--- 6 oracle oracle   4096 Jan  7 10:09 bin
drwxr-x--- 2 oracle oracle   4096 Jan  7 10:09 nodemanager
drwxr-x--- 3 oracle oracle   4096 Jan  7 10:09 init-info
drwxr-xr-x 2 oracle oracle   4096 Jan 12 14:41 lib
drwxr-xr-x 8 oracle oracle   4096 Jan 12 14:41 wlsdeploy
drwxr-x--- 4 oracle oracle   4096 Jan 12 14:41 servers
drwxr-x--- 2 oracle oracle   4096 Jan 12 14:42 logs
drwxr-x--- 9 oracle oracle   4096 Jan 12 14:43 config

[oracle@sample-domain1-managed-server1 custom]$ pwd
/u01/domains/base_domain/wlsdeploy/custom
[oracle@sample-domain1-managed-server1 custom]$ ls -lrt
total 8
drwxr-xr-x 4 oracle oracle 4096 Jul 14 07:42 _application_files
drwxr-xr-x 2 oracle oracle 4096 Jan 12 10:09 classes


the 2 custom folder are not extracted to $DOMAIN_HOME

**Comment by CarolynRountree** [comment]
@belfo We followed the structure of the archive file to extract under wlsdeploy/custom https://oracle.github.io/weblogic-deploy-tooling/concepts/archive/. This is under $DOMAIN_HOME but I take it you need it directly under domain home. Can you clarify what and why please?

**Comment by belfo** [comment]
@CarolynRountree That was my comprehension of extracting in the idea of "custom is extracted under $DOMAIN_HOME" So i misunderstood.
They why is because we have an app that look for the $DOMAIN_HOME/classes for a config file.

Will look into it to see if it work by having a wlsdeploy/custom in in the path


Thx for the reply
