### ISSUE TITLE
User password encrypted in template is not correctly decrypted in domain creation

### ISSUE THREAD

**Issue by georgenuesca** [oracle/weblogic-deploy-tooling#1010]
User:
            Robert:
                Password: '{AES}VFIzVmdwcWNLeHBPaWhyRy82VER6WFV6aHRPbGcwMjQ6bS90OGVSTnJxWTIvZjkrRjpjSzBQUHlOWWpWTT0='
                GroupMemberOf: [ Administrators, FriscoGroup ]

Yes, im passing -use_encryption option during domain creation. Rest of passwordencrypted fields are working fine. Its only the user passwords are not getting decrypted.  The password that actually works is the actual encrypted value.

**Comment by CarolynRountree** [comment]
This is a bug that will be fixed in next release.

**Comment by CarolynRountree** [comment]
Could you clarify what you mean about the password that actually works is the encrypted value please?

**Comment by CarolynRountree** [comment]
When I attempted to recreate, the password was decrypted and then encrypted as expected for the wlsroles.

**Comment by georgenuesca** [comment]
I am able to run createDomain using the encrypted value above. All my other passwords for datasources and admin  are encrpted as well (using property files). When I start up the admin server, I cant login with 'Robert' account using Robert123 as the password. The password that works is '{AES}VFIzVmdwcWNLeHBPaWhyRy82VER6WFV6aHRPbGcwMjQ6bS90OGVSTnJxWTIvZjkrRjpjSzBQUHlOWWpWTT0='.

**Comment by CarolynRountree** [comment]
okay thank you

**Comment by CarolynRountree** [comment]
Fixed by PR 1012
