### ISSUE TITLE
Quotes and special charachter in YAML

### ISSUE THREAD

**Issue by antobaldu** [oracle/weblogic-deploy-tooling#1041]
I create automatically model.yaml files with YAML libraries and these libraries don't add the quotes in strings that don't need it (as per YAML specification). 
I have a problem because my host names contain the charachter "-" and WDT Tools don't accept unquoted strings with this special charachter. i.e.  

```
topology:
   Server:
      ListenAddress:  xxx-yyy-001
```

Regards
Antonella

**Comment by rjeberhard** [comment]
What version are of the deploy tool are you using? It looks like the recently released 1.9.20 fixes a very similar issue.
