### ISSUE TITLE
validator no longer using variable_file argument on call to validate

### ISSUE THREAD

**Issue by CarolynRountree** [oracle/weblogic-deploy-tooling#108]
I just merged master into my WIP branch for injecting variables into the model. Code has changed in the validator that ignores the variable file name passed on the function call to validate. My work is blocked by this problem.

Here is the new code that ignores the variable file name argument:
        if variables_file_name is not None:
            self._logger.info('WLSDPLY-05004', variables_file_name, class_name=_class_name, method_name=_method_name)
            try:
                if self._model_context.get_variable_file():
                    self._variable_properties = variables.load_variables(self._model_context.get_variable_file())
                variables.substitute(model_dict, self._variable_properties)
            except VariableException, ve:
                ex = exception_helper.create_validate_exception('WLSDPLY-20004', 'validateModel',
                                                                ve.getLocalizedMessage(), error=ve)
                self._logger.throwing(ex, class_name=_class_name, method_name=_method_name)
                raise ex

**Comment by mwooten** [comment]
The fix for this is in the second commit for Pull Request#109
