### ISSUE TITLE
RFE - generic file loading overrides

### ISSUE THREAD

**Issue by domingoip** [oracle/weblogic-deploy-tooling#1112]
discoverDomain to pick up overrides and plan files when using a directory structure as described by generic file loading overrides (https://docs.oracle.com/en/middleware/fusion-middleware/weblogic-server/12.2.1.4/depgd/config.html#GUID-BBCE91E3-87ED-4D3E-A5F1-DE9F9B7F97EA).

**Comment by ddsharpe** [comment]
The deployment directory structure is documented in WLS https://docs.oracle.com/cd/E13222_01/wls/docs103/deployment/deployunits.html#wp1045803.
Generic file overrides are documented in WLS https://docs.oracle.com/cd/E13222_01/wls/docs103/deployment/config.html#wp1066442

The AppFileOverrides folder is a subfolder of the plan directory, but is not captured in config.xml.  The reference from plan.xml in the context-root element to the plan folder enables the AppFileOverrides folder.

**Comment by ddsharpe** [comment]
Example plan file.
```xml
<deployment-plan ...>
  <application-name>webapp.war</application-name>
...
  <config-root>/some/directory/mywebapp/plan</config-root>
</deployment-plan>
```
