### ISSUE TITLE
Breaking change from 1.9.20 to 2.2.0 in parsing model file FRS

### ISSUE THREAD

**Issue by vdrHorst** [oracle/weblogic-deploy-tooling#1124]
Trying to upgrade WDT from 1.9.20 to 2.2.0 got following parsing error:

####<May 9, 2022 6:27:32 PM> <INFO> <WebLogicDeployToolingVersion> <logVersionInfo> <WLSDPLY-01750> <The WebLogic Deploy Tooling createDomain version is 2.2.0:.b3de93d:May 02, 2022 20:21 UTC>
####<May 9, 2022 6:27:32 PM> <INFO> <path_utils> <find_config_path> <WLSDPLY-01725> <Using configuration file /ohi/SWdepot/Oracle/weblogic-deploy-tooling/fsgbu_custom_config/typedefs/DOMFRS.json>
####<May 9, 2022 6:27:33 PM> <INFO> <ModelContext> <__copy_from_args> <WLSDPLY-01050> <WebLogic version for aliases is 12.2.1.4.0.220329>
####<May 9, 2022 6:27:33 PM> <SEVERE> <cla_helper> <load_model> <WLSDPLY-09014> <createDomain was unable to load the model from /ohi/domBase/DOMFRS12214/wdt.d/DOMFRS12214.wdt due to a translation error: Unable to parse model from file /ohi/domBase/DOMFRS12214/wdt.d/DOMFRS12214.wdt : Failed to parse file /ohi/domBase/DOMFRS12214/wdt.d/DOMFRS12214.wdt: while scanning a simple key
 in 'reader', line 59, column 5:
        !WLS_FORMS:
        ^
could not find expected ':'
 in 'reader', line 60, column 3:
      UnixMachine:
      ^
>

**Comment by vdrHorst** [comment]
Contents of wdt file:

[oracle@fsgbu-lon-199[BATEA21] ~]$ cat /ohi/domBase/DOMFRS12214/wdt.d/DOMFRS12214.wdt
domainInfo:
  AdminUserName: weblogic
  AdminPassword: xxxxxxx
  ServerStartMode: prod
  RCUDbInfo:
    rcu_prefix: DOMFRS12214
    rcu_db_user: rcu_admin
    rcu_admin_password: xxxxxxx
    rcu_schema_password: xxxxxxxx
    rcu_db_conn_string: 'localhost:1521/RCU'

topology:
  Name: DOMFRS12214
  AdminServerName: AS_FRS12214
  ProductionModeEnabled: true
  Log:
    FileCount: 10
    FileMinSize: 5000
  NMProperties:
    CrashRecoveryEnabled: true
    DomainsDirRemoteSharingEnabled: true
    PropertiesVersion: 12.2.1.4.0
  SecurityConfiguration:
    NodeManagerUsername: weblogic
    NodeManagerPasswordEncrypted: xxxxxxxx
  Cluster:
    cluster_forms:
      WeblogicPluginEnabled: true
  Server:
    AS_FRS12214:
      ListenPort: 6600
      Machine: localmachine
      Log:
        FileCount: 10
        FileMinSize: 5000
      SSL:
        Enabled: true
        ListenPort: 7600
      WebServer:
        WebServerLog:
          FileCount: 10
          RotationType: bySize
          FileMinSize: 5000
    MS_FORMS12214:
      ListenPort: 6610
      Machine: localmachine
      Cluster: cluster_forms
      JTAMigratableTarget:
        Cluster: cluster_forms
        UserPreferredServer: MS_FORMS12214
      SSL:
        ListenPort: 7610
        Enabled: true
      WebServer:
        WebServerLog:
          FileCount: 10
          RotationType: bySize
          FileMinSize: 5000
    !WLS_FORMS:
  UnixMachine:
    localmachine:
      NodeManager:
        ListenPort: 6699
        NMType: SSL
  Machine:
    !AdminServerMachine:

**Comment by rakillen** [comment]
Hello vdrHorst -

There were changes to the parser starting with WDT release 2.0 to make it more YAML compliant. In this case, `!WLS_FORMS` and other elements using '!' delete notation need to be in quotes now. There is a full list of changes here:
https://oracle.github.io/weblogic-deploy-tooling/release-notes/
Hope this helps!

**Comment by robertpatrick** [comment]
@vdrHorst As Richard said, we moved from a hand-coded parser I wrote with Antlr to the SnakeYaml parser, which is YAML 1.1 compliant.  As such, a few things that previously didn't require quoting now do require it (e.g., the delete syntax).  There are a lot more items that previously required quotes that no longer do (e.g., text with embedded hyphens), though the parser is happy to accept them either quoted or unquoted.

We have tried to provide guidance to users about the small changes to the YAML required to use the 2.x parser.  We also made a very conscience decision to make the version that introduces the changes a new major release to try to indicate that the changes were not completely backward compatible.  Let us know if you run into anything that is not documented and we will do our best to help.

**Comment by vdrHorst** [comment]
I am a bit (understatement) ashamed... 
I should have read the Release Notes ofcause, sorry.
Found the clear description on the change to SnakeYAML, describing exactly my problem.
Tested right away, and adding the quotes its even backwards compatible, so problem gone.
Keep up the great work on this tool!

**Comment by robertpatrick** [comment]
@vdrHorst No need to be ashamed, it happens to all of us from time to time.  Thanks for reporting what you saw as an issue.  Please do not hesitate to report issues that you find so that we can keep making the tool better.
