### ISSUE TITLE
python dict() cannot be updated with values in PyOrderedDict()

### ISSUE THREAD

**Issue by CarolynRountree** [oracle/weblogic-deploy-tooling#113]
I'm not sure that anything can be done, but I believe it needs to be looked at. It caused me some troubleshooting time, and someone else might run into this.

You cannot update python dict() with a PyOrderedDict()  dict.update(pyorderedict). All other forms of the update work (dict.update(dict), pyordereddict.update(dict), pyordereddict.update(pyorderdereddict))

I have attached a python script showing these different forms of the update and the results.
[testpyordered.zip](https://github.com/oracle/weblogic-deploy-tooling/files/2037045/testpyordered.zip)

**Comment by mwooten** [comment]
Hi Carolyn, 

II was able to fix this by using super in a couple strategic places, in the PyOrderedDict.java file. I created four unit tests from your testpyordered.py file, to verify that all four scenarios work as expected. Will create a branch and commit/push/pull request for it, now.
