### ISSUE TITLE
YAML parse error hyphenated names

### ISSUE THREAD

**Issue by dbeniteza** [oracle/weblogic-deploy-tooling#1206]
Hello,

While trying to run the Update Domain Tool in order to update a WebLogic data source, I faced the following error.
The name of the WebLogic data source contains multiple hyphens.
####<Sep 26, 2022 10:03:29 AM> <SEVERE> <ParsingErrorListener> <syntaxError> <WLSDPLY-18018> <Parse error for file /var/tmp/ansible-tmp-1664179362.394714-130021-138895667404395/model_file at line 3 position 16: token recognition error at: '-b'>\n####<Sep 26, 2022 10:03:29 AM> <SEVERE> <ParsingErrorListener> <syntaxError> <WLSDPLY-18018> <Parse error for file /var/tmp/ansible-tmp-1664179362.394714-130021-138895667404395/model_file at line 3 position 19: token recognition error at: '-j'>\n####<Sep 26, 2022 10:03:29 AM> <SEVERE> <ParsingErrorListener> <syntaxError> <WLSDPLY-18018> <Parse error for file /var/tmp/ansible-tmp-1664179362.394714-130021-138895667404395/model_file at line 3 position 23: token recognition error at: '-r'>\n####<Sep 26, 2022 10:03:29 AM> <SEVERE> <ParsingErrorListener> <syntaxError> <WLSDPLY-18018> <Parse error for file /var/tmp/ansible-tmp-1664179362.394714-130021-138895667404395/model_file at line 3 position 28: token recognition error at: '-i'>\n####<Sep 26, 2022 10:03:29 AM> <SEVERE> <ParsingErrorListener> <syntaxError> <WLSDPLY-18018> <Parse error for file /var/tmp/ansible-tmp-1664179362.394714-130021-138895667404395/model_file at line 3 position 31: token recognition error at: '-j'>\n####<Sep 26, 2022 10:03:29 AM> <SEVERE> <ParsingErrorListener> <syntaxError> <WLSDPLY-18018> <Parse error for file /var/tmp/ansible-tmp-1664179362.394714-130021-138895667404395/model_file at line 3 position 36: token recognition error at: '-j'>\n####<Sep 26, 2022 10:03:29 AM> <SEVERE> <ParsingErrorListener> <syntaxError> <WLSDPLY-18018> <Parse error for file /var/tmp/ansible-tmp-1664179362.394714-130021-138895667404395/model_file at line 3 position 40: token recognition error at: '-u'>\n####<Sep 26, 2022 10:03:29 AM> <SEVERE> <ParsingErrorListener> <syntaxError> <WLSDPLY-18018> <Parse error for file /var/tmp/ansible-tmp-1664179362.394714-130021-138895667404395/model_file at line 7 position 28: token recognition error at: '-b'>\n####<Sep 26, 2022 10:03:29 AM> <SEVERE> <ParsingErrorListener> <syntaxError> <WLSDPLY-18018> <Parse error for file /var/tmp/ansible-tmp-1664179362.394714-130021-138895667404395/model_file at line 7 position 31: token recognition error at: '-j'>\n####<Sep 26, 2022 10:03:29 AM> <SEVERE> <ParsingErrorListener> <syntaxError> <WLSDPLY-18018> <Parse error for file /var/tmp/ansible-tmp-1664179362.394714-130021-138895667404395/model_file at line 7 position 35: token recognition error at: '-r'>\n####<Sep 26, 2022 10:03:29 AM> <SEVERE> <ParsingErrorListener> <syntaxError> <WLSDPLY-18018> <Parse error for file /var/tmp/ansible-tmp-1664179362.394714-130021-138895667404395/model_file at line 7 position 40: token recognition error at: '-i'>\n####<Sep 26, 2022 10:03:29 AM> <SEVERE> <ParsingErrorListener> <syntaxError> <WLSDPLY-18018> <Parse error for file /var/tmp/ansible-tmp-1664179362.394714-130021-138895667404395/model_file at line 7 position 43: token recognition error at: '-c'>\n####<Sep 26, 2022 10:03:29 AM> <SEVERE> <ParsingErrorListener> <syntaxError> <WLSDPLY-18018> <Parse error for file /var/tmp/ansible-tmp-1664179362.394714-130021-138895667404395/model_file at line 3 position 18: no viable alternative at input 'snsfarmae'>\n####<Sep 26, 2022 10:03:29 AM> <SEVERE> <ParsingErrorListener> <syntaxError> <WLSDPLY-18018> <Parse error for file /var/tmp/ansible-tmp-1664179362.394714-130021-138895667404395/model_file at line 7 position 30: mismatched input 'e' expecting {COMMENT, NEWLINE}>\n####<Sep 26, 2022 10:03:29 AM> <SEVERE> <cla_helper> <load_model> <WLSDPLY-09014> <updateDomain was unable to load the model from /var/tmp/ansible-tmp-1664179362.394714-130021-138895667404395/model_file due to a translation error: Unable to parse model from file /var/tmp/ansible-tmp-1664179362.394714-130021-138895667404395/model_file : The YAML parser encountered 14 error(s) while parsing /var/tmp/ansible-tmp-1664179362.394714-130021-138895667404395/model_file>\nupdateDomain.sh failed (exit code = 2)\n

According to the documentation samples, https://oracle.github.io/weblogic-deploy-tooling/samples/jdbc-model/, names can contain hyphens.
The problem could be solved by enclosing the hyphenated name with quotes, but since the all the WebLogic resource names from the domains are hyphenated, it would be convenient to allow hyphenated names.

**Comment by robertpatrick** [comment]
@dbeniteza The log you provided left out the entry that shows the version of WDT being used.  We changed the YAML parser in WDT 2.0.0 to use Snake YAML, which claims to be a YAML 1.1-compliant parser.

I am unable to produce the problem with current versions of WDT using the following model:

```
domainInfo:
    AdminUserName: weblogic
    AdminPassword: welcome1
topology:
    Name: my-domain
    AdminServerName: Admin-Server
    Server:
        Admin-Server:
            Notes: This is a note with-a-lot-of hyphens
        Server-0:
```

Running createDomain.sh results in:

```
JDK version is 1.8.0_271-b09
JAVA_HOME = /Library/Java/JavaVirtualMachines/jdk1.8.0_271.jdk/Contents/Home
WLST_EXT_CLASSPATH = /Users/rpatrick/tmp/wdt/weblogic-deploy/lib/weblogic-deploy-core.jar
CLASSPATH = /Users/rpatrick/tmp/wdt/weblogic-deploy/lib/weblogic-deploy-core.jar
WLST_PROPERTIES = -Dcom.oracle.cie.script.throwException=true -Djava.util.logging.config.class=oracle.weblogic.deploy.logging.WLSDeployLoggingConfig 
/opt/weblogic/soa12214/oracle_common/common/bin/wlst.sh /Users/rpatrick/tmp/wdt/weblogic-deploy/lib/python/create.py -oracle_home /opt/weblogic/soa12214 -domain_parent /Users/rpatrick/tmp/wdt -model_file /Users/rpatrick/tmp/wdt/model.yaml

Initializing WebLogic Scripting Tool (WLST) ...

Welcome to WebLogic Server Administration Scripting Shell

Type help() for help on available commands

####<Sep 28, 2022 6:09:19 PM> <INFO> <WebLogicDeployToolingVersion> <logVersionInfo> <WLSDPLY-01750> <The WebLogic Deploy Tooling createDomain version is 2.3.4-SNAPSHOT:main.7a25ea7:Sep 28, 2022 23:08 UTC>
####<Sep 28, 2022 6:09:19 PM> <INFO> <WLSDeployLoggingConfig> <logLoggingDirectory> <WLSDPLY-01755> <The createDomain program will write its log to directory /Users/rpatrick/tmp/wdt/weblogic-deploy/logs>
####<Sep 28, 2022 6:09:19 PM> <INFO> <ModelContext> <__copy_from_args> <WLSDPLY-01050> <WebLogic version for aliases is 12.2.1.4.0>
####<Sep 28, 2022 6:09:19 PM> <INFO> <ModelContext> <__copy_from_args> <WLSDPLY-01050> <WebLogic version for aliases is 12.2.1.4.0.210930>
####<Sep 28, 2022 6:09:19 PM> <INFO> <filter_helper> <apply_filters> <WLSDPLY-20017> <No filter configuration file /Users/rpatrick/tmp/wdt/weblogic-deploy/lib/model_filters.json>
####<Sep 28, 2022 6:09:19 PM> <INFO> <filter_helper> <apply_filters> <WLSDPLY-20016> <No filters of type create found in filter configuration file /Users/rpatrick/tmp/wdt/weblogic-deploy/lib/model_filters.json>
####<Sep 28, 2022 6:09:20 PM> <INFO> <DomainCreator> <__create_domain> <WLSDPLY-12203> <Creating domain of type WLS>
####<Sep 28, 2022 6:09:20 PM> <INFO> <DomainCreator> <__create_base_domain_with_select_template> <WLSDPLY-12210> <Selecting base template named Basic WebLogic Server Domain>
####<Sep 28, 2022 6:09:31 PM> <INFO> <DomainCreator> <__extend_domain_with_select_template> <WLSDPLY-12212> <Loading selected templates>
####<Sep 28, 2022 6:09:33 PM> <INFO> <DomainCreator> <__set_domain_name> <WLSDPLY-12227> <Changing domain name from base_domain to my-domain>
####<Sep 28, 2022 6:09:33 PM> <INFO> <DomainCreator> <__set_admin_server_name> <WLSDPLY-12229> <Changing the administration server name from AdminServer to Admin-Server>
####<Sep 28, 2022 6:09:33 PM> <INFO> <TopologyHelper> <create_placeholder_named_elements> <WLSDPLY-19403> <Creating placeholder for Server Server-0>
####<Sep 28, 2022 6:10:20 PM> <INFO> <Creator> <_create_named_mbeans> <WLSDPLY-12101> <Updating Server with the name Admin-Server>
####<Sep 28, 2022 6:10:20 PM> <INFO> <Creator> <_create_named_mbeans> <WLSDPLY-12101> <Updating Server with the name Server-0>
####<Sep 28, 2022 6:10:20 PM> <INFO> <Creator> <_create_named_mbeans> <WLSDPLY-12101> <Updating Server with the name Admin-Server>
####<Sep 28, 2022 6:10:20 PM> <INFO> <Creator> <_create_named_mbeans> <WLSDPLY-12101> <Updating Server with the name Server-0>
####<Sep 28, 2022 6:10:20 PM> <INFO> <DomainCreator> <__extend_domain_with_select_template> <WLSDPLY-12205> <Writing base domain my-domain to directory /Users/rpatrick/tmp/wdt/my-domain>
####<Sep 28, 2022 6:10:23 PM> <INFO> <DomainCreator> <__extend_domain_with_select_template> <WLSDPLY-12206> <Closing templates for domain my-domain>
####<Sep 28, 2022 6:10:24 PM> <INFO> <DefaultAuthenticatorHelper> <create_default_init_file> <WLSDPLY-01900> <Append to default authenticator initialization file /Users/rpatrick/tmp/wdt/my-domain/security/DefaultAuthenticatorInit.ldift>
####<Sep 28, 2022 6:10:24 PM> <INFO> <LibraryHelper> <install_domain_libraries> <WLSDPLY-12213> <The model did not specify any domain libraries to install>
####<Sep 28, 2022 6:10:24 PM> <INFO> <LibraryHelper> <extract_classpath_libraries> <WLSDPLY-12216> <The archive file was not provided so there are no classpath libraries to extract>
####<Sep 28, 2022 6:10:24 PM> <INFO> <LibraryHelper> <extract_custom_files> <WLSDPLY-12565> <The archive file was not provided so there are no custom files to extract>
####<Sep 28, 2022 6:10:24 PM> <INFO> <LibraryHelper> <install_domain_scripts> <WLSDPLY-12241> <The model did not specify any domain scripts to install>

Issue Log for createDomain version 2.3.4-SNAPSHOT running WebLogic version 12.2.1.4.0.210930 offline mode:

Total:       WARNING :     0    SEVERE :     0

createDomain.sh completed successfully (exit code = 0)
```

My suggestion is to move to the latest release of WDT and try again.  If this does not solve your problem, please provide the WDT version, full model file, and full updateDomain.log file (i.e., not stdout).

**Comment by dbeniteza** [comment]
# cat VERSION.txt
WebLogic Deploy Tooling 2.3.3

See attached file: updateDomain.log
[updateDomain.log](https://github.com/oracle/weblogic-deploy-tooling/files/9672574/updateDomain.log)

test.yaml
resources:
    JDBCSystemResource:
        my-jdbc-ds:
            JdbcResource:
                JDBCConnectionPoolParams:
                    MaxCapacity: 100
            Target: my-cluster

**Comment by robertpatrick** [comment]
@dbeniteza From the first line of your updateDomain.log file, it is clear that you are using release 1.9.20:

```
####<Sep 29, 2022 9:33:28 AM> <INFO> <WebLogicDeployToolingVersion> <logVersionInfo> <WLSDPLY-01750> <The WebLogic Deploy Tooling updateDomain version is 1.9.20:release-1.9.x.54d9dcb:Jan 11, 2022 21:44 UTC>
```

As such, this limitation is expected.  Please make sure you are using 2.3.3 (the first line of the log file will tell you exactly what version is being used).

**Comment by dbeniteza** [comment]
@robertpatrick thanks for your help. Moving to 2.3.3 version solves the problem.

**Comment by dbeniteza** [comment]
Moving to 2.3.3 version solves the problem.
