### ISSUE TITLE
Online deploy app error weblogic standalone 12.2.14

### ISSUE THREAD

**Issue by charlinuxgnome** [oracle/weblogic-deploy-tooling#1312]
[weblogic_deploy_tooling_issue_deployApps.log](https://github.com/oracle/weblogic-deploy-tooling/files/10156493/weblogic_deploy_tooling_issue_deployApps.log)
[weblogic_deploy_tooling_issue_stdout.txt](https://github.com/oracle/weblogic-deploy-tooling/files/10156494/weblogic_deploy_tooling_issue_stdout.txt)

**Comment by robertpatrick** [comment]
@charlinuxgnome We are currently working on WDT 3.0 and the current plan is to try to release that in February.  Unfortunately, our `main` branch already has a couple of breaking changes fixing a few attribute names that did not follow our convention so I would prefer to not try to make an interim release if it isn't an emergency.  If you build your own installer from main right now, I suspect this will resolve your issue and likely not negatively impact you.  Thoughts?

**Comment by robertpatrick** [comment]
WDT 3.0 released so closing this issue as resolved.  Please open a new issue if you encounter problems using WDT 3.0.
