### ISSUE TITLE
compare tool flagging false positive

### ISSUE THREAD

**Issue by WhatDoor** [oracle/weblogic-deploy-tooling#1370]
Hi, 

I was testing out the compare tool and found that it was raising this as a difference in the diffed yaml file. 

`Arguments: -Xms2048m -Xmx4096m -XX:+UseConcMarkSweepGC -Dweblogic.security.SSL.nojce=true
                    -Dweblogic.rjvm.enableprotocolswitch=true -DUseSunHttpHandler=true  -Dcom.sun.net.ssl.enableECC=false  -Djsse.enableSNIExtension=false  -Dweblogic.security.allowCryptoJDefaultPRNG=true,!-Xms2048m
                    -Xmx4096m -XX:+UseConcMarkSweepGC -Dweblogic.security.SSL.nojce=true
                    -Dweblogic.rjvm.enableprotocolswitch=true -DUseSunHttpHandler=true
                    -Dcom.sun.net.ssl.enableECC=false -Djsse.enableSNIExtension=false
                    -Dweblogic.security.allowCryptoJDefaultPRNG=true
`

As far as I can tell, what it is deleting and replacing is the same and the only difference between these is that there are 2 spaces between some of the flags instead of 1. Is this expected behaviour?

**Comment by jshum2479** [comment]
@WhatDoor   We only check the value of the attribute and as long as they are different then they are considered different.  For example, if you rearrange the ordering of the attribute value in each model, then they are considered different.

**Comment by robertpatrick** [comment]
@WhatDoor Can you tell us how you got the two models you are comparing?  Just want to make sure we fix your use case...

**Comment by WhatDoor** [comment]
I got this by running the discover tool on our dev weblogic instance twice on two separate days, and then compared those two resulting models. As far as I know, no one has done anything to this config.
