### ISSUE TITLE
Question: Can/Will ServerComponents like OHS (and FORMS) be supported in future release?

### ISSUE THREAD

**Issue by vdrHorst** [oracle/weblogic-deploy-tooling#143]
In WLST we use `ohs_createInstance()` to create a Oracle HTTP Server component as ServerComponent in our Weblogic domain.
And `createFormsComponent()` to create Oracle Forms components.
When discovery is run, these components are not taken into account into the current MetaData Model.

Can/Will these kind of ServerComponents be supported in a future release? Currently we need to run a post wlst script to add these to our standard domain.

**Comment by ddsharpe** [comment]
Neither have been discussed or considered, yet.  The issue is potentially broader than just these two components and we should definitely discuss the addition of components to the model.

REF https://docs.oracle.com/middleware/1212/webtier/HSADM/getstart.htm#HSADM845

**Comment by ddsharpe** [comment]
We started discussing this topic again today.  At a minimum, we would like to add the OHS configuration to the model.  Can you please post the WLST that you use to add OHS and Forms components?  We would like to get an idea of the scope of your use case.  Looking at the MBeans, there doesn't appear to be a lot that we can offer.  In the OHS configuration case, how do you handle http.conf changes?

**Comment by ddsharpe** [comment]
Can you please post your WLST so that we can ensure coverage of your use case?  I would like to get this in the next release.

**Comment by vdrHorst** [comment]
**Steps to create FSGBU OHI workable Forms domain in WLserver 12.2.1.3**
(install FMW 12.2.1.3 Infrastructure)
(install FMW Forms and Reports 12.2.1.3, actually add in FMW infrafstructure)
(create RCU database and create repository for Forms domain, COMPONENTLIST=STB,WLS,OPSS,IAU,IAU_APPEND,IAU_VIEWER)

**Either GUI install (not interesting for WDT scripting, but as reference):**
  - run $ORACLE_HOME/oracle_common/common/bin/config.sh
  - create new domain, location, with Product Templates : "Oracle Forms" and "Oracle HTTP Server (Collocated)"
  ...
  - Advanced Configuration on "System Components"
  ...
  - Keep default System Component "forms1" (type FORMS)
  - Add new System Component "ohs12213" (type OHS) --> Name can be choosen.
  - Assign these System Components to WLS "Machines"
  After successfull GUI creation, the OHS can be started using "$DOMAIN_HOME/bin/startComponent.sh ohs12213"

But that is not what we want, as we would like to config it all without GUI.
**So, current install without GUI is:**
  - run Weblogic Deploy Tool (DOMFRS12213.wdt file as example below) 
  - this will create the wanted WLS AdminServer and Managed Server and settings, but no OHS System Component
  - The "forms1" System Component (type FORMS) seems to be partially present though, see below
  - Run extra WLST script to create the OHS System Component:
    - Connect to the (running?! ... we do...) AdminServer of the domain
                - run WLST command/function "ohs_createInstance(<Name>, <machinename>, <listenPort>, <sslPort>, <adminPort>)"

**Investigations:**
  - the called WLST function "ohs_createInstance" originates in $FMW_HOME/em/archives/fmwctrl/plugins/em_webtier.war
  (most likely only present/installed with the FMW Forms install addition to FMW infrastructure.)
  - there is also a $FMW_HOME/em/archives/fmwctrl/plugins/em_forms.war present, most likely for the System Component type "FORMS"
  - when System Components are not (yet) created, the directory "$DOMAIN_HOME/system_components" is NOT present
  - when System Components are created, directories "$DOMAIN_HOME/system_components/<TYPE>/<name>/data (and others) are present
  (where in our case <TYPE> is one of "FORMS" or "OHS")
  - in the tail of the "$DOMAIN_HOME/config/config.xml" file, the <system-component> is modelled
  - the directories "$DOMAIN_HOME/config/fmwconfig/components/FORMS" and "../components/OHS" exists, even without running "ohs_createInstance"
  (there is no "../instances/..." directory yet, which will most likely be created on initial run)
  
It seems logical (to me, but who am I) that the configuration wdt.yaml file would have a new "SystemComponent" in the "topology:" section, like
<snippet>
topology:
  Name: .....
  Server:
    AdminServerName:
                  ...
                ManagedServerName:
                  ...
  SystemComponent:
        forms1:
                  Type: FORMS
        ohs12213:
                  Type: OHS
                  Machine: <machinename>
                  ListenPort: <listenPort>
                  SSLPort: <sslPort>
                  AdminPort: <adminPort>


Example DOMFRS12213.wdt
====================
topology:
  Name: DOMFRS12213
  AdminServerName: AS_FRS12213
  Cluster:
    cluster_forms:
      WeblogicPluginEnabled: true
  Server:
    AS_FRS12213:
      Machine: localmachine
      ListenPort: 6300
      SSL:
        ListenPort: 7300
        Enabled: false
    MS_FORMS12213:
      Machine: localmachine
      Cluster: cluster_forms
      ListenPort: 6310
      SSL:
        ListenPort: 7310
        Enabled: true
    !WLS_FORMS:
  UnixMachine:
    localmachine:
      NodeManager:
        ListenPort: 6399
        NMType: SSL
  Machine:
    !AdminServerMachine:

Example DOMFRS12213_addOHS.wlst
===========================
connect('weblogic','<passwd>','localhost:6300')
ohs_createInstance(instanceName='ohs12213',machine='localmachine',listenPort=6380,sslPort=7380,adminPort=6381)
exit()

WLST commandline examples:
=================================
wls:/offline> help('manageohs')

List commands for managing Oracle HTTP Server instances.
    help('ohs_addAdminProperties')   Add a property to OHS Admin server property file (ohs_admin.properties).
    help('ohs_addNMProperties')   Add a property to OHS Node Manager plugin property file (ohs_nm.properties).
    help('ohs_createInstance')   Create a managed Oracle HTTP Server instance.
    help('ohs_createTestDomain')   Create a compact domain for testing or other non-production use of Oracle HTTP Server. This method is now deprecated.
    help('ohs_deleteInstance')   Delete a managed Oracle HTTP Server instance.
    help('ohs_exportKeyStore')   Export the keyStore to the specified Oracle HTTP Server instance.
    help('ohs_updateInstances')   Perform post instance creation tasks.


wls:/offline> help('ohs_createInstance')

Description:

Create a managed Oracle HTTP Server instance, optionally specifying ports and server
name configuration.

The ohs_createInstance command is available when WLST is connected to an
Administration Server instance.

Syntax:

ohs_createInstance(instanceName='instance-name', machine='machine-name', listenPort = nnnn,
                  sslPort = nnnn, adminPort = nnnn, serverName = 'server-name')
    instanceName  - This is the name of the managed instance being created.
    machine       - This is the existing machine entry for the instance.
    listenPort    - Optional.  This is the port number of the non-SSL server.  If this
                    is not specified, a port will be assigned automatically.
    sslPort       - Optional.  This is the port number of the SSL virtual host.  If this
                    is not specified, a port will be assigned automatically.
    adminPort     - Optional.  This is the port number used for communication with Node Manager.
                    If this is not specified, a port will be assigned automatically.
    serverName    - Optional.  This is the value of the ServerName directive of non-SSL server.
                    If this is not specified, the hostname of the machine and the listen port
                    will be used to construct the value.

Example:

ohs_createInstance(instanceName = 'example', machine = 'localmachine',
                  listenPort = 10080, sslPort = 10443, serverName = 'OHS1')

**Comment by vdrHorst** [comment]
This works perfectly! Thanks for the enhancement
