### ISSUE TITLE
Enhancement request: Add removal of objects into the MetaData model

### ISSUE THREAD

**Issue by vdrHorst** [oracle/weblogic-deploy-tooling#144]
From the README explanation it is clear that renaming existing objects (like Managed Servers) is not supported. 
> ...the WebLogic Deploy Tooling does not support the use of the Name attribute in these folders and any attempt to set the Name attribute will not be honored.

But would it be possible to model a "not wanted object any more" into the model? Which will be deleted when the domain is `updateDomain` (or even on `createDomain` where the template adds a not wanted object)?
Possible modelling solution in yaml `model_file` could be to put an exclamation mark "!" in front of the object name, causing it to be deleted or removed to be set. 

(Rationale: When creating a default Forms domain, the managed server from the extentionTemplate "Oracle Forms" is defaulted to "WLS_FORMS" and cannot be overwritten with the `createDomain` resulting in a obsolete Managed Server after initial run.

**Comment by ddsharpe** [comment]
Removing existing objects is definitely on the desired feature list.  The plan is to add an additional feature like "merge to the model" which must support removal of unwanted existing objects.  The default behavior will remain the same where models are additive to the domain being updated.  The new merge to the model feature will take a model and remove anything in the existing domain that is not found in the model.  It is not clear at this point if the tool will need a simple "remove" feature as well.

**Comment by vdrHorst** [comment]
I can see that @rakillen already committed some changes in code https://github.com/oracle/weblogic-deploy-tooling/commit/322c696b8df3270d7cb872dcc9fb84000e29dd54

Does this mean the enhancement request has been added in the tool already?

**Comment by rakillen** [comment]
No, this is still pending.  Some initial work has been done on that branch.

**Comment by vdrHorst** [comment]
Didn't expect my question would trigger a close...🤔😞😟

**Comment by rakillen** [comment]
Oops, sorry!

**Comment by CarolynRountree** [comment]
I am not sure why this was closed. The enhancement is in the testing stage and will be in the next release.
