### ISSUE TITLE
missing domain param

### ISSUE THREAD

**Issue by negast** [oracle/weblogic-deploy-tooling#1471]
Hello

When I'm trying to discover a domain I see following param in de the domain is missing.

`Enable RESTful Management Services`
is this something that can be added?
I've tried with online and offline discovery.
I don't know much about the code but it is normally in the path /RestfulManagementServices/<DOMAIN>

**Comment by rakillen** [comment]
Hello negast -
I was able to create and discover a domain with a `RestfulManagementServices` section in the model. The discovered model looked like this:
```
topology:
    Name: DemoDomain
    RestfulManagementServices:
        Enabled: false
        Notes: test
```
You may not be seeing this section in your discovered model if there are no attributes with non-default values. For WLS 12.2.1 and later, the default value for the `Enabled` attribute is `true`.

I tested with WLS 12.2.1.4 offline. Let me know if you're having problems with a different version.

**Comment by robertpatrick** [comment]
@negast Please see Richard's comment above and let us know if this is still an issue for you.

**Comment by negast** [comment]
Hello this is indeed on an oracle cloud instance running weblogic 14.
If I add 
```
topology:
    Name: DemoDomain
    RestfulManagementServices:
        Enabled: false
        Notes: test
```
will it work?

**Comment by rakillen** [comment]
Restful Management Services is enabled/checked by default on WLS domain creation, so you don't need to have that section in your model, unless you want to disable it.

**Comment by negast** [comment]
Ok I think I was checking on the one were we enabled it. And then indeed the param does not show. I took an export of the disabled one and it was set to false there. If I added the block as you mentioned and set it to true it did activate it again. Thank you for your help.
