### ISSUE TITLE
Unable to discover app SB_JMS_Proxy_ae95651.N246372bc.0.188def01f3a.N8000 since the application source path is empty

### ISSUE THREAD

**Issue by zukko78** [oracle/weblogic-deploy-tooling#1473]
We have an issue discovering the FMW OSB domain, domain details:

<Jun 21, 2023 7:22:37 PM GMT> <Info> <Management> <BEA-141107> <Version: WebLogic Server 12.2.1.4.0
OPatch Patches:
34065178;24731214;Sat Jun 18 01:48:33 GMT 2022;One-off
34044738;24719205;Sat Jun 18 01:48:07 GMT 2022;FMW Thirdparty Bundle Patch 12.2.1.4.220406
34012040;24705947;Sat Jun 18 01:47:32 GMT 2022;WLS PATCH SET UPDATE 12.2.1.4.220329
33965482;24684630;Sat Jun 18 01:46:18 GMT 2022;SOA Bundle Patch 12.2.1.4.220315
33950717;24677093;Sat Jun 18 01:44:48 GMT 2022;OPSS Bundle Patch 12.2.1.4.220311
33546536;24718505;Sat Jun 18 01:44:17 GMT 2022;One-off
33093748;24325771;Sat Jun 18 01:43:51 GMT 2022;One-off
32720458;24558359;Sat Jun 18 01:43:42 GMT 2022;JDBC 19.3.0.0 FOR CPUJAN2022 (WLS 12.2.1.4, WLS 14.1.1)
32410850;24028986;Sat Jun 18 01:43:29 GMT 2022;One-off
31713426;23829342;Sat Jun 18 01:43:20 GMT 2022;One-off
31544353;23673193;Sat Jun 18 01:42:54 GMT 2022;One-off
30613424;24331010;Sat Jun 18 01:42:45 GMT 2022;One-off
1221413;24662161;Sat Jun 18 01:42:36 GMT 2022;Bundle patch for Oracle Coherence Version 12.2.1.4.13
33618954;24526311;Sat Jun 18 01:42:27 GMT 2022;OWSM BUNDLE PATCH 12.2.1.4.211129
32121987;23905468;Sat Jun 18 01:41:58 GMT 2022;OSB Bundle Patch 12.2.1.4.201105> 

 WebLogic Deploy Tooling - 3.2.1

####<Jun 21, 2023 8:37:59 PM> <INFO> <DeploymentsDiscoverer> <add_application_to_archive> <WLSDPLY-06393> <Will not add application MSMQAdapter from Oracle installation directory to archive>
####<Jun 21, 2023 8:37:59 PM> <INFO> <DeploymentsDiscoverer> <get_applications> <WLSDPLY-06392> <Adding Application OracleAppsAdapter>
####<Jun 21, 2023 8:38:01 PM> <INFO> <DeploymentsDiscoverer> <add_application_to_archive> <WLSDPLY-06393> <Will not add application OracleAppsAdapter from Oracle installation directory to archive>
####<Jun 21, 2023 8:38:01 PM> <INFO> <DeploymentsDiscoverer> <get_applications> <WLSDPLY-06392> <Adding Application OracleBamAdapter>
####<Jun 21, 2023 8:38:03 PM> <INFO> <DeploymentsDiscoverer> <add_application_to_archive> <WLSDPLY-06393> <Will not add application OracleBamAdapter from Oracle installation directory to archive>
####<Jun 21, 2023 8:38:04 PM> <INFO> <DeploymentsDiscoverer> <get_applications> <WLSDPLY-06392> <Adding Application SAPAdapter>
####<Jun 21, 2023 8:38:06 PM> <INFO> <DeploymentsDiscoverer> <add_application_to_archive> <WLSDPLY-06393> <Will not add application SAPAdapter from Oracle installation directory to archive>
####<Jun 21, 2023 8:38:06 PM> <INFO> <DeploymentsDiscoverer> <get_applications> <WLSDPLY-06392> <Adding Application SB_JMS_Proxy_ae95651.N246372bc.0.188def01f3a.N8000>
####<Jun 21, 2023 8:38:06 PM> <SEVERE> <discover> <main> <WLSDPLY-06011> <discoverDomain failed to discover domain app-domain3 at /shared/domains/app-domain3 : Unable to discover app SB_JMS_Proxy_ae95651.N246372bc.0.188def01f3a.N8000 since the application source path is empty>

Issue Log for discoverDomain version 3.2.0 running WebLogic version 12.2.1.4.0.220329 online mode:

SEVERE Messages:

        1. WLSDPLY-06011: discoverDomain failed to discover domain app-domain3 at /shared/domains/app-domain3 : Unable to discover app SB_JMS_Proxy_ae95651.N246372bc.0.188def01f3a.N8000 since the application source path is empty

Total:   SEVERE :    1  WARNING :    0

discoverDomain.sh failed (exit code = 2)

**Comment by zukko78** [comment]
Info from Adminconsole:
Deployment:
SB_JMS_Proxy_ae97ebd.60a4e3a5.0.188cbcf4728.N8000 | Active | OK | Enterprise Application | osb_cluster_1 | Global |   | 100


Name: | SB_JMS_Proxy_ae95651.N246372bc.0.188def01f3a.N8000
Scope: | Global
Path: | / shared/ domains/app-domain3/ sbgen/ jms/ SB_JMS_Proxy_ae95651.N246372bc.0.188def01f3a.N8000. ear
-- | --
Deployment Plan: | / shared/ domains/ app-domain3/ sbgen/ jms/ plan/SB_JMS_Proxy_ae95651.N246372bc.0.188def01f3a.N8000_Plan. xml
-- | --

**Comment by zukko78** [comment]
we run discover tool something like that:

./discoverDomain.sh -oracle_home /u01/oracle -domain_type OSB -domain_home .....

**Comment by robertpatrick** [comment]
@zukko78 Since WDT doesn't provide the typedef for OSB, you need to edit your typedef to filter out applications and other resources that you want WDT to skip over.  For example, adding something like this to the typedef file:

```
"discover-filters": {
    "/Application": [
        "^SB_JMS_Proxy.*"
    ]
}
```

will cause WDT to not try to discover the OSB JMS Proxy applications.

**Comment by robertpatrick** [comment]
Feel free to reopen the issue if this doesn't resolve your issue.
