### ISSUE TITLE
Alias get_model_attribute_and_value should check for default after path token

### ISSUE THREAD

**Issue by CarolynRountree** [oracle/weblogic-deploy-tooling#151]
Aliases.get_model_attribute_and_value returns a null if the wlst attribute value is a default value. This allows minimal population of the model. While doing a fix for NMProperties, I noticed that attributes that use a path token have a default value with the token. This is a great idea. However, the check for default seems to be done before the token is applied to the path. 

Attaching a model file to show the default value is populated in the model.
[nmprops.txt](https://github.com/oracle/weblogic-deploy-tooling/files/2329560/nmprops.txt)

**Comment by CarolynRountree** [comment]
Below a few examples to explain what we should address. The objective is to clean up what is generated in the model by discover. We need to be sensitive that we don't over simplify the test for default to a point that we don't recognize something the user generated instead of wlst auto generation.   

Attribute= value is returned from the wlst attribute, Alias= is the default_value on the alias definition.  

1. Here is an example of the slashes generated differently in Windows. This is a nice easy one to compare, except if we put a default value in the alias definition, currently that definition will only work for one of the two different file path types.  
```
 /WLDFSystemResource/WLDFResource/WatchNotification/ImageNotification/ImageDirectory: 
  Attribute=logs\diagnostic_images : Alias=None
```
2. We have a problem with config descriptor files for resource groups versus global. The descriptor file names for resource groups or templates in a partition are stored in a different folder location than the global or resource group and resource group template. The user can choose the folder location. If he does not, then WLST generates a folder location and name. In aliases, our resource group and partition pulls in the global json file, which has a different default value.  
```
/Partition/ResourceGroup/JMSSystemResource/SourcePath  :
Attribute=./config/partitions/Partitions-29690/jms/jmssystemresources-60017-jms.xml  :  Alias=None

/ResourceGroup/JMSSystemResource/SourcePath :
Attribute=./config/jms/jmssystemresources-23111-jms.xml  :  Alias=None

/JMSSystemResource/SourcePath :
Attribute=./config/jms/jmssystemresources-39266-jms.xml  :  Alias=None
```
  * Note the ./ in the front of the path (which to wlst simply means relative to the domain)    

  * Note that the jmssystemresources-39266-jms.xml is generated by WLST. We have to be careful not to dismiss what a user might have entered for the file name. However, if we put this in the model (more junk in the model), and the user does not remove it before a create/update, then the wlst attributed will be updated with this on-premise datasource generated name. This doesn't seem to really matter (other than the junk in the model) until you use update, and WLST has generated the same name for an existing config file. Fairly unlikely but not impossible. 
  * Note one of the subfolder names is the name of the mbean (in this case the mbean name is Partitions-29690). A token that represents if the name is the mbean name ignore it, would work here.
3. Here is another interesting scenario (wish they were all like this). This prefix was generated by wlst. We can simply do a straight comparision. However, we need to make sure we don't do any stripping of the variable ${serverName}.
```
/ServerTemplate/TransactionLogJDBCStore/PrefixName:                                                                            Attribute=TLOG_${serverName}_  :  Alias=None
```

**Comment by rakillen** [comment]
Converted to Jira WDT-281
