### ISSUE TITLE
Server Start Arguments are not working

### ISSUE THREAD

**Issue by sebmichiels** [oracle/weblogic-deploy-tooling#1523]
Dears,

In our WDT model, we are using the Start Arguments of the managed servers. It's a simple managed server in a Cluster. This managed server contains start arguments : 
`Server Start:
  Arguments: '-Dtest=test`

When the WebLogic operator starts the managed server, this argument is not added to the JAVA Options. I tried to set JAVA OPTIONS directly in the domain and it's working. But in our case, we want to have the arguments in the model.

I saw a few examples in your code. So I guess it should work. 

In the log, we can see that the node manager is started but the JAVA_OPTIONS are only: 
`JAVA_OPTIONS=-Dweblogic.system.BootIdentityFile=/u01/domain/test-env01/servers/m1/security/boot.properties -Dweblogic.nodemanager.ServiceEnabled=true -Dweblogic.nmservice.RotationEnabled=true -Djava.security.egd=file:/dev/./urandom  -Dweblogic.Stdout=/u01/domain/test-env01/servers/m1/logs/m1.out -XX:+CrashOnOutOfMemoryError`

When I check in the console, the arguments of the server start are there. Idem in the config.xml file. So, it seems that the WDT model is ok but not taken into account. It seems also that the Node Manager is used to start the managed server. 

Any ideas? Is there is a specific way to enable it?

Thanks.

**Comment by robertpatrick** [comment]
@sebmichiels This is a WebLogic Kubernetes Operator limitation.  You must use the environment variables to pass in system properties instead of Server Start Arguments.  See https://oracle.github.io/weblogic-kubernetes-operator/managing-domains/manage-domains/#important-considerations-for-weblogic-domains-in-kubernetes for more information.
