### ISSUE TITLE
Configure Oracle Diagnostic Log Handler at level of Server Template / Dynamic Server

### ISSUE THREAD

**Issue by brieucolivier** [oracle/weblogic-deploy-tooling#1527]
We are trying to configure a log handler in our WDT Model. In our case we would like to modify the supplemental attributes. After checking the code, we noticed (in odl_deployer.py) that it is only possible for concrete instances of servers. Is it planned to make it possible to manage for Server Template / Dynamic Servers configuration? 
BR.

**Comment by robertpatrick** [comment]
@brieucolivier It looks like it is already supported for Dynamic Servers...what am I missing?

https://github.com/oracle/weblogic-deploy-tooling/blob/main/core/src/main/python/wlsdeploy/tool/deploy/odl_deployer.py#L114-L122

**Comment by robertpatrick** [comment]
@brieucolivier I am confused.

The ServerTemplate has nothing to do with either the `DynamicClusterSize` or the `ServerNamePrefix`--both are defined in the `DynamicServers` folder of a `Cluster`.  Presumably, your properties file already has an entry that looks something like this:

```
Cluster.mycluster.DynamicServers.DynamicServerCount=4
```

Why can't you add another property to that file that looks something like this:

```
ODLConfiguration.config1.Servers=MS1,MS2,MS3,MS4
```

**Comment by brieucolivier** [comment]
Hello,
I completely understand your point and how you want to handle it.
 
Unfortunately, in our case, the number of dynamic server is not "hardcoded" in the image (model in image). This number is set as a environment variable to be able to "tune" our image easily without rebuilding the image. 
 
In this case, it means that we don't know in advance the size of the cluster. 
 
Regarding the property ODLConfiguration.config1.Servers, we cannot hardcode the name of the servers as we don't know the number of managed server. 
 
We propose to be able to put a regex (or another mechanism) to include a set of managed servers (In this case it can be MS*) or all managed servers of a Cluster.

**Comment by robertpatrick** [comment]
So use a second environment variable to specify the list of server names?

In your proposal, what exactly would this regex do?  You do realize that these server names are used to create directories where a logging XML file is written, right?  These directory names must match the managed server names or the software will ignore them.

Regardless of who implements this, they have to dynamically determine the list of server names in order for this to work.  I’m not feeling like there is a compelling need for WDT to do this.

**Comment by brieucolivier** [comment]
> So use a second environment variable to specify the list of server names?

Yes indeed, we can do that. Sorry, I did not think about that, but it can work for us. 
 
Thank you very much for the support.
