### ISSUE TITLE
Enable PasswordDigest configuration

### ISSUE THREAD

**Issue by gregoan** [oracle/weblogic-deploy-tooling#1531]
Hello,

We created WL domain for which one we enabled password digest configuration and this is not working.
Reading the [doc](https://docs.oracle.com/middleware/12213/wls/WLACH/taskhelp/webservices/webservicesecurity/UsePasswordDigest.html) , there is sentence about something related to username to be re-created after
---> See **After you finish** section (_you must recreate these users so that their cleartext password, and not their digest, is stored in the password database_)
---> If we reset the password using WL console so after the WL server is started, PasswordDigest is working fine.

Regards.

**Comment by robertpatrick** [comment]
@gregoan We are discussing internally with the WLS Security team to get feedback on whether there is anything that WDT can do get around this limitation.  I will update you once we have a definitive answer.

**Comment by robertpatrick** [comment]
@gregoan It seems like it might be possible to make this work but it requires testing and changes to WDT (assuming that it works).  This will not make it into WDT 4.0 but can be looked at for a future release.

**Comment by robertpatrick** [comment]
WDT 4.0.0 released so closing as resolved.
