### ISSUE TITLE
Configuring  Default servers 

### ISSUE THREAD

**Issue by hxd868** [oracle/weblogic-deploy-tooling#1537]
Though we have specified to use the Custom Server Names starting with WLS_*, Along with them WDT also creating the default servers 

How can we update WDT to not created these default servers
  <server>
    <name>osb_server1</name>
    <listen-port>7003</listen-port>
    <web-server>
      <name>osb_server1</name>
      <web-server-log>
        <name>osb_server1</name>
        <elf-fields>date time cs-method ctx-ecid ctx-rid cs-uri sc-status bytes</elf-fields>
        <log-file-format>extended</log-file-format>
      </web-server-log>
    </web-server>
    <listen-address/>
    <server-life-cycle-timeout-val>30</server-life-cycle-timeout-val>
    <startup-timeout>0</startup-timeout>
    <server-diagnostic-config>
      <name>osb_server1</name>
    </server-diagnostic-config>
    <coherence-cluster-system-resource>defaultCoherenceCluster</coherence-cluster-system-resource>
  </server>
  <server>
    <name>soa_server1</name>
    <listen-port>7004</listen-port>
    <web-server>
      <name>soa_server1</name>
      <web-server-log>
        <name>soa_server1</name>
        <elf-fields>date time cs-method ctx-ecid ctx-rid cs-uri sc-status bytes</elf-fields>
        <log-file-format>extended</log-file-format>
      </web-server-log>
    </web-server>
    <listen-address/>
    <server-life-cycle-timeout-val>30</server-life-cycle-timeout-val>
    <startup-timeout>0</startup-timeout>
    <server-diagnostic-config>
      <name>soa_server1</name>
    </server-diagnostic-config>

**Comment by robertpatrick** [comment]
@hxd868 The servers are defines in the soa/osb domain extension templates (i.e., if you wrote your own WLST scripts to create the domain, you would also see these servers created) so the only thing you can do is tell WDT to delete them by doing something like this in your model file:

```
topology:
    Server:
        '!osb_server1':
        '!soa_server1':
        WLS_osb1:
            ...
        WLS_soa1:
            ...
```
