### ISSUE TITLE
Add console summary report to create, deploy and update tools.

### ISSUE THREAD

**Issue by CarolynRountree** [oracle/weblogic-deploy-tooling#154]
This requires changing the cmd and shell scripts logging properties. See discover cmd and shell scripts. 

Ensure the quality of the warning and severe messages in the summary report.

**Comment by CarolynRountree** [comment]
Here is an example of message quality that needs to be improved in create: These are written to the console. The first two probably should not show up in the console (log at fine), the last has no context about what MBean that attribute is from .
####<Sep 6, 2018 3:44:17 PM> <SEVERE> <CommandExceptionHandler> <handleException> <> <Error: cd() failed.>
####<Sep 6, 2018 3:44:17 PM> <SEVERE> <CommandExceptionHandler> <handleException> <> <Error: set() failed.>
####<Sep 6, 2018 3:44:18 PM> <SEVERE> <create> <main> <WLSDPLY-12409> <createDomain failed to create the domain: Failed to set attribute EnableGroupMembershipLookupHierarchyCaching to value true: wlst.set(EnableGroupMembershipLookupHierarchyCaching, true) in offline mode failed : Unable to convert argument to type java.lang.Class

**Comment by rakillen** [comment]
This is done for create .sh and .cmd with #292

**Comment by rakillen** [comment]
Converted to internal Jira WDT-269
