### ISSUE TITLE
SecurityConfiguration create in offline will not take short name

### ISSUE THREAD

**Issue by CarolynRountree** [oracle/weblogic-deploy-tooling#158]
The offline create(name, type, provider) usually will take a shortened version of the class name for type. The aliases are set up to only allow a short type.  OracleUnifiedDirectoryAuthenticator and VirtualUserAuthenticator that will not take a shortened name in offline. create and deploy are broken if the alias definition is NOT set to long name for offline wlst_type. However, a lookup of the wlst_type when the alias definition IS set to the long name fails. 

Need to come up with an appropriate strategy. 

FYI, create always succeeds in both online and offline with the full class name.

**Comment by rakillen** [comment]
Converted to Jira WDT-282
