### ISSUE TITLE
Compatibility with Oracle CPU Oct 2024

### ISSUE THREAD

**Issue by veijov** [oracle/weblogic-deploy-tooling#1587]
Weblogic logs contains exceptions while deploying
- Error on connection: 'weblogic.rjvm.t3.MuxableSocketT3$T3MsgAbbrevJVMConnection@541b0a8a' java.io.EOFException
- java.rmi.ConnectException: PeerGone thrown while in non-connected state
- java.rmi.ConnectException: Attempt to sendMsg using a closed connection
Despite the errors, the deployment is successful.

**Comment by ddsharpe** [comment]
Sorry, but I do not understand what you are doing.  Please describe the environment, and the workflow that you are trying to do.

**Comment by veijov** [comment]
We are deploying our applications using the following command: `java weblogic.Deployer -deploy -adminurl t3 -adminurl t3://localhost:7001...`
During deployment several errors are logged in the WLS log, the causes of which I have listed above. Before the CPU, there were no such errors.

**Comment by ddsharpe** [comment]
`WebLogic Deploy Tooling` and `weblogic.Deployer` are not the same tool.  `weblogic.Deployer` is part of the Oracle WebLogic distribution.  If there is an issue with the October CPU or that tool, you need to file an SR with Oracle Support.

WebLogic Deploy Tooling (this project) is an open source set of tools that is installed separately from the Oracle Home and contains shell commands like createDomain, discoverDomain, etc.  See https://github.com/oracle/weblogic-deploy-tooling/tree/main/installer/src/main/bin
