### ISSUE TITLE
Deprecate subfolders that are incorrectly named

### ISSUE THREAD

**Issue by CarolynRountree** [oracle/weblogic-deploy-tooling#162]
Create a deprecate type for subfolders that are using the reference mbean instead of the containment mbean. Discover will use the new subfolders, deploy, etc will allow backward compatibility.

1. best way to correct the system tests
2. Using the correct subfolder will ensure the attributes under the subfolder.

**Comment by rakillen** [comment]
Converted to Jira WDT-283
