### ISSUE TITLE
WebLogic 19c support 

### ISSUE THREAD

**Issue by ddsharpe** [oracle/weblogic-deploy-tooling#163]
WDT needs to support WebLogic 19c

**Comment by CarolynRountree** [comment]
These are new folders in 19. We have not implemented all folders in previous versions, but will check to see if these folders are on a critical path.

top level 

EJBContainer
JMSConnectionConsumers
MigratableRMIServices

JMS 

Template/TopicSubscriptionParams
Topic/TopicSubscriptionParams
UniformDistributedTopic/TopicSubscriptionParams

**Comment by ddsharpe** [comment]
fixed by CER
