### ISSUE TITLE
Add model samples for special domain types

### ISSUE THREAD

**Issue by CarolynRountree** [oracle/weblogic-deploy-tooling#167]

**Comment by rakillen** [comment]
Converted to Jira WDT-285

**Comment by piyushwadhwani** [comment]
Does this help?

{
"name": "APP",
"description": "APP type domain definitions with wls 12.2.1.3",
"versions": {
"12.2.1.3": "APP_12213"
},
"definitions": {
"APP_12213": {
"baseTemplate": "Basic WebLogic Server Domain",
"extensionTemplates": [
"Oracle JRF",
"Oracle Enterprise Manager",
"Oracle JRF SOAP/JMS Web Services"
],
"serverGroupsToTarget": [ "JRF-MAN-SVR" ],
"rcuSchemas": [ "STB", "WLS", "MDS", "IAU", "IAU_VIEWER", "IAU_APPEND", "OPSS" ]
}
}
}
