### ISSUE TITLE
Alias definition folder entry should be an array

### ISSUE THREAD

**Issue by CarolynRountree** [oracle/weblogic-deploy-tooling#168]
We have added both the version and the mode to the folder level. But if the name of the folder differs between versions, then we have a problem. Since the folder entry is not an array, you can only have one version range and one wlst_type.

The SAFAgent JmssafMessageLogFile Mbean cannot be discovered or created (this is a singleton which, in online, is automatically created when the agent is created) in offline mode until version 12.2.1.

We need to have a mechanism to spread the folder level values other than attribute across versions, while maintaining the 12.2.1.3 offline value name standard.
FYI, I have not tested to see what would happen if a model contained this folder and deploy/update was performed in offline mode. This should be tested.

**Comment by rakillen** [comment]
Converted to Jira WDT-*286
