### ISSUE TITLE
Improve usage documentation for stand-alone validate

### ISSUE THREAD

**Issue by CarolynRountree** [oracle/weblogic-deploy-tooling#182]
The cmd and sh script usage explanation of the -print_usage parameter needs improvement. By combining the -print_usage and its corresponding sub_parameters, I thought the context was one of those parameters. It needs to discuss what the context parameter (separately from the subparameters) and the format of the context, i.e. topology:/Server. The README.md does successfully describe the -print_usage context, but does not talk about its corresponding parameters  at all.

**Comment by rakillen** [comment]
Converted to Jira WDT-291
