### ISSUE TITLE
Online discover needs to discover the application and library source path

### ISSUE THREAD

**Issue by CarolynRountree** [oracle/weblogic-deploy-tooling#183]
The source path attribute in Library and Application is readonly in online and readwrite in offline. You cannot deploy an application or library without the sourcepath because of code in the applications_deployer python file - will add a comment with that snippet of code. We need to modify the code since you cannot set this value in online mode.

It might be a good idea to discover this value into the model when running discover in online mode. We need to add an access type to the alias definitions that states the value is readonly but discover it. This is not the only attribute that faces this particular problem. something like "access": "${:ROD}"

This access type is not useful for create/update/deploy because those tools need to follow the WLST attribute access type.

**Comment by CarolynRountree** [comment]
FYI, one off checks against attributes in the code somehow need to be added to the validation tool

Here is the code in applications_deployer:

```
            shared_library = \
                copy.deepcopy(dictionary_utils.get_dictionary_element(shared_libraries, shared_library_name))
            shlib_source_path = dictionary_utils.get_element(shared_library, SOURCE_PATH)
            if string_utils.is_empty(shlib_source_path):
                ex = exception_helper.create_deploy_exception('WLSDPLY-09302', shared_library_name, SOURCE_PATH)
                self.logger.throwing(ex, class_name=self._class_name, method_name=_method_name)
                raise ex
```

**Comment by rakillen** [comment]
Converted to Jira WDT-292
