### ISSUE TITLE
Problem with folder versions in alias definitions

### ISSUE THREAD

**Issue by CarolynRountree** [oracle/weblogic-deploy-tooling#186]
When I added a folder for 19c (12.2.1.4) to the alias definitions, unit tests broke. We run unit tests with wls 12.2.1.3 (required), so we have never run into this problem before adding this new folders. We run with 12.2.1.3 offline as this is the version we use to generate the mbean and attribute model names. 

I found that the get_model_subfolder_names returns all of the existing subfolder_names in the alias definitions without applying the check for version, wlst_mode and wlst_type to the names.

**Comment by rakillen** [comment]
Converted to Jira WDT-293
