### ISSUE TITLE
Need a domain name token and other

### ISSUE THREAD

**Issue by CarolynRountree** [oracle/weblogic-deploy-tooling#187]
I see this as two different types of tokens -

1. For defaulting attributes that have name strings automatically generated by wlst (there are quite a few reference type of fields that contain a generated string name instead of a reference object. Also, there path attributes that have generated file names that contain the domain name or a reference name. We should be able to put some sort of token in the default value that tells alias don't pay attention to this part of the name when you check for default value.

2. If an attribute contains a value that will be stored in the model after the default check, we should attempt to tokenize that part of the name that is not portable to the target domain. i.e. domain name. Hopefully after doing number 1, we won't have too many other types of tokens to address.

**Comment by CarolynRountree** [comment]
Here is an example of a file with a generated file name that has the domain name:
```
/Log/FileName                                                                                                                 Attribute=logs/system_test_domain.log  : 
Alias=None
```

**Comment by rakillen** [comment]
Converted to Jira WDT-294
