### ISSUE TITLE
Default value in ResourceGroup different than in global

### ISSUE THREAD

**Issue by CarolynRountree** [oracle/weblogic-deploy-tooling#188]
ResourceGroup and ResourceGroupTemplate pulls in the WLDFSystemResource alias definition, which is also global. There is one field in the definition that has a different default value in the global versus the ResourceGroup and ResourceGroupTemplate. Pretty low in priority, but opening an issue on this. Don't know how to solve this. It would be a pain to replicate the entire json file for this one type. But hey, maybe we should

 /ResourceGroup/WLDFSystemResource/WLDFResource/WatchNotification/Watch/ExpressionLanguage                                     Attribute=EL  :  Alias=WLDF

**Comment by rakillen** [comment]
Converted to Jira WDT-295
