### ISSUE TITLE
Static deployment of non-versioned application 'appName' failed due it its manifest defines version.

### ISSUE THREAD

**Issue by dbechtel89** [oracle/weblogic-deploy-tooling#192]
i want to deploy an application with the createDomain tool. My model file has an appDeployments entry:
`"appDeployments": {
        "Application": {
            "test-app": {
                "SourcePath": "C:/test-app.war",
                "Target": "AdminServer",
                "ModuleType": "war",
                "StagingMode": "nostage",
                "PlanStagingMode": "nostage"
            }
        }
    }` 

The test-app has a manifest file with a version entry. If i start the weblogic server, i get the error message:
Static deployment of non-versioned application 'test-app' failed due it its manifest defines version.

**Comment by CarolynRountree** [comment]
Please swipe the manifest and attach to this bug along with the createDomain logs that are located in weblogic-deploy/logs

**Comment by ddsharpe** [comment]
Can the same application be deployed through the WebLogic console in other domains of the same version?  Can you attach test-app.war to this issue?

**Comment by jshum2479** [comment]
weblogic mangled the deployed application name as base_name#<specification version>@<impl version>,  this is done automatically by the weblogic console. If the app has versions in the manifest but the name is without the spec and impl version, then you will get an error when starting the server.   We will look into adding the capability of altering the name automatically if the manifest is present.  

By the way, your manifest file is without a specification version which is not legal with the implementation version specified.

**Comment by dbechtel89** [comment]
it's working now

**Comment by jdporrasc** [comment]
Cuál fue la solución?

**Comment by rakillen** [comment]
This was fixed by PR #235, back in release 0.17
