### ISSUE TITLE
Use case redeploy an app and update the deployment plan

### ISSUE THREAD

**Issue by kaifricke** [oracle/weblogic-deploy-tooling#194]
Here is what I want to achieve (in online mode):
1. Deploy a shared library (yes can be done already)
2. Redeploy a ear file and add a reference to the shared library (plan may exists already or not) 

I am not sure how I can achieve 2: 
I could of course extend the model and run a separate wlst script to change or create the plan, but then I have to connect twice.
Would it be possible to get a hook to run some wlst commands before deployment ?
Any other suggestions or thoughts ?

Best regards,
-Kai

**Comment by CarolynRountree** [comment]
you can extend the model using filters. The filters are not documented, but they are specifically used to extend the model before the deploy. However, the WLST connection has not yet been made,  which means you must open and close a connection (so 2 connections). If you are interested, I will write up notes about using filters. FYI, The redeploy strategy sounds like something we should explore.
