### ISSUE TITLE
 <SEVERE> <discover> <main> <WLSDPLY-06011> <discoverDomain failed to discover domain 

### ISSUE THREAD

**Issue by LiquidKoala** [oracle/weblogic-deploy-tooling#203]
Error on run is:

Cannot parse config-groups.xml in /space/sw/oracle/products/wls/10.3/user_projects/domains/WLS_PNET/init-info/config-groups.xml : Attribute not allowed (no wildcards allowed): topology-profile in element config-groups@http://xmlns.oracle.com/weblogic/config-groups at <xml-fragment topology-profile="Expanded"/>>
discoverDomain.sh failed (exit code = 2)

Full run:

oracle@vs-tapp040:/sw/oracle/products/wls/weblogic-deploy/bin$ ./discoverDomain.sh -oracle_home /sw/oracle/products/wls/10.3  -domain_home /sw/oracle/products/wls/10.3/user_projects/domains/WLS_PNET -archive_file Test_Discoveredvs-tapp040Domain.zip -model_file Test_Discoveredvs-tapp040Domain.yaml
JDK version is 1.8.0_77-b03
Domain type  not recognized by shell script...assuming JRF is required
JAVA_HOME = /sw/oracle/products/java
WLST_EXT_CLASSPATH =
CLASSPATH = /sw/oracle/products/wls/weblogic-deploy/lib/weblogic-deploy-core.jar
WLST_PROPERTIES = -Djava.util.logging.config.class=oracle.weblogic.deploy.logging.WLSDeployCustomizeLoggingConfig -Dcom.oracle.cie.script.throwException=true
/sw/oracle/products/wls/10.3/wlserver_10.3/common/bin/wlst.sh /sw/oracle/products/wls/weblogic-deploy/lib/python/discover.py -oracle_home /sw/oracle/products/wls/10.3 -domain_home /sw/oracle/products/wls/10.3/user_projects/domains/WLS_PNET -archive_file Test_Discoveredvs-tapp040Domain.zip -model_file Test_Discoveredvs-tapp040Domain.yaml
 
CLASSPATH=/sw/oracle/products/wls/10.3/patch_wls1036/profiles/default/sys_manifest_classpath/weblogic_patch.jar:/sw/oracle/products/wls/10.3/patch_ocp371/profiles/default/sys_manifest_classpath/weblogic_patch.jar:/space/sw/oracle/products/jdk_1.7.0_80/lib/tools.jar:/space/sw/oracle/products/wls/10.3/wlserver_10.3/server/lib/weblogic_sp.jar:/space/sw/oracle/products/wls/10.3/wlserver_10.3/server/lib/weblogic.jar:/sw/oracle/products/wls/10.3/modules/features/weblogic.server.modules_10.3.6.0.jar:/space/sw/oracle/products/wls/10.3/wlserver_10.3/server/lib/webservices.jar:/sw/oracle/products/wls/10.3/modules/org.apache.ant_1.7.1/lib/ant-all.jar:/sw/oracle/products/wls/10.3/modules/net.sf.antcontrib_1.1.0.0_1-0b2/lib/ant-contrib.jar:/sw/oracle/products/wls/weblogic-deploy/lib/weblogic-deploy-core.jar:/sw/oracle/products/wls/10.3/utils/config/10.3/config-launch.jar::/space/sw/oracle/products/wls/10.3/wlserver_10.3/common/derby/lib/derbynet.jar:/space/sw/oracle/products/wls/10.3/wlserver_10.3/common/derby/lib/derbyclient.jar:/space/sw/oracle/products/wls/10.3/wlserver_10.3/common/derby/lib/derbytools.jar::
 
Initializing WebLogic Scripting Tool (WLST) ...
 
Welcome to WebLogic Server Administration Scripting Shell
 
Type help() for help on available commands

**Comment by CarolynRountree** [comment]
This message is returned by WLST. Could you please attach the discoverDomain.log from <install>/weblogic-deploy/logs and the config-groups.xml from your domain location.

**Comment by ddsharpe** [comment]
I am going to close this issue due to lack of response.  If needed, please re-open and provide more details about the domain that you were trying to discover, such as the templates that were used to create it, or zip up the domain and attach it.

**Comment by LiquidKoala** [comment]
Attached discoverDomain.log from /weblogic-deploy/logs and the config-groups.xml domain. 

[discoverDomain.log](https://github.com/oracle/weblogic-deploy-tooling/files/2853500/discoverDomain.log)


[config-groups.txt](https://github.com/oracle/weblogic-deploy-tooling/files/2853509/config-groups.txt)

I can check on zipping up the domain.

**Comment by LiquidKoala** [comment]
Attached are discoverDomain.log and config-groups.xml. 
I will check if the domain zip is available. 

[config-groups.txt](https://github.com/oracle/weblogic-deploy-tooling/files/2853580/config-groups.txt)
[discoverDomain.log](https://github.com/oracle/weblogic-deploy-tooling/files/2853581/discoverDomain.log)
