### ISSUE TITLE
Example of model to deploy data-source incorrectly adds slash characters causing deployment failure with Oracle DB

### ISSUE THREAD

**Issue by ankedia** [oracle/weblogic-deploy-tooling#209]
The = example of 
I have created a data-source that points to a Oracle DB using example provided here =>
https://github.com/oracle/weblogic-deploy-tooling

The URL format in model yaml is this => 
URL: 'jdbc:oracle:thin:@//@@PROP:dbcs1.url@@'

This doesn't work with Oracle since it has extra slash character. I get below exceptions during data-source deployment due to slash characters. 

The example should remove "/" characters for Oracle DB.

<Jan 7, 2019 10:22:02,249 PM UTC> <Error> <Deployer> <BEA-149205> <Failed to initialize the application "dellPool" due to error weblogic.application.ModuleException: weblogic.common.resourcepool.ResourceSystemException: Invalid port number for URL jdbc:oracle:thin:@//burbe23.us.oracle.com:1521:stressB for datasource 'dellPool'
weblogic.application.ModuleException: weblogic.common.resourcepool.ResourceSystemException: Invalid port number for URL jdbc:oracle:thin:@//burbe23.us.oracle.com:1521:stressB for datasource 'dellPool'
       at weblogic.jdbc.module.JDBCModule.prepare(JDBCModule.java:408)
...
Caused By: weblogic.common.resourcepool.ResourceSystemException: Invalid port number for URL jdbc:oracle:thin:@//burbe23.us.oracle.com:1521:stressB for datasource 'dellPool'
       at weblogic.jdbc.common.internal.JDBCUtil.parseException(JDBCUtil.java:332)
       at weblogic.jdbc.common.internal.ConnectionEnvFactory.makeConnection0(ConnectionEnvFactory.java:354)

**Comment by jshum2479** [comment]
There are two ways to setup oracle jdbc url 

jdbc:oracle:thin:@[HOST][:PORT]:SID

For service name type URL format, it is:

jdbc:oracle:thin:@//[HOST][:PORT]/SERVICE

So if you start with // then it is treated as service type and you have a colon  then it is an invalid format.
