### ISSUE TITLE
Server Start Arguments. Server cannot start

### ISSUE THREAD

**Issue by antonionappi88** [oracle/weblogic-deploy-tooling#210]
Hello,
I'm trying to generate a domain from a yaml file. I have a problem with this part of the YAML : 

```
ServerStart":
        "Arguments": "-Djava.security.egd=file:/dev/./urandom -Dweblogic.data.canTransferAnyFile=true -Dweblogic.servlet.useExtendedSessionFormat=true -Dweblogic.security.SSL.protocolVersion=TLS1 -Djdk.tls.client.protocols=TLSv1,TLSv1.1,TLSv1.2"
```
When I create the domain from this, it gives me back a config.xml with : 
```
 <arguments>-DANTLR_USE_DIRECT_CLASS_LOADING=true -Djava.awt.headless=true -Dhttp.webdir.enable=false -Duser.timezone=Europe/Zurich -Djava.net.preferIPv4Stack=true -Djava.security.egd=file:/dev/./urandom -Dweblogic.data.canTransferAnyFile=true -Djdk.tls.client.protocols=TLSv1 TLSv1.1 TLSv1.2</arguments> 
```
Basically it removes the commas from `TLSv1,TLSv1.1,TLSv1.2`  and the server cannot be started.

P.s. I tried also to put the `TLSv1,TLSv1.1,TLSv1.2` between single or double quotes but it doesn't change anything. ( also to add a backslash in front of the commas, but nothing).

Do you know if there is a way to achieve what I need ?
Thank you in advance!

Cheers,
Antonio

**Comment by rakillen** [comment]
Hey Antonio,
I think there is a better fix for this, but I was able to work around it by using this syntax in the YAML file:

            ServerStart:
                Arguments: [
                    "-Djava.security.egd=file:/dev/./urandom",
                    "-Dweblogic.data.canTransferAnyFile=true",
                    "-Dweblogic.servlet.useExtendedSessionFormat=true",
                    "-Dweblogic.security.SSL.protocolVersion=TLS1",
                    "-Djdk.tls.client.protocols=TLSv1,TLSv1.1,TLSv1.2"
                ]

This gave me the correct result in config.xml, with commas intact.
Richard

**Comment by antonionappi88** [comment]
Hello Richard,
it worked. Thanks a lot!

Cheers,
Antonio
