### ISSUE TITLE
SingleSignOnServices in WLS < 12.2.1.3

### ISSUE THREAD

**Issue by antonionappi88** [oracle/weblogic-deploy-tooling#214]
Hello,
In this [issue](https://github.com/oracle/weblogic-deploy-tooling/issues/97) was mentioned that the SingleSignOnServices was not possible to configure for WLS versions lower than 12.2.1.3. 
The problem is still there, do you think that there will a be a fix or I should find a work around ? 

Thank you.
Cheers,
Antonio

**Comment by ddsharpe** [comment]
This is a WLST bug that was fixed in 12.2.1.  The fix for WLST in WebLogic Server is filed under bug 29223183.  The bug backport for 12.1.3 is bug 29266063.
