### ISSUE TITLE
Can't have blank lines in model yaml files

### ISSUE THREAD

**Issue by moreaut** [oracle/weblogic-deploy-tooling#236]
I tried to add a copyright to a model yaml file followed by a blank line, i.e.:
```
# Copyright 2019, Oracle Corporation and/or its affiliates.  All rights reserved.
# Licensed under the Universal Permissive License v 1.0 as shown at http://oss.oracle.com/licenses/upl.

domainInfo:
...
```

And I got this error when I tried to build the model:

```
####<Jan 31, 2019 2:10:37 PM> <SEVERE> <ParsingErrorListener> <syntaxError> <WLSDPLY-18018> <Parse error for file /u01/oracle/docker-build-tmp/model.yaml at line 4 position 0: mismatched input '\n' expecting {<EOF>, NAME, LIST_ITEM_OP}>
####<Jan 31, 2019 2:10:37 PM> <SEVERE> <create> <main> <WLSDPLY-20009> <createDomain failed to load the model file /u01/oracle/docker-build-tmp/model.yaml: Unable to parse model from file /u01/oracle/docker-build-tmp/model.yaml : The YAML parser encountered 1 error(s) while parsing /u01/oracle/docker-build-tmp/model.yaml>

createDomain.sh failed (exit code = 2)
```

Then I changed the blank line to start with #, then it successfully created my domain:
```
# Copyright 2019, Oracle Corporation and/or its affiliates.  All rights reserved.
# Licensed under the Universal Permissive License v 1.0 as shown at http://oss.oracle.com/licenses/upl.
#
domainInfo:
...
```

I'm using version 0.14

Note: Kubernetes yaml files support blank lines (i.e. kubectl apply -f accepts yaml files with blank lines)

**Comment by kaifricke** [comment]
Hello,
I did a quick test with the Antlr grammar tester and Yaml.g4:

java org.antlr.v4.gui.TestRig Yaml file -gui --diagnostics
# Comment
Name:
    Name1: Oracle
Works fine, if no empty line between comment and statement
java org.antlr.v4.gui.TestRig Yaml file -gui --diagnostics
# Comment
<Empty line here >
Name:
    Name1: Oracle
With an empty line, I get the error line 3:0 mismatched input '\r\n' expecting {<EOF>, NAME, LIST_ITEM_OP} as you get.

So the grammar implementation does not support this currently. The question is if that is actually supported by the YAML Spec.

-Kai

**Comment by CarolynRountree** [comment]
Kai, thanks for the input.
