### ISSUE TITLE
DeployApps python error

### ISSUE THREAD

**Issue by cchaplin** [oracle/weblogic-deploy-tooling#242]
When I try to deploy an application (EAR file) in online mode using deployApps.sh I get below python error.
```
Initializing WebLogic Scripting Tool (WLST) ...

Welcome to WebLogic Server Administration Scripting Shell

Type help() for help on available commands

Problem invoking WLST - Traceback (innermost last):
  File "/apps/middleware/Naveen/weblogic-deploy/lib/python/deploy.py", line 29, in ?
ImportError: no module named aliases


deployApps.sh completed but with some issues (exit code = 1)
bash-3.2$
```
But I can very much find aliases module inside weblogic-deploy. I'm using 0.17 version of the release zip file. 

**Weblogic version: 10.3.5**
Java version used for tooling: 1.7.0_80-b15
Command used:
`weblogic-deploy/bin/deployApps.sh -oracle_home /apps/middleware/products/Oracle/weblogic/WLS10_3_5 -domain_type WLS -domain_home /apps/data/domains/cr_domain -archive_file app.zip -model_file app_model.yml -admin_url t3://localhost:7001 -admin_user weblogic`

**Comment by jshum2479** [comment]
Have you put any special jar in the $domain/lib or classpath of the domain ?

**Comment by cchaplin** [comment]
There are no special jars in <domain>/lib. I even tried with Weblogic 10.3.6 with java 1.7 i get the same error. Classpath set by weblogic deploy tooling script

> JDK version is 1.7.0_80-b15
> JAVA_HOME = /apps/middleware/products/Oracle/jrockit/jdk1.7.0_80
> WLST_EXT_CLASSPATH =
> CLASSPATH = /apps/middleware/tools/weblogic-deploy/lib/weblogic-deploy-core.jar
> WLST_PROPERTIES = -Djava.util.logging.config.class=oracle.weblogic.deploy.logging.WLSDeployLoggingConfig -Dcom.oracle.cie.script.throwException=true
> /apps/middleware/products/Oracle/weblogic/WLS10_3_6/wlserver_10.3/common/bin/wlst.sh /apps/middleware/tools/weblogic-deploy/lib/python/deploy.py -oracle_home /apps/middleware/products/Oracle/weblogic/WLS10_3_6 -domain_type WLS -domain_home /apps/ee/5/wsoa/APC_05 -archive_file apc_payments.zip -model_file apc_payments.yml -admin_url t3://localhost:7001 -admin_user web logic
>  
> CLASSPATH=/apps/middleware/products/Oracle/weblogic/WLS10_3_6/patch_wls1036/profiles/default/sys_manifest_classpath/weblogic_patch.jar:/apps/middleware/products/Oracle/weblogic/WLS10_3_6/patch_ocp371/profiles/default/sys_manifest_classpath/weblogic_patch.jar:/apps/middleware/products/Oracle/jrockit/jdk1.7.0_80/lib/tools.jar:/apps/middleware/products/Oracle/weblogic/WLS10_3_6/wlserver_10.3/server/lib/weblogic_sp.jar:/apps/middleware/products/Oracle/weblogic/WLS10_3_6/wlserver_10.3/server/lib/weblogic.jar:/apps/middleware/products/Oracle/weblogic/WLS10_3_6/modules/features/weblogic.server.modules_10.3.6.0.jar:/apps/middleware/products/Oracle/weblogic/WLS10_3_6/wlserver_10.3/server/lib/webservices.jar:/apps/middleware/products/Oracle/weblogic/WLS10_3_6/modules/org.apache.ant_1.7.1/lib/ant-all.jar:/apps/middleware/products/Oracle/weblogic/WLS10_3_6/modules/net.sf.antcontrib_1.1.0.0_1-0b2/lib/ant-contrib.jar:/apps/middleware/tools/weblogic-deploy/lib/weblogic-deploy-core.jar:/apps/middleware/products/Oracle/weblogic/WLS10_3_6/wlserver_10.3/common/derby/lib/derbyclient.jar:/apps/middleware/products/Oracle/weblogic/WLS10_3_6/wlserver_10.3/server/lib/xqrl.jar:/apps/middleware/products/Oracle/weblogic/WLS10_3_6/utils/config/10.3/config-launch.jar::/apps/middleware/products/Oracle/weblogic/WLS10_3_6/wlserver_10.3/common/derby/lib/derbynet.jar:/apps/middleware/products/Oracle/weblogic/WLS10_3_6/wlserver_10.3/common/derby/lib/derbyclient.jar:/apps/middleware/products/Oracle/weblogic/WLS10_3_6/wlserver_10.3/common/derby/lib/derbytools.jar::

**Comment by cchaplin** [comment]
I'm getting python error with discover domain too. 

> Initializing WebLogic Scripting Tool (WLST) ...
> 
> Welcome to WebLogic Server Administration Scripting Shell
> 
> Type help() for help on available commands
> 
> Problem invoking WLST - Traceback (innermost last):
>   File "/apps/middleware/tools/weblogic-deploy/lib/python/discover.py", line 29, in ?
> ImportError: no module named aliases
> 
> 
> discoverDomain.sh completed but with some issues (exit code = 1)

which is similar to error got trying to deploy (above)..  What could be causing  this. I can see that aliases present. Any ideas, suggestions appreciated. I was trying to discover a weblogic 10.3.5 domain but by setting oracle_home to weblogic 10.3.6 install (because our 10.3.5 weblogic is using JDK 1.6). But then even when I try to discover a 10.3.6 domain i get the same error.

**Comment by rakillen** [comment]
I suspect the Python search path is finding another **wlsdeploy** directory somewhere on the search path, and the error occurred when it did not contain an **aliases** sub-directory.  Another possibility is that the **<WDT install>/lib/python directory** is not correctly appended to the search path.

The search path for Python classes does not correspond exactly to the CLASSPATH variable, but is created internal to WLST.  The value can be accessed in Python code as **sys.path**.

You can print the sys.path variable in the top-level Python file (discover.py or deploy.py), after the sys.path.append() command, such as:

sys.path.append(os.path.dirname(os.path.realpath(sys.argv[0])))
**print("PATH: " + str(sys.path))
print("CWD: " + str(os.getcwd()))**

The path references ".", so it is good to know the working directory.  It also contains "__classpath__", which you already have above.

Verify that the <WDT install>/lib/python is the last entry in that path.

Verify that there is not a wlsdeploy directory under any of the entries in that path.  

Hope this helps.

**Comment by rakillen** [comment]
Another user had inadvertently created this scenario by running the tool from the directory where he had constructed his archive zip.  Because the root directory of the zip structure is named **wlsdeploy**, and the parent directory was his working directory when he ran the tool, Python was finding that **wlsdeploy** directory first in the path search, instead of the one in **[WDT install]/lib/python**.

**Comment by cchaplin** [comment]
I was wondering why i get this Python error sporadically. I'm having the same issue as the other user reported. I had wlsdeploy directory(from the zip structure) in the current working directory from where i execute the deployApps.sh

After removing the wlsdeploy directory, the python error "ImportError: no module named aliases" is gone now. Thanks very much for your support.

**Comment by CarolynRountree** [comment]
That is interesting! Thank you for the information.
