### ISSUE TITLE
createDomain.sh script error in ubuntu

### ISSUE THREAD

**Issue by gosurya-oracle** [oracle/weblogic-deploy-tooling#246]
While trying to create a domain using WDT on ubuntu (using docker image), I noticed the following script errors 

/u01/app/weblogic-deploy/bin/createDomain.sh: 161: /u01/app/weblogic-deploy/bin/createDomain.sh: [[: not found
/u01/app/weblogic-deploy/bin/createDomain.sh: 172: /u01/app/weblogic-deploy/bin/createDomain.sh: cannot create 1: Permission denied
/u01/app/weblogic-deploy/bin/createDomain.sh: 172: /u01/app/weblogic-deploy/bin/createDomain.sh: [[: not found

I think this has to do with the shebang line at the top says #!/bin/sh which may or may not be a bash shell. The code is using bash syntax.

**Comment by jshum2479** [comment]
All the shell script needs to be changed to support ubuntu bash

**Comment by xirona** [comment]
Confirmed changing the first line to #!/bin/bash fixes the issue for Ubuntu.
