### ISSUE TITLE
Java incompatibility issue with weblogic 10.3.5

### ISSUE THREAD

**Issue by cchaplin** [oracle/weblogic-deploy-tooling#247]
We have a weblogic 10.3.5 setup using JRockit 1.6 JVM. Even though i set JAVA_HOME to point to JDK1.7 and run the weblogic deploy tooling scripts (discoverDomain or createDomain), I get Java incompatibility error. 

I tried to set my JAVA_HOME to JDK 7 
JDK version is 1.7.0_80-b15
JAVA_HOME = /apps/middleware/products/Oracle/jrockit/jdk1.7.0_80

and run the deployApps.sh but I get java incompatibility issue

> Exception in thread "Main Thread" java.lang.UnsupportedClassVersionError: oracle/weblogic/deploy/logging/WLSDeployLoggingConfig : unsupported classversion 51.0
>         at java.lang.ClassLoader.defineClass1(Native Method)
>         at java.lang.ClassLoader.defineClassCond(ClassLoader.java:631)
>         at java.lang.ClassLoader.defineClass(ClassLoader.java:615)
>         at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:141)
>         at java.net.URLClassLoader.defineClass(URLClassLoader.java:283)
>         at java.net.URLClassLoader.access$000(URLClassLoader.java:58)
>         at java.net.URLClassLoader$1.run(URLClassLoader.java:197)
>         at java.net.URLClassLoader.findClass(URLClassLoader.java:190)
>         at java.lang.ClassLoader.loadClass(ClassLoader.java:306)
>         at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
>         at java.lang.ClassLoader.loadClass(ClassLoader.java:247)
>         at java.util.logging.LogManager.readConfiguration(LogManager.java:741)
>         at java.util.logging.LogManager$2.run(LogManager.java:267)
>         at java.util.logging.LogManager.readPrimordialConfiguration(LogManager.java:265)
>         at java.util.logging.LogManager.getLogManager(LogManager.java:248)
>         at java.util.logging.Logger.<init>(Logger.java:225)
>         at java.util.logging.LogManager$RootLogger.<init>(LogManager.java:1092)
>         at java.util.logging.LogManager$RootLogger.<init>(LogManager.java:1089)
>         at java.util.logging.LogManager$1.run(LogManager.java:180)
>         at java.util.logging.LogManager.<clinit>(LogManager.java:157)
>         at java.util.logging.Logger.getAnonymousLogger(Logger.java:392)
>         at java.util.logging.Logger.getAnonymousLogger(Logger.java:365)
>         at weblogic.diagnostics.debug.DebugLoggerRepository.createAndInitAnonymousLogger(DebugLoggerRepository.java:92)
>         at weblogic.diagnostics.debug.DebugLoggerRepository.<init>(DebugLoggerRepository.java:33)
>         at weblogic.diagnostics.debug.DebugLogger.<clinit>(DebugLogger.java:46)
>         at weblogic.descriptor.DescriptorClassLoader.<clinit>(DescriptorClassLoader.java:26)
>         at weblogic.WLST.main(WLST.java:19)
> Exception in thread "Thread-0" java.lang.NoClassDefFoundError: java/util/logging/LogManager
>         at java.util.logging.LogManager$Cleaner.run(LogManager.java:211)
> 
> deployApps.sh completed but with some issues (exit code = 1)

Even though I set JAVA_HOME to 1.7 and PATH to to $JAVA_HOME/bin after running the deployApps.sh it points to default Java in the weblogic domain (which is java 1.6).. The PATH variable value displayed by deployApps.sh

> PATH=/apps/middleware/products/Oracle/weblogic/WLS10_3_5/wlserver_10.3/server/bin:/apps/middleware/products/Oracle/weblogic/WLS10_3_5/modules/org.apache.ant_1.7.1/bin:/apps/middleware/products/Oracle/jrockit/jrockit-jdk1.6.0_29-R28.2.2-4.1.0/jre/bin:/apps/middleware/products/Oracle/jrockit/jrockit-jdk1.6.0_29-R28.2.2-4.1.0/bin:/apps/middleware/products/Oracle/jrockit/jdk1.7.0_80/bin:/usr/kerberos/bin:/usr/local/bin:/bin:/usr/bin:/apps/middleware/products/Oracle/jrockit/jrockit-jdk1.6.0_29-R28.2.2-4.1.0/bin

_Originally posted by @cchaplin in https://github.com/oracle/weblogic-deploy-tooling/issues/240#issuecomment-462859551_

**Comment by jshum2479** [comment]
The weblogic deploy tool requires jdk 7 and above.   

Exception in thread "Main Thread" java.lang.UnsupportedClassVersionError: oracle/weblogic/deploy/logging/WLSDeployLoggingConfig : unsupported classversion 51.0

The deployApps.sh  (or any weblogic deploy script launches the wlst.sh from the middleware installation), even you by passed the script check to use JDK 7,  it won't help because the wlst.sh is going to use the JDK version when you installed weblogic and in your case it is jrockit 6.  

Our code and maven plugin requires JDK7, so that's why you see the classversion incompatibility error.  
I believe 10.3.5 only supports jdk 6 whereas 10.3.6 supports jdk 7.

**Comment by cchaplin** [comment]
Ok. We have lots of applications (around 100 webservices spread in multiple domains) running on weblogic 10.3.5. We are moving those to 10.3.6. I was planning to use discoverDomain to capture the domain details and use it to create domains on 10.3.6 environment.  Any suggestions please?

**Comment by ddsharpe** [comment]
@cchaplin I am able to discover 10.3.5 domains by using an Oracle Home with 10.3.6.  The downside is that you will need the 10.3.6 OH binaries installed on the machine where you want to run discover.

Like:
./discoverDomain.sh -oracle_home /middleware/wls1036 -domain_home /middleware/wls1035/user_projects/domains/base_domain -archive_file ./test.zip -model_file test.yaml

**Comment by cchaplin** [comment]
That is interesting. I guess, that is my only option. Cannot install WLS 10.3.6 on production. 

 I wish online  discover mode was possible (just like deploy application mode).

**Comment by jshum2479** [comment]
Another option is to zip up the domain directory from production and unzip it to the same location on another machine that you can install 10.3.6/JDK7 as long as your security team is ok with it.
