### ISSUE TITLE
Do we have dry run mode(like check mode in ansible) in this tool?

### ISSUE THREAD

**Issue by yoursmanish** [oracle/weblogic-deploy-tooling#252]
Do we have dry run mode(like check mode in ansible) in this tool? 
in which doesn't apply changes but compare with live environment and reports the changes which will be made.

**Comment by ddsharpe** [comment]
Not at this time, but I will add this to the improvements list.

**Comment by robertpatrick** [comment]
Workaround is to use `discoverDomain `and then `compareModel` to compare your model with the existing domain.  Closing for now,
