### ISSUE TITLE
Invalid or missing credentials configuration

### ISSUE THREAD

**Issue by staylorx** [oracle/weblogic-deploy-tooling#262]
When installing the Oracle Identity Manager (OIM), I get all the way through the create, but run into a credentials problem. In the config.sh UI there is a step between "JDBC Test" and "Keystore" called "Credentials". How would one enter these using a model and/or typedef? We see the same issue for the same reasons when attempting to install ODI.

In OIM, these username-password pairs are under the "oim" store with the following keys:
- keystore
- OIMSchemaPassword
- sysadmin
- WeblogicAdminKey

```
####<Feb 26, 2019 3:26:07 PM> <INFO> <DomainCreator> <__create_domain_with_select_template> > <WLSDPLY-12206> <Closing templates for domain oim_domain>
com.oracle.cie.domain.script.ScriptException: 60456: Invalid or missing credentials configuration.
60456: The credentials configuration in your domain is invalid.
60456: Correct the configuration.
64014: The required property is missing.
64014: Invalid property "Username" of Credential: value "" is invalid. The property value is required.
64014: Provide property value.
...
####<Feb 26, 2019 3:26:08 PM> <SEVERE> <create> <main> <WLSDPLY-12409> <createDomain failed to create the domain: Failed to write domain to /home/oracle/oim_domain: > wlst.writeDomain(/home/oracle/oim_domain) failed : Error writing domain:
60456: Invalid or missing credentials configuration.
60456: The credentials configuration in your domain is invalid.
60456: Correct the configuration.
64014: The required property is missing.
64014: Invalid property "Username" of Credential: value "" is invalid. The property value is required.
64014: Provide property value.>
```

Aside, this is a wonderful project and has the potential to save ~~me~~ everyone tons of time. Nice job!

**Comment by jshum2479** [comment]
I am looking for some input regarding OIM.  It is possible to support OIM in WDT creation.  There are some keystore values need to be set before the domain is written to the disk and the data can be introduced in the model.   

In the OIM domain you are trying to create, do you have anything else configured differently from what's out of the box.  For example, default collocated OIM has soa_server1, oim_server1.  Do you usually change it to be clustered by adding more servers and do you any other customization or deployed apps to the domain (other than the oim policy, security data which I believe is in the database).

**Comment by staylorx** [comment]
Out if the box and on first pass I try to build the two servers and two clusters from the template. If I run the install from config.sh I get two clusters, one for each server. So I have been setting up my YAML the same way. Pretty much next-next-finish domain so far.

**Comment by jshum2479** [comment]
Thanks, what versions of OIM you are testing against ?

**Comment by staylorx** [comment]
12.2.1.3.0 as of a month ago.

**Comment by jshum2479** [comment]
Thanks,  I have an experimental branch testoim and it can create a oim domain (or soa),  discovery has not been completed yet, but you are welcome to give it a try and give me feedback - I am not familiar with oim, so I am not sure the created domain is correct and can be used. 

You can clone the project and switch to the branch

git checkout testoim
mvn -DskipTests -Denforcer.skip clean install

The wdt zip file will be under installer/target

To create an oim domain, you can

/createDomain.sh -oracle_home  <your 12213 mw home> -domain_type OIM -domain_home /tmp/simpleoim -model_file /tmp/simple-oim.yaml -run_rcu -rcu_prefix TESTOIM -rcu_db localhost:1521/pdborcl

Here's a sample model file I use:

domainInfo:
    AdminUserName: 'weblogic'
    AdminPassword: 'welcome1'
    ServerStartMode: 'prod'
    OIMCredentials:
        oim_keystore_user : 'weblogic'
        oim_keystore_password : 'welcome1'
        oim_schema_user : 'weblogic'
        oim_schema_password : 'welcome1'
        oim_sysadmin_user : 'weblogic'
        oim_sysadmin_password : 'welcome1'
        oim_weblogic_admin_user : 'weblogic'
        oim_weblogic_admin_password : 'welcome1'
    ServerGroupTargetingLimits:
           'SOA-MGD-SVRS': ['soa_server1', 'soa_server2']
           'OIM-MGD-SVRS': ['oim_server1', 'oim_server2']

topology:
    Name: simple_domain
    SecurityConfiguration:
        NodeManagerUsername : 'weblogic'
        NodeManagerPasswordEncrypted : 'welcome1'
    Cluster:
        soa_cluster:
            MulticastTTL: 1
        oim_cluster:
            MulticastTTL: 1

    Server:
        AdminServer:
            ListenAddress: myaddress
            ListenPort: 7001
            Machine : machine1
        soa_server1:
            Cluster : soa_cluster
            ListenAddress: myaddress
            ListenPort: 8001
            Machine : machine1
        soa_server2:
            Cluster : soa_cluster
            ListenAddress: myaddress
            ListenPort: 8003
            Machine : machine1
        oim_server1:
            Cluster : oim_cluster
            ListenAddress: myaddress
            ListenPort: 8101
            Machine : machine1
        oim_server2:
            Cluster : oim_cluster
            ListenAddress: myaddress
            ListenPort: 8103
            Machine : machine1
    Machine:
        machine1:
            NodeManager:
                ListenAddress: myaddress

**Comment by robertpatrick** [comment]
No response from user, closing for now
