### ISSUE TITLE
RCU extra variables

### ISSUE THREAD

**Issue by staylorx** [oracle/weblogic-deploy-tooling#263]
When using the RCU installer outside of createDomain, I sometimes run into using extra variables. SOA Suite for instance has 'SOA_PROFILE_TYPE" and "HEALTHCARE_INTEGRATION" variables. 

In RCU I add `-variables  SOA_PROFILE_TYPE=MED,HEALTHCARE_INTEGRATION=NO` after -component to add these. Possibly add an optional field in create and update domain such as "rcu_variables"?

Thanks!

**Comment by jshum2479** [comment]
This feature is actually in the new release, you can refer to the documentation here:

https://github.com/oracle/weblogic-deploy-tooling/blob/master/site/rcuinfo.md

We welcome any feedback.

**Comment by staylorx** [comment]
Wonderful. Thanks!
