### ISSUE TITLE
topology validator not splitting classpath

### ISSUE THREAD

**Issue by shanedonohoe** [oracle/weblogic-deploy-tooling#275]
I have been experiencing severe errors during the classpath checking step of the topology validation:

```WLSDPLY-05024: Attribute ClassPath in model location topology:/Server/myserver_batch1/ServerStart/SERVER_START-0 references entry wlsdeploy/classpathLibraries/javax.persistence_1.1.0.0_2-0(1).jar:wlsdeploy/classpathLibraries/com.oracle.jpa2support_1.0.0.0_21(1).jar:wlsdeploy/classpathLibraries/weblogic_patch(1).jar:wlsdeploy/classpathLibraries/weblogic(2).jar that is not found in the archive file /home/bea/bacstelip_discovered.zip```

It seems that the classpath is not being split (on colons in our case), so the full string, separators included, is being searched for as a path in the archive.

We're currently using a workaround by changing the `if`s in the original source to the `elif`s and adding a conditional to check for colons. This works for us, but is obviously specific to our case and wouldn't work as a general fix.

```python
    # lib/python/wlsdeploy/tool/validate/validator.py
    881         valid_valus_data_types = ['list', 'string']
    882         if value_data_type not in valid_valus_data_types:
    883             validation_result.add_error('WLSDPLY-05023', attribute_name, model_folder_path, value_data_type)
    884         else:
    885             attr_values = []
    886
    887             if value_data_type == 'string' and ":" in attribute_value:
    888                 attr_values = attribute_value.split(":")
    889
    890             elif value_data_type == 'string' and model_constants.MODEL_LIST_DELIMITER in attribute_value:
    891                 attr_values = attribute_value.split(model_constants.MODEL_LIST_DELIMITER)
    892
    893             elif value_data_type == 'string':
    894                 attr_values.append(attribute_value)
    895
    896             for item_path in attr_values:
    897                 validation_result = self.__validate_single_path_in_archive(item_path.strip(), attribute_name,
    898                                                                            model_folder_path, validation_result)```

**Comment by rakillen** [comment]
The Server/ServerStart/Classpath attribute is a list type, so it can be represented in the model in two ways, as a comma-delimited string, or as a list. Your entry in the model should look like:

ServerStart: 'wlsdeploy/classpathLibraries/javax.persistence_1.1.0.0_2-0(1).jar, wlsdeploy/classpathLibraries/com.oracle.jpa2support_1.0.0.0_21(1).jar, wlsdeploy/classpathLibraries/weblogic_patch(1).jar, wlsdeploy/classpathLibraries/weblogic(2).jar'

or:
ServerStart: [
    'wlsdeploy/classpathLibraries/javax.persistence_1.1.0.0_2-0(1).jar',
    'wlsdeploy/classpathLibraries/com.oracle.jpa2support_1.0.0.0_21(1).jar',
    'wlsdeploy/classpathLibraries/weblogic_patch(1).jar',
    'wlsdeploy/classpathLibraries/weblogic(2).jar'
]

The tools will use the correct delimiter when setting the value in WLST.  If any list member contains a comma, a list must be used in the model. 

There is a more detailed discussion of list values [here](https://github.com/oracle/weblogic-deploy-tooling#model-semantics).

Hope this helps.

**Comment by shanedonohoe** [comment]
Thanks Richard, but our problem is during domain discovery, we are not creating our own model file at this point.

**Comment by rakillen** [comment]
OK, I'm able to reproduce it in discover.
