### ISSUE TITLE
Undeploy application

### ISSUE THREAD

**Issue by cchaplin** [oracle/weblogic-deploy-tooling#285]
Is it possible to undeploy application using this tooling ? Say, if we deploy a new version of an application during a release. if for some reason, we have to rollback the release, can this toolig help? my ideas was to undeploy current version and redeploy old version.

**Comment by CarolynRountree** [comment]
We do not currently support this action, which seems to be something like backup original/undeploy original/redeploy new. undeploy current/restore last backup. This is an interesting idea. Will get back to you whether this is something we can support with the tool.

**Comment by cchaplin** [comment]
Does the prev-model-file option of the deployApps.sh work ? the documentation says 
```

        prev-model-file - the location of the previous model file.

                          This is used to remove apps and resources that
                          were previously deployed in addition to
                          (re)deploy the current apps and resources

```
Can this help?

**Comment by CarolynRountree** [comment]
Not yet. This planned for a future release. Leave your Issue open to help us prioritize and notify you of impending development.

**Comment by rakillen** [comment]
internal JCS JIRA JCS-10214

**Comment by jshum2479** [comment]
It is supported in 1.8.0 using the exclamation notation for app or shared lib
