### ISSUE TITLE
Global properties for web applications

### ISSUE THREAD

**Issue by dbechtel89** [oracle/weblogic-deploy-tooling#286]
We can't configure global properties (domain wide properties) for our web applications, e.g. gzip compression.

WLST command:

cd('/WebAppContainer/%DOMAIN%/GzipCompression/%DOMAIN%')
cmo.setGzipCompressionEnabled(true)
cmo.setGzipCompressionMinContentLength(2048)
set('GzipCompressionContentType',jarray.array([String('text/html
'), String('text/xml
'), String('text/plain
'), String('text/javascript')], String))

**Comment by jshum2479** [comment]
Thanks for letting us know, we will be adding support of WebAppContainer

**Comment by jshum2479** [comment]
We have added support for WebAppContainer in the resource level in the master branch, next release should include the functionality.  You can specify in the resource section of the model similar to this:

resources:
    WebAppContainer:
        WAPEnabled: 0
        FilterDispatchedRequestsEnabled: true
        AllowAllRoles: true
        XPoweredByHeaderLevel: NONE
        ServletAuthenticationFormURL: true
        ServletReloadCheckSecs: 1
        ChangeSessionIDOnAuthentication: true
        MimeMappingFile: wlsdeploy/config/amimemappings.properties
        AuthCookieEnabled: true
        WorkContextPropagationEnabled: true
        ReloginEnabled: true
        GzipCompression:
            GzipCompressionContentType: [ text/html, text/xml, text/plain ]
            GzipCompressionEnabled: true

**Comment by dbechtel89** [comment]
It isn't working on Weblogic 12.2.1.2. Only on 12.2.1.3, but 12.2.1.2 supports this option, too.

**Comment by jshum2479** [comment]
The alias is incorrectly identify GzipCompression minimal version is 12.2.1.3.  We will update it.
