### ISSUE TITLE
domainLibraries when using WebLogic Operator and no Archive

### ISSUE THREAD

**Issue by bryantidd** [oracle/weblogic-deploy-tooling#287]
When using the WebLogic Operator, my model.yaml is defined in a ConfigMap. I don't have a reasonable way to provide an archive other than on a persistent volume separate from the model. I would like to provide the libraries in a list in the model with the full path and let the WDT place them appropriately for domain library use.

I do want them in the classpath, and loaded as needed.

**Comment by CarolynRountree** [comment]
Thank you Bryan for the information.
