### ISSUE TITLE
need implementation of get_model_attribute_name in aliases

### ISSUE THREAD

**Issue by CarolynRountree** [oracle/weblogic-deploy-tooling#29]
Aliases currently has get_wlst_attribute_name(location, model_name) that returns the wlst attribute name for the model attribute name. Add a corresponding get_model_attribute_name(location, wlst_attribute_name) to return the model attribute name for the provided wlst attribute name. This is needed for validation tests.

**Comment by robertpatrick** [comment]
Is this issue still needed or can it be closed?
