### ISSUE TITLE
How to use Weblogic-Deploy-Tooling for second Machine?

### ISSUE THREAD

**Issue by dbechtel89** [oracle/weblogic-deploy-tooling#321]
I have the following topology and i can create the domain on machine1 with the deploy-tool. 
But how can i create the domain on the second machine?
If i run the same command on the second machine, the nodemanager will listen on localhost instead of listen on machine2. 

`"topology": {
    "Name": "@@PROP:DOMAIN_NAME@@",
    "AdminServerName": "AdminServer",
    "Machine": {
      "machine1": {
        "NodeManager": {
          "NMType": "Plain",
          "ListenAddress": "localhost",
          "ListenPort": "@@PROP:NODEMANAGER_SERVER1_PORT@@"
        }
      },
      "machine2": {
        "NodeManager": {
          "NMType": "Plain",
          "ListenAddress": "machine2",
          "ListenPort": "@@PROP:NODEMANAGER_SERVER2_PORT@@"
        }
      }
    },
    "Server": {
      "AdminServer": {
        "ListenPort": "@@PROP:ADMIN_PORT@@",
        "ServerStart": {
          "Arguments": "-Dlogback.configurationFile=wlsdeploy/classpathLibraries/config/logback.xml"
        },
        "Machine": "machine1",
        "SSL": {
          "Enabled": false
        }
      },
      "ms_infrastruktur1": {
        "ListenPort": "@@PROP:SERVER_INFRASTRUKTUR_PORT@@",
        "ServerStart": {
          "Arguments": "-Dlogback.configurationFile=wlsdeploy/classpathLibraries/config/logback.xml -XX:PermSize=512m -XX:MaxPermSize=1024m -Xms512m -Xmx2048m"
        },
        "Machine": "machine1",
        "SSL": {
          "Enabled": false
        }
      },
      "ms_infrastruktur2": {
        "ListenPort": "@@PROP:SERVER_INFRASTRUKTUR_PORT@@",
        "ServerStart": {
          "Arguments": "-Dlogback.configurationFile=wlsdeploy/classpathLibraries/config/logback.xml -XX:PermSize=512m -XX:MaxPermSize=1024m -Xms512m -Xmx2048m"
        },
        "Machine": "machine2",
        "SSL": {
          "Enabled": false
        }
      },
[...]`

**Comment by jshum2479** [comment]
After creating the domain, you can use the pack and unpack commands for copying the domain to another machine 

https://docs.oracle.com/cd/E24329_01/web.1211/e24498/commands.htm#WLDPU139

Currently, only the nodemanager.properties on the admin server is setup.  Affter unpacking the domain,  you will need to manually modify the nodemanager.properties file on machine2 under  $domain/nodemanager and change the ListenAddress  before starting the node manager

**Comment by ddsharpe** [comment]
I think it makes sense to support something like this.  While pack/unpack provides the functionality, its extra steps and artifacts that need to be managed.  It sounds like it would be simpler to support this use case with WDT.

**Comment by jshum2479** [comment]
On the second machine, if it is only the listen address change then you can set the environment variable LISTEN_ADDRESS (LISTEN_PORT also works) before starting the nodemanager.   This will override the settings in the nodemanager.properties file

**Comment by robertpatrick** [comment]
For now, use pack/unpack.  No plans to implement this in the near-term.  Closing for now.
