### ISSUE TITLE
Creating custom RPM / Compiling issue with weblogic-deploy/lib/python/wlsdeploy/util/statistics.py

### ISSUE THREAD

**Issue by w4z** [oracle/weblogic-deploy-tooling#336]
Hi,

WDT version: 0.21

We are building custom RPM to have WDT as package shipped on our environment.
As part of package creation the py files are compiled.

Looks like there is a problem with file:
weblogic-deploy/lib/python/wlsdeploy/util/statistics.py

Error faced:
+ /usr/lib/rpm/brp-python-bytecompile /usr/bin/python 0
Compiling <CUT> weblogic-deploy/lib/python/wlsdeploy/util/statistics.py ...
Sorry: IndentationError: expected an indented block (statistics.py, line 17)
+ /usr/lib/rpm/redhat/brp-python-hardlink

After looking into the statisctics.py we found out there is empty method causing the problem:
`    def add_info(self):`

Could you change the method to include pass, please ?
There is no error after it and the .py file is compiled properly.

Diff/Patch file has been attached.
[statistics.zip](https://github.com/oracle/weblogic-deploy-tooling/files/3038311/statistics.zip)

Thanks
Wojciech

**Comment by CarolynRountree** [comment]
statistics.py has been removed in a branch - the next release will not contain the statistics.py
