### ISSUE TITLE
Creator does not allow directories as ServerStart.ClassPath

### ISSUE THREAD

**Issue by aroemers** [oracle/weblogic-deploy-tooling#344]
When declaring the `ServerStart.ClassPath` attribute to have a directory as its value, the Creator is unable to continue. For example:

```yaml
ServerStart:
  ClassPath: 'wlsdeploy/classpathLibraries/some-directory'
```

yields the following error:

```
WLSDPLY-12409: createDomain failed to create the domain: The attribute ClassPath in 
model location topology:/Server/some-server/ServerStart/NO_NAME_0 has value 
wlsdeploy/classpathLibraries/some-directory that references a file inside the archive 
file <method ModelContext.get_archive_file_name of ModelContext instance 14850> 
that does not exist
```

If backslashes are used, the Validator yields some warnings, but the Creator works fine. It nicely copies all files from the archive, and sets the Classpath in the domain. But, using backslashes in the Classpath entry only works on Windows machines, when actually starting the WebLogic server. We need it to work with slashes as well, for the unix/linux environments.

Is this a bug? Or how to deal with this?

**Comment by rakillen** [comment]
This should work with forward slashes on Windows and Linux.

**Comment by rakillen** [comment]
It looks like an expanded archive should be OK, and your original declaration
```ClassPath: 'wlsdeploy/classpathLibraries/some-directory'```
should work.  Looking into a fix.
