### ISSUE TITLE
in newest version 0.22 create Domain with new domain type not working 

### ISSUE THREAD

**Issue by piyushwadhwani** [oracle/weblogic-deploy-tooling#354]
i was using weblogic tooling version 0.14 earlier , and as part of the domain creation i have defined custom domain type. which is kept at  lib/typedefs/

I was able to create domain by giving
-domain_type APP , but with recent version 0.22 its giving invalid domain 

sample custom domain

{
    "name": "APP",
    "description": "APP type domain definitions  with wls 12.2.1.3",
    "versions": {
        "12.2.1.3": "APP_12213"
    },
    "definitions": {
        "APP_12213": {
            "baseTemplate": "Basic WebLogic Server Domain",
            "extensionTemplates": [
                "Oracle JRF",
                "Oracle Enterprise Manager",
                "Oracle JRF SOAP/JMS Web Services"
            ],
            "serverGroupsToTarget": [ "JRF-MAN-SVR" ],
            "rcuSchemas": [ "STB", "WLS", "MDS", "IAU", "IAU_VIEWER", "IAU_APPEND", "OPSS"  ]
        }
    }
}

**Comment by ddsharpe** [comment]
Thanks, we will get this corrected.
