### ISSUE TITLE
deployApps not working if Sourcepath of application is outside of archive

### ISSUE THREAD

**Issue by dbechtel89** [oracle/weblogic-deploy-tooling#360]
WDT Version: 0.22

If i have an application with a SourcePath outside of the archive file, the application is not copied to the domain. The AppDeployment MBean is created, but no file is existing.

**Comment by ddsharpe** [comment]
Why is it necessary to copy the file to the domain directory?  It is a legitimate use case to have a domain reference an application from an external directory.

**Comment by ddsharpe** [comment]
Closing this issue due to lack of response.  Please open a new issue with the requested explanation if this is still an issue for you.
