### ISSUE TITLE
force deploying application

### ISSUE THREAD

**Issue by cchaplin** [oracle/weblogic-deploy-tooling#367]
We have a webapplication (war file) deployed in weblogic server using WDT with context root /myroot. Now i tried to deploy another version of same application (with same context root /myroot). It fails, which is expected as there is already an application with same context root. Is there a way to handle this using WDT - basically force deploy the war file ?

When we were using weblogic.deploy command line tool (default built-in tool) the tool would give an error with message that an appliciation with the given context root already exist (with applilcation name and context root). basically we had a wrapper script which calls the deploy command, if this error occurs, we would undeploy the application which already exists (the deploy command  would provide teh application  name and context root in error message).

But the WDT does not give such  error ? any suggestions on how to go about?

Many Thanks.

**Comment by jshum2479** [comment]
In wlst, there is a redeploy command that allows you do update an app.  WDT online deploy (i.e. with -admin_user -admin_url options) works with it.   However, the full path of the war file must be the same and it cannot be changed,  so you cannot deploy any application or library using the same name but with a different path to it.  

The current WDT online deploy also tries to optimize the strategy for undeploy, redeploy and stop/start/restart the app or shared library as needed; so you may not see any error or there may be cases we are not handling correctly.  

Would you mind sharing your use case with more details ?  e.g.  Are you packaging the war file in the archive and then use WDT for deployment or just referencing it with the absolute path in the model,   any plan.xml involved,  what changes in the new war file for new update deployment?  What process is used to create the archive - CI/CD process?  manual process etc ...

**Comment by cchaplin** [comment]
We are building the war file (maven build) and creating the archive (zip file as required by WDT tool) with war file and model file (.yml) which references the war file inside the archive. 
We have Ansible playbook which 
- Take the war file, create model file and the necessary WDT archive. 
- copy the WDT archive to weblogic admin server
- Deploy the archive using WDT tooling

We have hundreds of SOAP based web services (JAX-WS) deployed on Weblogic 10.3.6 environment. 
**Context:** Say we have deployed a service AccountDetails with context root /AccountDetails_1_0. The version information is part of the context root (_1_0). Only when the service undergoes major change (non backward compatible change) the version number in context root is incremented (say _1_1). Else for any bug fixes or minor changes (backward compatible) the version number in context root remains same.

Scenario 1: in the test environment, the AccountDetails service with context root /AccountDetails_1_0 is deployed on test environment (say UAT). The test team has found an issue, the development team has fixed it and we need to deploy it to the test environment so that the fix can be verified. Since this is bug fix, the service will have same context root (/AccountDetails_1_0). The deployment fails. only option is to undeploy already existing service (the one with bug) and deploy the new service (bug fixed)

Scenario 2: In production environment, the service can undergo changes (new feature, bug fix etc) and if the changes does not result in incrementing version number in context root (when new optional element is added to  soap request or bug fix). Again when trying to deploy this service results in failure because the context root already exist. 

As part of automation, our idea was to try deploying the service, if the tool reports back error (like the undeploy of weblogic.deploy tool) try deleting the existing service (again this detail was given in the error message reported by weblogic.Deploy tool) and deploy again.

**Comment by jshum2479** [comment]
Thanks for the information,  I think we should have a way to handle this.  When you are using weblogic.Deploy tool, are you using the -redeploy option ?,  there shouldn't be a need to undeploy and delete the service manually.   

https://docs.oracle.com/middleware/12213/wls/DEPGD/redeploy.htm#DEPGD259  (look for in-place redeployment).

**Comment by jshum2479** [comment]
I discovered a bug in the deploy tool for supporting your use case and I have a fix for that, once it is merged and release, it should work if you are using the same name for the app deployment.  

If you are using the version in your deployment names (e.g. account_service1.0, account_service1.1), even if the context root is the same, the current tool does not support it, but we will need to look further to investigate how to support it.

**Comment by cchaplin** [comment]
Thanks for the information. Typically, the deployments were manual using weblogic web console. We started to automate recently. Not sure if -redeploy option to weblogic.Deploy worked. I will recheck again. Thanks

**Comment by jshum2479** [comment]
Please try this with the latest vesion.
