### ISSUE TITLE
Extension templates not getting applied after WDT upgrade

### ISSUE THREAD

**Issue by 53d117460ec63d70** [oracle/weblogic-deploy-tooling#370]
Definition extension templates are no longer applied after upgrading from WDT 0.20 to 0.21. I am testing using WLS10.3.6 with the following typesdef file:
```json
{
    "copyright": "Copyright (c) 2017, 2018, Oracle and/or its affiliates. All rights reserved.",
    "license": "The Universal Permissive License (UPL), Version 1.0",
    "name": "WLS",
    "description": "WLS type domain definitions",
    "versions": {
        "10.3.6": "WLS_11G",
        "12.1.1": "WLS_11G",
        "12.1.2": "WLS_12CR1",
        "12.1.3": "WLS_12CR1",
        "12.2.1": "WLS_12CR2",
        "19.1":   "WLS_19CR1"
    },
    "definitions": {
        "WLS_11G": {
            "baseTemplate": "@@WL_HOME@@/common/templates/domains/wls.jar",
            "extensionTemplates": ["@@ORACLE_HOME@@/Oracle_BI1/common/templates/applications/oracle.bipublisher_template_11.1.1.jar" ],
            "serverGroupsToTarget": [ ],
            "rcuSchemas": [ ]
        },
        "WLS_12CR1": {
            "baseTemplate": "@@WL_HOME@@/common/templates/wls/wls.jar",
            "extensionTemplates": [ ],
            "serverGroupsToTarget": [ ],
            "rcuSchemas": [ ]
        },
        "WLS_12CR2": {
            "baseTemplate": "Basic WebLogic Server Domain",
            "extensionTemplates": [ ],
            "serverGroupsToTarget": [ ],
            "rcuSchemas": [ ]
        },
        "WLS_19CR1": {
            "baseTemplate": "Basic WebLogic Server Domain",
            "extensionTemplates": [ ],
            "serverGroupsToTarget": [ ],
            "rcuSchemas": [ ]
        }
    }
}
```
EDIT: I see the same issue on WDT 0.22 and 0.24.

**Comment by CarolynRountree** [comment]
When you say no longer applied, do you not see the resources from your extension template in the config.xml, or are the resources in the config.xml but not targeted to the managed servers?

**Comment by 53d117460ec63d70** [comment]
With WDT versions >0.20 I don't see the resources in config.xml nor do I get the additional files added to the domain by the extension template.

**Comment by CarolynRountree** [comment]
A fix for this problem will be available in the next release. This couuld require a change to your typedef file. Any change will be documented.

FYI, the current release has cleaned up WDT bin scripts. You can create your own typedef file, instead of updating the WLS.json, and use this name as the domain type on the command line.  Also, if you are running the WLST script out of oracle_common, and not Oracle_BI1, then you no longer need to set the WLST_PATH_DIR environment variable.

**Comment by 53d117460ec63d70** [comment]
Thanks! Regarding the typedef files, is there any way to reference these outside of the WDT installation, eg an environment variable?

**Comment by CarolynRountree** [comment]
You are talking about -domain_type <mytypedef env var> correct  (Not location of the file)? That's a good idea. Would you please open a separate issue for this idea.

**Comment by 53d117460ec63d70** [comment]
Oh, I *was* actually talking about the location of the file! WDT only looks in `weblogic-deploy/lib/typedefs` for the typedef files so if I want to use a custom typedef I have to add it to that directory. It seems cleaner to have my custom files separate from the WDT installation? That's why I was thinking of an environment variable that could override the default location.

**Comment by CarolynRountree** [comment]
Also a good suggestion. Please open issue.

**Comment by 53d117460ec63d70** [comment]
Great, done: https://github.com/oracle/weblogic-deploy-tooling/issues/371#issue-439691017

**Comment by rakillen** [comment]
Changes to fix the template problems (not including file location) have all been merged to master now. They will be part of the next release, 0.25 .

There is one change you will need for your typedef file. Include the attribute `"targeting": "APPLY_JRF"` in your 11g definition.

Details in [Domain Type Definitions](/oracle/weblogic-deploy-tooling/blob/master/site/type_def.md).
