### ISSUE TITLE
Alternative typedef files directory

### ISSUE THREAD

**Issue by 53d117460ec63d70** [oracle/weblogic-deploy-tooling#371]
WDT looks in `weblogic-deploy/lib/typedefs` for the typedef files. If I want to use a custom typedef I have to add it to that directory. It seems cleaner to have custom typedef files separate from the WDT installation. Could WDT support a mechanism for specifying an alternative typedef files directory, possibly an environment variable that could override the default location?

**Comment by ddsharpe** [comment]
What if we created an `WDT_ADDITIONAL_TYPEDEFS` environment variable that pointed to an additional folder that we could scan for typedefs?  The variable would be empty/null by default.  WDT would always scan the `weblogic-deploy/lib/typedefs` folder first, and look in `WDT_ADDITIONAL_TYPEDEFS` when a type is not found.  The `WDT_ADDITIONAL_TYPEDEFS` would only support a flat folder (scans the folder and not sub-directories).

**Comment by 53d117460ec63d70** [comment]
That sounds good. Would it be preferable for `WDT_ADDITIONAL_TYPEDEFS` to take precedence over `weblogic-deploy/lib/typedefs`? This would allow custom typedef files to have the same name as those in the binary, providing an 'overwrite' function.

**Comment by wszczurek** [comment]
"preferable for WDT_ADDITIONAL_TYPEDEFS to take precedence over
weblogic-deploy/lib/typedefs"
I would like to vote for this order too, if possible ;).
This is the pattern used quite widely, that the ENV VARIABLE "overwrite"
standard config data.

**Comment by ddsharpe** [comment]
If the user thinks they are using --domain_type WLS, I would think that it would be confusing to the user if the result was something different because of a version found in the additional typedef folder.  What is the downside of having additional typedefs with different names, like WLS_SPECIAL1?

**Comment by 53d117460ec63d70** [comment]
Having `deploy/lib/typedefs` scanned first would require the custom typedef designer to first check that their custom typedef filename isn't the same as one in `deploy/lib/typedefs` too avoid that being read first. This could be problematic if additional typedefs are added to `deploy/lib/typedefs` with successive WDT releases. Should a WDT release introduce a filename that I have been using as a custom typedef then I will no longer get my custom typedef. I think having `WDT_ADDITIONAL_TYPEDEFS` scanned preferentially allows for the principal of least astonishment. Or could there be two variables, pre and post, so that the user can decide?

**Comment by kaifricke** [comment]
Why don't ues a flag like we have for Webapps (prefer-web-inf-classes), eg prefer-builtin_types or prefer_user_types.  So the user can decide what he wants to take precedence in case of a conflict.

**Comment by wszczurek** [comment]
@kaifricke That would be even better.
With just one variable it could be translated to: 
If the environment variable `WDT_ADDITIONAL_TYPEDEFS` is set and not empty then it could work like `prefer_user_types`.
Of course more flexibility the better.

**Comment by ddsharpe** [comment]
Thanks everyone for the great brainstorming session here.  I like these ideas.

**Comment by rakillen** [comment]
There are additional configuration files and directories and files under <WDT>/lib now for injector and filter configuration, etc. It might be preferable for the environment variable to point to an alternative .../lib location, that could contain customized versions of those files and directories. Maybe WDT_CUSTOM_CONFIG, and use it as the first element of a search path for these.

**Comment by vdrHorst** [comment]
After upgrading/using the new WDT version, I now need to create symlinks to all (three) custom typedef files in <WDTversion>/lib/typedef to my own typedef library somewhere else on the filesystem. Doable but hope this can be enhanced (soon) using the proposed WDT_CUSTOM_CONFIG environment variable by @rakillen. (+1)
