### ISSUE TITLE
Domain User and Group creation

### ISSUE THREAD

**Issue by 53d117460ec63d70** [oracle/weblogic-deploy-tooling#376]
Can WLS users and groups be specified in the model so that WDT will add them to the created domain? The documentation states that they cannot be discovered (https://github.com/oracle/weblogic-deploy-tooling/blob/master/site/discover.md) but I cannot see any mention of creation.

**Comment by ddsharpe** [comment]
Not today.  We have talked about this several times, but never implemented it.  There hasn't been any demand for it, since WLS recommends using external LDAP providers over the embedded LDAP in production.  If you feel like this is a big deal for your use case, it would help me if could you describe the impact to you, your project, or your company.

**Comment by 53d117460ec63d70** [comment]
For domains that use embedded LDAP we are updating `DefaultAuthenticatorInit.ldift` with the users and groups after the domain has been created. It would be cleaner to have all the domain config in the model but it's not a big deal. Thanks.

**Comment by wszczurek** [comment]
It is useful to have support for creating users and groups in WDT in my opinion.
This could be especially useful if we have more than one authentication providers (Local LDAP and Remote/Central LDAP).
There is quite often rule to not rely only on Remote/Central LDAP but to keep in place local LDAP too.
The WLS instances need to be available (access) via local authentication provider if the network connectivity to remote, central LDAP is not available.

**Comment by ddsharpe** [comment]
@53d117460ec63d70 which API are you using to update the ldift file?
@wszczurek are you saying that you need to load users/groups locally and remotely?  

Which version(s) of WLS are you using?

**Comment by wszczurek** [comment]
WLS: 10.3.6 and 12.2.1.3

The users are different in local and remote (central) ldap.
There are generic, non-personal users in the Local LDAP. You can think about them like generic/system/service accounts.
There are personal users (real people) in the Central/Remote LDAP.

With this approach WLS is working properly even if you do not have access to Central/Remote LDAP. It is useful in case you have many system around the globe and you do not want to have "Permanent" dependency to Central/Remote LDAP, which can be not always available.

**Comment by 53d117460ec63d70** [comment]
> @53d117460ec63d70 which API are you using to update the ldift file?
> @wszczurek are you saying that you need to load users/groups locally and remotely?
> 
> Which version(s) of WLS are you using?

WLS10.3.6
I'm currently using the ansible blockinfile module with a Jinja2 template and creating the salted SHA1 hashed with a custom ansible filter plugin.

**Comment by rakillen** [comment]
Fixed with #411
