### ISSUE TITLE
Option to disable binary archiving during discover

### ISSUE THREAD

**Issue by 53d117460ec63d70** [oracle/weblogic-deploy-tooling#378]
Would it be possible to provide a feature to disable binary archiving and the binary path updates in the model during discover? I would like to manage my binaries independently. To allow me to do this I currently have to reinstate the binary paths in the model after domain discovery. It would be preferable to optionally disable archiving and have the binary paths left unchanged. Disabling archiving would also speed up the discover process.

**Comment by larspusa** [comment]
Sounds like a good option.

**Comment by robertpatrick** [comment]
Implemented, use `-skip_archive` option to `discoverDomain`
