### ISSUE TITLE
Alias change needed for ResourceManager in Partition

### ISSUE THREAD

**Issue by CarolynRountree** [oracle/weblogic-deploy-tooling#39]
Partition.json and ResourceManagement.json both include ResourceManager.json. The wlst_type for ResourceManager is ResourceManager${:s}. The mbean type in online wlst is /ResourceManagement/ResourceManagers and Partition/ResourceManager.

**Comment by mwooten** [comment]
This sounds similar to Issue# 38, but I'm not sure the same fix (giving Partition.json it's own ResourceManager folder) is what we want. Will discuss with Derek, to see if he thinks this should be a change to the aliases code, instead of modifying the alias JSON file.

**Comment by CarolynRountree** [comment]
I agree with you.

**Comment by robertpatrick** [comment]
Personally, I would just duplicate the aliases for Resource Manager instead of trying to be too smart in solving this problem.  The aliases are complex enough without having to deal with this naming issue based on context.
