### ISSUE TITLE
Server group targeting fails (add used on list instead of append)

### ISSUE THREAD

**Issue by Omar007** [oracle/weblogic-deploy-tooling#394]
Targeting to dynamic clusters seems to still be WIP but even if you currently try to do so, it bails out early and crashes on a call to add() in wlsdeploy/tool/util/target_helper.py.
It seems the target is supposed to be added to 'cluster_members' on line 360
https://github.com/oracle/weblogic-deploy-tooling/blob/3058d27259e74577a84a8ae0e0acd071d79553bd/core/src/main/python/wlsdeploy/tool/util/target_helper.py#L360
but a call to 'add' is used instead of 'append', resulting in an AttributeError.

**Comment by CarolynRountree** [comment]
Fix will be included in the next release. WIP

**Comment by CarolynRountree** [comment]
Merged into master. Available in next release. Please view known issues document

**Comment by ddsharpe** [comment]
Fixed by #396
