### ISSUE TITLE
Error when creating a minimal domain

### ISSUE THREAD

**Issue by timfel** [oracle/weblogic-deploy-tooling#397]
If you use the minimal model from https://github.com/oracle/weblogic-deploy-tooling/blob/master/site/create.md, you get an error currently on these two lines:

https://github.com/oracle/weblogic-deploy-tooling/blob/105c9e669d5a8b9cd7a7712e774821f620c89e5a/core/src/main/python/wlsdeploy/tool/create/domain_creator.py#L490 and https://github.com/oracle/weblogic-deploy-tooling/blob/105c9e669d5a8b9cd7a7712e774821f620c89e5a/core/src/main/python/wlsdeploy/tool/create/domain_creator.py#L496

The reason is that `server_assigns` and `dynamic_assigns` are `None`. A simple fix is this, which does the same thing for objects with a length and works also with `None`:
```diff
diff --git a/core/src/main/python/wlsdeploy/tool/create/domain_creator.py b/core/src/main/python/wlsdeploy/tool/create/domain_creator.py
index 8663db0..3a15346 100644
--- a/core/src/main/python/wlsdeploy/tool/create/domain_creator.py
+++ b/core/src/main/python/wlsdeploy/tool/create/domain_creator.py
@@ -487,13 +487,13 @@ class DomainCreator(Creator):

         server_groups_to_target = self._domain_typedef.get_server_groups_to_target()
         server_assigns, dynamic_assigns = self.target_helper.target_server_groups_to_servers(server_groups_to_target)
-        if len(server_assigns) > 0:
+        if server_assigns:
             self.target_helper.target_server_groups(server_assigns)

         self.wlst_helper.write_domain(domain_home)
         self.wlst_helper.close_template()

-        if len(dynamic_assigns) > 0:
+        if dynamic_assigns:
             self.target_helper.target_server_groups_to_dynamic_clusters(dynamic_assigns)

         self.logger.exiting(class_name=self.__class_name, method_name=_method_name)
```

**Comment by ddsharpe** [comment]
fixed by #398
