### ISSUE TITLE
Steps to configure Oracle Diagnostic Logger (ODL) using WDT 

### ISSUE THREAD

**Issue by rakesh-253** [oracle/weblogic-deploy-tooling#412]
Our product uses FMW's **12.2.1.3** Oracle Diagnostic Logging(ODL) Framework for logging messages. In a traditional installation of a Weblogic domain with Enterprise Manager (EM) template selected, we were able to configure/modify below ODL's default behavior by using EM console UI - 
- Log file size & Retention Policy - [Configuring Log File Rotation](https://docs.oracle.com/en/middleware/lifecycle/12.2.1.3/asadm/managing-log-files-and-diagnostic-data.html#GUID-391C6ADF-1D5D-46B4-A7F6-C9CF855F8AF6)
- Log Level of messages to be logged - [Setting the Level of Information Written to Log Files
](https://docs.oracle.com/en/middleware/lifecycle/12.2.1.3/asadm/managing-log-files-and-diagnostic-data.html#GUID-5F581C02-5E7A-4865-87E9-98AC8A91A02F)

This Logging customization usually gets saved under `<domain_home>/config/fmwconfig/<server-name>/logging.xml`

Using WDT Model, we would like to achieve the same logging customization and build/deploy domain images with our product's preferred/recommended configuration. However, the existing documentation for [Metamodel](https://github.com/oracle/weblogic-deploy-tooling#the-metadata-model) does not have enough information to cover this requirement. 

Can you please provide a WDT model sample to configure FMW's ODL Logging in a Webogic domain?

As suggested by Carolyn R, adding below - 
- Version: This is for FMW 12.2.1.3
- Timeline: It would be great if you can accommodate this request in your next release cycle. 

PS: I have found this **online** WLST commands for configuring ODL - [Logging Custom WLST Commands](https://docs.oracle.com/en/middleware/lifecycle/12.2.1.3/fcccr/logging-custom-wlst-commands.html#GUID-A0DD57A3-AE33-400E-BE91-6D20C25D05A5)

**Comment by CarolynRountree** [comment]
Fixed in 1.6.0. See documentation at https://github.com/oracle/weblogic-deploy-tooling/blob/master/site/odl_configuration.md
