### ISSUE TITLE
specifying weblogic deployment  upload directory

### ISSUE THREAD

**Issue by cchaplin** [oracle/weblogic-deploy-tooling#435]
When we use deployApps.sh, the ear/ear files are uploaded to wlsdeploy/applications/ directory under the <DOMAIN_HOME>. Is it possible to provide an alternate location to where the files should be uploaded ? like uploads directory under <DOMAIN_HOME>/servers/<Admin_server_name>/upload or other directories external to <DOMAIN_HOME>

**Comment by ddsharpe** [comment]
The WDT tools (create, deployApps, ...) use the wlsdeploy folder for several reasons.  The primary reason being safety.  With the known folder approach, WDT is able to reduce the chance of failures, greatly simplify file operations, and prevent accidental damage to an existing domain.  The cost of stepping out of this "safe zone" is not something we are interested in taking on at this time.
It is possible to have applications outside the wlsdeploy folder.  For example, you can pre-place the file in a location outside the domain home, and then model the full path of that file in the WDT yaml.

**Comment by cchaplin** [comment]
Thanks Derek. I will use the suggested method.
