### ISSUE TITLE
Add missing JMS attributes to aliases

### ISSUE THREAD

**Issue by ddsharpe** [oracle/weblogic-deploy-tooling#44]
/JMSSystemResource/JmsResource/DistributedTopic attribute SAFExportPolicy 
/JMSSystemResource/JmsResource/DistributedQueue attribute SAFExportPolicy 
/JMSSystemResource/JmsResource/ForeignServer attribute JNDIPropertiesCredential 
/JMSSystemResource/JmsResource/ForeignServer/ForeignConnectionFactory attribute Password 
/JMSSystemResource/JmsResource/ForeignServer/ForeignConnectionFactory attribute RemoteJNDIName 
/JMSSystemResource/JmsResource/ForeignServer/ForeignDestination attribute RemoteJNDIName 
/JMSSystemResource/JmsResource/Queue attribute DestinationKeys 
/JMSSystemResource/JmsResource/Queue attribute JMSCreateDestinationIdentifier 
/JMSSystemResource/JmsResource/Queue attribute SAFExportPolicy 
/JMSSystemResource/JmsResource/SAFErrorHandling attribute SAFErrorDestination 
/JMSSystemResource/JmsResource/SAFImportedDestinations/SAFQueue attribute RemoteJNDIName 
/JMSSystemResource/JmsResource/SAFImportedDestinations/SAFTopic attribute RemoteJNDIName 
/JMSSystemResource/JmsResource/SAFRemoteContext/SAFLoginContext attribute Password 
/JMSSystemResource/JmsResource/Template attribute DestinationKeys 
/JMSSystemResource/JmsResource/Topic attribute DestinationKeys 
/JMSSystemResource/JmsResource/Topic attribute JMSCreateDestinationIdentifier 
/JMSSystemResource/JmsResource/Topic attribute SAFExportPolicy 
/JMSSystemResource/JmsResource/UniformDistributedQueue attribute DestinationKeys 
/JMSSystemResource/JmsResource/UniformDistributedQueue attribute JMSCreateDestinationIdentifier 
/JMSSystemResource/JmsResource/UniformDistributedQueue attribute SAFExportPolicy 
/JMSSystemResource/JmsResource/UniformDistributedTopic attribute DestinationKeys 
/JMSSystemResource/JmsResource/UniformDistributedTopic attribute JMSCreateDestinationIdentifier 
/JMSSystemResource/JmsResource/UniformDistributedTopic attribute SAFExportPolicy

**Comment by mwooten** [comment]
I need Pull Request #43 to either be merged or rejected before doing this, or else there will be merge conflicts like we had before. If you want to reject it, I'll delete the associated branch and create a new one for adding these JMS attributes.

**Comment by ddsharpe** [comment]
Why don’t you just remove the 9800 messages from that branch, and then I will accept it and merge it?

**Comment by mwooten** [comment]
Hi Derek,

It looks like the attributes you want added are already there. There is a difference in the case, but the attributes are there:

"attributes": {
    "AttachSender":                   [ {"version": "[10,)", "wlst_mode": "both", "wlst_name": "AttachSender",                          "wlst_path": "WP001", "value": {"default
    "ConsumptionPausedAtStartup":     [ {"version": "[10,)", "wlst_mode": "both", "wlst_name": "ConsumptionPausedAtStartup",            "wlst_path": "WP001", "value": {"default
    "DefaultTargetingEnabled":        [ {"version": "[10,)", "wlst_mode": "both", "wlst_name": "DefaultTargetingEnabled",               "wlst_path": "WP001", "value": {"default
    "DefaultUnitOfOrder":             [ {"version": "[10,)", "wlst_mode": "both", "wlst_name": "DefaultUnitOfOrder",                    "wlst_path": "WP001", "value": {"default
    **"DestinationKey":                 [ {"version": "[10,)", "wlst_mode": "both", "wlst_name": "DestinationKey${:s}",**                   "wlst_path": "WP001", "value": {"default
    "ForwardDelay":                   [ {"version": "[10,)", "wlst_mode": "both", "wlst_name": "ForwardDelay",                          "wlst_path": "WP001", "value": {"default
    "IncompleteWorkExpirationTime":   [ {"version": "[10,)", "wlst_mode": "both", "wlst_name": "IncompleteWorkExpirationTime",          "wlst_path": "WP001", "value": {"default
    "InsertionPausedAtStartup":       [ {"version": "[10,)", "wlst_mode": "both", "wlst_name": "InsertionPausedAtStartup",              "wlst_path": "WP001", "value": {"default
    "JNDIName":                       [ {"version": "[10,)", "wlst_mode": "both", "wlst_name": "JNDIName",                              "wlst_path": "WP001", "value": {"default
    **"JmsCreateDestinationIdentifier": [ {"version": "[10,)", "wlst_mode": "both", "wlst_name": "${Jms:JMS}CreateDestinationIdentifier"**, "wlst_path": "WP001", "value": {"default
    "LoadBalancingPolicy":            [ {"version": "[10,)", "wlst_mode": "both", "wlst_name": "LoadBalancingPolicy",                   "wlst_path": "WP001", "value": {"default
    "LocalJNDIName":                  [ {"version": "[10,)", "wlst_mode": "both", "wlst_name": "LocalJNDIName",                         "wlst_path": "WP001", "value": {"default
    "MaximumMessageSize":             [ {"version": "[10,)", "wlst_mode": "both", "wlst_name": "MaximumMessageSize",                    "wlst_path": "WP001", "value": {"default
    "MessagingPerformancePreference": [ {"version": "[10,)", "wlst_mode": "both", "wlst_name": "MessagingPerformancePreference",        "wlst_path": "WP001", "value": {"default
    "Notes":                          [ {"version": "[10,)", "wlst_mode": "both", "wlst_name": "Notes",                                 "wlst_path": "WP001", "value": {"default
    "ProductionPausedAtStartup":      [ {"version": "[10,)", "wlst_mode": "both", "wlst_name": "ProductionPausedAtStartup",             "wlst_path": "WP001", "value": {"default
    "Quota":                          [ {"version": "[10,)", "wlst_mode": "both", "wlst_name": "Quota",                                 "wlst_path": "WP001", "value": {"default
    "ResetDeliveryCountOnForward":    [ {"version": "[10,)", "wlst_mode": "both", "wlst_name": "ResetDeliveryCountOnForward",           "wlst_path": "WP001", "value": {"default
    **"SafExportPolicy":                [ {"version": "[10,)", "wlst_mode": "both", "wlst_name": "${Saf:SAF}ExportPolicy"**,                "wlst_path": "WP001", "value": {"default
    "SubDeploymentName":              [ {"version": "[10,)", "wlst_mode": "both", "wlst_name": "SubDeploymentName",                     "wlst_path": "WP001", "value": {"default
    "Template":                       [ {"version": "[10,)", "wlst_mode": "both", "wlst_name": "Template",                              "wlst_path": "WP001", "value": {"default
    "UnitOfOrderRouting":             [ {"version": "[10,)", "wlst_mode": "both", "wlst_name": "UnitOfOrderRouting",                    "wlst_path": "WP001", "value": {"default
    "UnitOfWorkHandlingPolicy":       [ {"version": "[10,)", "wlst_mode": "both", "wlst_name": "UnitOfWorkHandlingPolicy",              "wlst_path": "WP001", "value": {"default
},

**Comment by ddsharpe** [comment]
There was a bug in the validation code.  This is not an issue with WDT.
