### ISSUE TITLE
Failed to get environment, environ will be empty:

### ISSUE THREAD

**Issue by JaikrishnaPatel** [oracle/weblogic-deploy-tooling#445]
When I tried to use this out of box, I get following exception.  Do I need to make this directory C:\Test\weblogic-deploy\bin>createDomain.cmd -oracle_home C:\WLS1213 -domain_type=WLS -domain_parent C:\WLS1213\user_projects\domains\JimDomain -model_file MinimalDemoDomain.yaml
JDK version is 1.8.0_212, setting JAVA_VENDOR to Sun...
JAVA_HOME = C:\PROGRA~1\Java\JDK18~1.0_2
WLST_EXT_CLASSPATH = C:\Test\WEBLOG~1\lib\weblogic-deploy-core.jar
CLASSPATH = C:\Test\WEBLOG~1\lib\weblogic-deploy-core.jar
WLST_PROPERTIES = -Djava.util.logging.config.class=oracle.weblogic.deploy.logging.WLSDeployCustomizeLoggingConfig -Dcom.oracle.cie.script.throwException=true
C:\WLS1213\oracle_common\common\bin\wlst.cmd C:\Test\WEBLOG~1\lib\python\create.py -oracle_home C:\WLS1213 -domain_type=WLS -domain_parent C:\WLS1213\user_projects\domains\JimDomain -model_file MinimalDemoDomain.yaml
Java HotSpot(TM) 64-Bit Server VM warning: ignoring option MaxPermSize=256m; support was removed in 8.0
Picked up _JAVA_OPTIONS: -Xmx512M

Initializing WebLogic Scripting Tool (WLST) ...

Welcome to WebLogic Server Administration Scripting Shell

Type help() for help on available commands

Failed to get environment, environ will be empty: (0, 'Failed to execute command ([\'sh\', \'-c\', \'env\']): java.io.IOException: Cannot run program "sh": CreateProcess error=2, The system cannot find the file specified')
Problem invoking WLST - Traceback (innermost last):
  File "C:\Test\WEBLOG~1\lib\python\create.py", line 36, in ?
  File "C:\Test\weblogic-deploy\lib\python\wlsdeploy\tool\create\domain_typedef.py", line 23, in ?
  File "C:\Test\weblogic-deploy\lib\python\wlsdeploy\tool\create\domain_typedef.py", line 29, in DomainTypedef
  File "C:\WLS1213\wlserver\common\wlst\modules\jython-modules.jar\Lib/javapath$py.class", line 110, in join
  File "C:\WLS1213\wlserver\common\wlst\modules\jython-modules.jar\Lib/javapath$py.class", line 27, in _tostr
TypeError: join() argument must be a str or unicode object, not 'NoneType' object

**Comment by ddsharpe** [comment]
If you run the following code in a WLST shell, do you get the same error regarding the environment not found?

```
import javaos

print javaos.getenv("user.name")
```

**Comment by JaikrishnaPatel** [comment]
C:\Test\weblogic-deploy\bin>java weblogic.WLST
Picked up _JAVA_OPTIONS: -Xmx512M

Initializing WebLogic Scripting Tool (WLST) ...

Welcome to WebLogic Server Administration Scripting Shell

Type help() for help on available commands

wls:/offline> import javaos
wls:/offline> print javaos.getenv("user.name")
Failed to get environment, environ will be empty: (0, 'Failed to execute command ([\'sh\', \'-c\', \'env\']): java.io.IOException: Cannot run program "sh": CreateProcess error=2, The system cannot find the file specified')
None
wls:/offline>

**Comment by ddsharpe** [comment]
This is a known issue for Windows 10 users and older versions of WebLogic Server.  The OS type map in older versions of WLST/Jython did not include Windows 10.  WebLogic Server fixed this in 12.2.1.1.0+ and there are patches available for older versions still under support contract. On Oracle's Support web site, this fix is referenced as bug 22138883.

**Comment by JaikrishnaPatel** [comment]
Is this patch available for 12.1.3?  We are using 12.1.3

**Comment by ddsharpe** [comment]
If 12.1.3 is still in the support matrix, it would need to be back-ported to that release.  You will need to reach out to Oracle Support and request the patch.

**Comment by JaikrishnaPatel** [comment]
Thanks Derek.  Will open up SR with Oracle for this patch.  Looks like only there for 10.3.6 and 12.2.1
