### ISSUE TITLE
Discovery tool doc doesn't match discovery tool help

### ISSUE THREAD

**Issue by tbarnes-us** [oracle/weblogic-deploy-tooling#446]
The help output from `/u01/wdt/weblogic-deploy/bin/discoverDomain.sh` doesn't match the documentation at `https://github.com/oracle/weblogic-deploy-tooling/blob/master/site/discover.md`.

For example, the help mentions options that the doc doesn't (wlst path, domain type, admin URL/user).

Also, I wonder why admin_url and admin_user are mentioned in the first place - I thought the discover tool was an off-line tool...

Finally, should the doc mention the '.sh' script in addition to the '.cmd' script?

**Comment by tbarnes-us** [comment]
Another item:  The discover tool is capable of generating yaml, so it'd be helpful if the doc mentioned this (the doc currently only provides example of creating a .json).

**Comment by rakillen** [comment]
I'll look into these.

One note, discover does have an online mode.  Need to have that in the doc also.

**Comment by CarolynRountree** [comment]
Fixed in 1.6.0.
