### ISSUE TITLE
How to create complete same domain using deploy tooling

### ISSUE THREAD

**Issue by atjapan2015** [oracle/weblogic-deploy-tooling#449]
Hi experts,

This is a task about migrating existing on-premise weblogic to weblogic cloud on OCI.
We are considering using weblogic deploy tooling to do the migration and verifying the feasibility of weblogic deploy tooling.

firstly, we want try one simple thing, re-create same domain on the same machine.

1. Step 0, using config.sh creating a new domain. (Domain Name: first_domain)
2. Step 1, using discoverDomain.sh to output model yaml of first domain.
3. Step 2, adding (domainInfo and others) to output model yaml. (**Question 1**:Why domainInfo is not output? and how many additional info do we need to add?)
4. Step 3, backup first_domain to first_domain_bak.
5. Step 4, using createDomain.sh and modified model yaml to create same domain.(Domain Name: first_domain)
6. Step 5, using "diff -r first_domain first_domain_bak" to check the result, there are many differences. (**Question 2**:Why there are so many differences?)

**Question 3**: Is there any guide for re-create a complete same domain by using weblogic deploy tooling?

Attached file is the differences between first_domain and first_domain_bak.
Feel free to let me know if you need any other info.
[differences.xlsx](https://github.com/oracle/weblogic-deploy-tooling/files/3666462/differences.xlsx)

Thanks& Best Regards!

**Comment by CarolynRountree** [comment]
Per your question in number 3. WDT has a couple of utilities to assist with managing your model. You can code a filter to add/remove/update mbeans and attributes in the model.  A variable injector is used to insert a token into an attribute and put the token and value into a variable file. Both  can be run in either discover or create. In discover, the utilities are run before persisting the model. The filters are run first and then the variable injectors. You can use both to create the domainInfo section and add the adminUser and adminPassword (perhaps use the variable injector to add tokens for the attributes)

Per the diff. The main differences are the password fields. Each domain has a new encryption "seed" file. This is used to encrypt the passwords in the config xml files. This means that the same password in two different domains will not be the same.

What is your goal with the diff? Are you using it for exploration of the WDT tool, or do you plan to incorporate this as part of your migration? I am asking to determine what we can do to help you.

I will need to find out if the config.sh creates a backup of the config.xml, and if so, why WLST does not create the same back-up.

**Comment by ddsharpe** [comment]
Question 3:  It is possible to create the same domain over and over again.  Yes.  But if you want to compare encrypted values, then no, these will not be the same.  The ability to re-use the same encryption key for multiple domain creations does not exist in WebLogic Server, yet.

Question 2: There are differences because you are comparing encrypted values (see responses to question 3).  And, several of the differences of other fields are errors in your compare, as values are equal with the exception of whitespace.  

Question 1:  I do not understand the question.
