### ISSUE TITLE
delete notation does not work with quoted entity

### ISSUE THREAD

**Issue by jshum2479** [oracle/weblogic-deploy-tooling#451]
In the model, if I specify

1. !mydatasource  works
2. !'mydatasource' does not work. This limit the naming of the entity such as 'my-data-source' which requires quoted string because of the hyphen.

**Comment by rakillen** [comment]
quoted entity names like this one should be specified as:

"!mydatasource"

**Comment by rakillen** [comment]
Leave this issue open - I'll update the README
