### ISSUE TITLE
WLS10.3.6 no NMProperties support?

### ISSUE THREAD

**Issue by acarlson1994** [oracle/weblogic-deploy-tooling#452]
NMProperties configuration is not supported in WLS 10.3.6.0.

Is there an alternative way to manage nodemanager.properties with WDT for WLS 10.3.6? Or a suggested approach?

I'm specifically trying to set SecureListener property to false.

Please let me know if there is a better place to post in the future.

**Comment by ddsharpe** [comment]
@acarlson1994 We left this issue open, as we hoped to find a better solution at some point.  Unfortunately, we have been unable to provide anything meaningful in regards to NM support in 10.3.6.  WDT is aligned with WLST and NM isn't managed by WLST a later release of WLS.  I am open to suggestions or an outside pull request in this area, but we are not likely to add a feature in this area to support configuring 10.3.6 NM at this time.
