### ISSUE TITLE
not able to run WDT tool scripts

### ISSUE THREAD

**Issue by ashok11gai** [oracle/weblogic-deploy-tooling#454]
Getting below error, looks like latest version is missing lib(lib/python/discover.py).

JAVA_HOME = /usr/java8_64
WLST_EXT_CLASSPATH = /u02/exp/weblogic-deploy-tooling-weblogic-deploy-tooling-1.4.0/installer/src/main/lib/weblogic-deploy-core.jar
CLASSPATH = /u02/exp/weblogic-deploy-tooling-weblogic-deploy-tooling-1.4.0/installer/src/main/lib/weblogic-deploy-core.jar
WLST_PROPERTIES = -Djava.util.logging.config.class=oracle.weblogic.deploy.logging.WLSDeployCustomizeLoggingConfig -Dcom.oracle.cie.script.throwException=true
/u02/app/oracle/products/fmw_soa/oracle_common/common/bin/wlst.sh /u02/exp/weblogic-deploy-tooling-weblogic-deploy-tooling-1.4.0/installer/src/main/lib/python/discover.py -oracle_home /u02/app/oracle/products/fmw_soa -domain_home /u02/app/oracle/config/config_soa/domains/soa_domain_preprd -archive_file soa_domain_preprd.zip -model_file soa_domain_preprd.yaml -domain_type WLS
Logging configuration class "oracle.weblogic.deploy.logging.WLSDeployCustomizeLoggingConfig" failed
java.lang.ClassNotFoundException: oracle.weblogic.deploy.logging.WLSDeployCustomizeLoggingConfig

Initializing WebLogic Scripting Tool (WLST) ...

Welcome to WebLogic Server Administration Scripting Shell

Type help() for help on available commands

Problem invoking WLST - java.io.FileNotFoundException: /u02/exp/weblogic-deploy-tooling-weblogic-deploy-tooling-1.4.0/installer/src/main/lib/python/discover.py

discoverDomain.sh completed but with some issues (exit code = 1)

**Comment by CarolynRountree** [comment]
It looks like you pulled down the source and are running it out of the source location. Our scripts are set up to locate the WDT files from the install image. After you build the source, take the install image from location installer->target and unzip it into some location and run against this directory. Or you can download the release from the releases page. Let me know if this fixes your problem please.

**Comment by ashok11gai** [comment]
Yeah! Thanks for quick response. yes, i'm able to execute it now. This is helpful in quickly setting up the stuff and gave us a break from writing version specific wlst scripts each time 😊
