### ISSUE TITLE
ImportError: No module named javaos

### ISSUE THREAD

**Issue by ta9846** [oracle/weblogic-deploy-tooling#458]
I tried to create a domain using the following command:

$DOMAIN_PATH/weblogic-deploy/bin/createDomain.sh -oracle_home $ORACLE_HOME -domain_parent $DOMAIN_PATH  -domain_type WLS -model_file $DOMAIN_PATH/admin-domain.yaml

But it threw the following error:

Traceback (most recent call last):
  File "/path/to/weblogic-deploy/lib/python/create.py", line 7, in <module>
    import javaos as os
ImportError: No module named javaos
Problem invoking WLST - Traceback (most recent call last):
  File "/path/to/weblogic-deploy/lib/python/create.py", line 7, in <module>
    import javaos as os
ImportError: No module named javaos

createDomain.sh completed but with some issues (exit code = 1)
Error : Domain creation failed

**Comment by ddsharpe** [comment]
@ta9846 Which version of WebLogic Server are you using (for $ORACLE_HOME)?

**Comment by ta9846** [comment]
I am using WLS 14.1.1 BETA, please let me know if it is appropriate to discuss on this version over here.

**Comment by ddsharpe** [comment]
WDT support for 14.1.1 has not been released yet.  We hope to have something this week.
