### ISSUE TITLE
CredentialEncrypted in Security configuration is not encrypted after createDomain

### ISSUE THREAD

**Issue by ddsharpe** [oracle/weblogic-deploy-tooling#471]
CredentialEncrypted in Security configuration is not encrypted after createDomain.

topology:
    Server:
        AdminServer:
            ListenPort: 7001
    SecurityConfiguration:
        CredentialEncrypted: 'some-password'

In the config.xml under the security configuration:
    <credential-encrypted>some-password</credential-encrypted>

**Comment by ddsharpe** [comment]
This is an offline WLST bug, and not a WDT bug.  See bug 30275024 in OTN.

**Comment by dborysenko** [comment]
Hi @ddsharpe 
I ran into same issue as you've describe here. But i was not able to find any info on support.oracle.com side regarding bug 30275024. Can you please provide more info on that? Is there a patch available from oracle? 
Please advise.

**Comment by ddsharpe** [comment]
@dborysenko You may need to file an SR with Oracle Support so that they will notify you when it becomes available.  Or, you can wait a few days, and check again.  Sorry, it looks like this bug was only fixed recently and hasn't made its way through all the channels, yet.
