### ISSUE TITLE
encryptModel.cmd throwing "The syntax of the command is incorrect." error

### ISSUE THREAD

**Issue by muhammadwasay** [oracle/weblogic-deploy-tooling#477]
When running the encryptModel.cmd. It is throwing  throwing "The syntax of the command is incorrect." error.
This issue is coming in 1.5.1 and 1.5.0 release.
It is working fine in 1.4.0 release

**Comment by ddsharpe** [comment]
Fixed by #481

**Comment by rakillen** [comment]
This fix has been merged to master, and will be in the next release.  If you need it sooner, you can build from master, or just make the file change in your installation directory (see the PR #481).
