### ISSUE TITLE
add version file marker to the WDT installer

### ISSUE THREAD

**Issue by ddsharpe** [oracle/weblogic-deploy-tooling#483]
Add simple text file to the installer zip that contains the tool version.  This will help with auditing Docker images that contain the WDT install.

**Comment by kaifricke** [comment]
That would be very useful, we install WDT via ansible / rpm and it would help checking the installed version. For now we have to add it manually

-Kai

**Comment by ddsharpe** [comment]
Fixed in 1.8.0 by PR #596
