### ISSUE TITLE
Is WDT  supported for FMW 12.2.1.4 version?

### ISSUE THREAD

**Issue by ashok11gai** [oracle/weblogic-deploy-tooling#500]
Hi,

Can you please confirm , if WDT is supported for SOA/OSB 12.2.1.4 versions ?

Thanks,
Ashok.

**Comment by ddsharpe** [comment]
In as much as SOA is supported on 12.2.1.3, it is supported on 12.2.1.4.  The underlying WebLogic JRF components are updated and tested on 12.2.1.4.
