### ISSUE TITLE
Is it possible to upgrade the 10.3.6 descoverd domain to 12.2.1.4 version

### ISSUE THREAD

**Issue by ashok11gai** [oracle/weblogic-deploy-tooling#507]
Is it possible to upgrade the 10.3.6 descoverd domain to 12.2.1.4 version directly with this WDT tool on a new machine?
Source:
Discoverdomain.sh
10.3.6 domain -> Discoverd  have domain_10.3.6.yaml 
Target:
Update Yaml with new domain information and run on 12.2.1.4 installed machine l.
12.2.14 -> create 

I only see that library resources needs to be updated to 11g to 12c.

Thanks,
Ashok.

**Comment by ddsharpe** [comment]
It is possible, yes.  The tool will capture the configuration that it finds in the 10.3.6 domain in a model.  That model can then be applied to any version of WebLogic to create a new domain.  The tool does not "fix" applications or libraries.  You may need to change or recompile your applications or libraries to allow for the new JDK and/or WebLogic version.

**Comment by ashok11gai** [comment]
Thank  you.  I'll test this out.
