### ISSUE TITLE
Issue with typedefs for soa 11g domain 

### ISSUE THREAD

**Issue by ashok11gai** [oracle/weblogic-deploy-tooling#508]
I’ve updated typedefs  JRF.json file in WDT/lib for SOA 11.1.1.9 version discover and createDomain purpose.
This seems to be working fine, except it is creating additional soa_server1 and causing multiple library, resources target issues in created SOA domain.

We have added below extensionTemplates in JRF.json to create SOA 11g domain.
"@@ORACLE_HOME@@/Oracle_SOA1/common/templates/applications/oracle.soa_template_11.1.1.jar",
We have only 6 servers (AdminServer, s_server1, s_server2, s_server3, s_server4, m_server,), but its creating additional soa_server1 and its corresponding jms resources and targets. This seems to be coming from oracle.soa_template_11.1.1.jar template.
How to avoid this and ensure it only creates whatever it generates in model yaml file and targets application properly?

Create domain log snippet.
####<Dec 24, 2019 3:57:33 PM> <FINER> <TargetHelper> <target_jrf_groups_to_clusters_servers> <> <ENTRY /opt/oracle/Middleware/user_projects/domains/soabpm_domain>
####<Dec 24, 2019 3:57:33 PM> <FINER> <TargetHelper> <_get_existing_server_names> <> <ENTRY>
####<Dec 24, 2019 3:57:33 PM> <FINER> <TargetHelper> <_get_existing_server_names> <> <RETURN [AdminServer, s_server1, s_server2, s_server3, s_server4, m_server, soa_server1]>

Below is the typedefs SOA definition I used to create the SOA 11g domain using WDT, is this correct approach ?
"definitions": {
        "JRF_11G" : {
            "baseTemplate": "@@WL_HOME@@/common/templates/domains/wls.jar",
            "extensionTemplates": [
                "@@ORACLE_HOME@@/oracle_common/common/templates/applications/jrf_template_11.1.1.jar",
                "@@ORACLE_HOME@@/oracle_common/common/templates/applications/oracle.jrf.ws.async_template_11.1.1.jar",
                "@@ORACLE_HOME@@/oracle_common/common/templates/applications/oracle.wsmpm_template_11.1.1.jar",
                "@@ORACLE_HOME@@/oracle_common/common/templates/applications/oracle.em_11_1_1_0_0_template.jar",
				"@@ORACLE_HOME@@/Oracle_SOA1/common/templates/applications/oracle.soa_template_11.1.1.jar",
             
            ],
			"targeting": "APPLY_JRF",
            "serverGroupsToTarget" : [ "JRF-MAN-SVR", "WSMPM-MAN-SVR", "SOA-MGD-SVRS" ],
            "customExtensionTemplates": [ ],
			"rcuSchemas": [ "MDS", ,"SOAINFRA" ,"ORASDPM" ]
        }
Thanks,
Ashok.

**Comment by rakillen** [comment]
You should be able to remove the server and other resources after the templates are applied using the delete notation in the model (WDT 1.30 and later):

https://github.com/oracle/weblogic-deploy-tooling#declaring-named-mbeans-to-delete

This should remove the deleted server from any targeting as part of create.

If there are problems doing this as part of create, it may be necessary to run updateDomain after the create, using a separate model with only the deleted elements.

**Comment by ashok11gai** [comment]
Thank you for the quick repose ! seems it solves the problem to some extent with bit more work as need to identify the resources which are getting added from templates.

As per the WDT doc note, the WDT is working on additive approach . Is there anyway we can get support for non-additive, converge-to-the-model approach from Dev team ?

**Comment by rakillen** [comment]
Original problem is resolved, tagging this as enhancement for converge-to-the-model

**Comment by robertpatrick** [comment]
No plans to implement, closing for now.
