### ISSUE TITLE
Issues with encrypted values in the domain 12.2.1.4

### ISSUE THREAD

**Issue by ashok11gai** [oracle/weblogic-deploy-tooling#518]
The passwords encrypted with encryptModel.sh script is having issues while starting the servers. When I cross checked , the encryption with wlst encrypting with {AES256} where as encryptModel.sh encrypting with {AES}.  The encryprion with WLST is working but not the  encryptModel.sh.

Java version is "1.8.0_211". 
OSB Domain is 12.2.1.4.

Encyprt script.
{AES}cTZMQy9QNnUrUVdCNGVybU0yWmg1VjgyNDFuQzVSNytuVVU9OmlsV2lZY0JoUXZIdmM1Vmo6NHZ0NkozKzdxc0E9

WLST from domain. es = encrypt('password')
{AES256}mfMRpEFhhteEYavmgpnqRpSPrCPbu6k1rQ248hove0clvXkPd2D3MJM4WpEySNX0WDpJJ7CWHHjmgVW9VPbaX2//TmpkZP6aT1YMTi+JAdbLX+qhM4KHPc+0JtLRFICs

The server is complaining with below errors for necrypted values. 

Caused By: java.lang.IllegalArgumentException: In production mode, it's not allowed to set a clear text value to the property: CredentialEncrypted of SecurityConfigurationMBean

Caused By: weblogic.security.internal.encryption.EncryptionServiceException: com.rsa.jsafe.JSAFE_PaddingException: Invalid padding.
        at weblogic.security.internal.encryption.JSafeEncryptionServiceImpl.decryptBytes(JSafeEncryptionServiceImpl.java:144)
        at weblogic.security.internal.encryption.JSafeEncryptionServiceImpl.decryptString(JSafeEncryptionServiceImpl.java:192)
        at weblogic.security.internal.encryption.ClearOrEncryptedService.decrypt(ClearOrEncryptedService.java:99)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        Truncated. see log file for complete stacktrace
Caused By: com.rsa.jsafe.JSAFE_PaddingException: Invalid padding.
        at com.rsa.jsafe.JSAFE_SymmetricCipher.decryptFinal(Unknown Source)
        at weblogic.security.internal.encryption.JSafeEncryptionServiceImpl.decryptBytes(JSafeEncryptionServiceImpl.java:129)
        at weblogic.security.internal.encryption.JSafeEncryptionServiceImpl.decryptString(JSafeEncryptionServiceImpl.java:192)
        at weblogic.security.internal.encryption.ClearOrEncryptedService.decrypt(ClearOrEncryptedService.java:99)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        Truncated. see log file for complete stacktrace

Thanks,
Ashok.

**Comment by rakillen** [comment]
Hello Ashok -

The encryptModel is used to encrypt the password fields in the model, allowing them to be decrypted in the createDomain or other WDT tools using the -use_encryption flag.

A model encrypted with the encryptModel tool cannot be used to apply encrypted passwords directly in WLST.

More information here:
https://github.com/oracle/weblogic-deploy-tooling/blob/master/site/encrypt.md

Hope that helps.

**Comment by ashok11gai** [comment]
Thanks for your reply. I'll re-try and post the update.

**Comment by AaronJaegerVA** [comment]
I am seeing the same issue when using the weblogic-deploy-tooling with the weblogic-image-tool. I have tried using the weblogic-image-tool with and without the --wdtEncryptionKey option. Can someone help me understand what I am missing?

`A MultiException has 9 exceptions.  They are:
1. weblogic.management.provider.internal.RuntimeAccessImpl$ParseException: [Management:141266]Parsing failure in config.xml: java.lang.IllegalArgumentException: In production mode, it's not allowed to set a clear text value to the property: CredentialEncrypted of SecurityConfigurationMBean.
2. java.lang.IllegalStateException: Unable to perform operation: create on weblogic.management.provider.internal.RuntimeAccessImpl
3. java.lang.IllegalStateException: Unable to perform operation: post construct on weblogic.management.provider.internal.RuntimeAccessService
4. java.lang.IllegalArgumentException: While attempting to resolve the dependencies of weblogic.t3.srvr.FinalThreadLocalService errors were found
5. java.lang.IllegalStateException: Unable to perform operation: resolve on weblogic.t3.srvr.FinalThreadLocalService
6. java.lang.IllegalArgumentException: While attempting to resolve the dependencies of weblogic.t3.srvr.BootService errors were found
7. java.lang.IllegalStateException: Unable to perform operation: resolve on weblogic.t3.srvr.BootService
8. java.lang.IllegalArgumentException: While attempting to resolve the dependencies of weblogic.server.PartitionRuntimeBuilderService errors were found
9. java.lang.IllegalStateException: Unable to perform operation: resolve on weblogic.server.PartitionRuntimeBuilderService`

**Comment by ddsharpe** [comment]
@ashok11gai and @AaronJaegerVA This issue with CredentialEncrypted turned out to be a WebLogic Scripting Tool Bug, WLST.  We filed a bug and the Oracle team delivered a patch for this issue.  See OFFLINE WLST NOT ENCRYPTING CREDENTIAL AFTER UPDATEDOMAIN() on Oracle Support under bug number 30275024.

**Comment by AaronJaegerVA** [comment]
Thank you for the response, Derek. I will check the article.

Sincerely,

Aaron Jaeger
Sr. Systems Engineer
ETS TSEI
Perspecta
Enterprise Testing Service (Station 116) (005Q)
VA OIT EPMD
727-320-1972
[Title: EPMD logo - Description: EPMD logo][Title: ETS logo - Description: ETS Flame logo]

**Comment by AaronJaegerVA** [comment]
> @ashok11gai and @AaronJaegerVA This issue with CredentialEncrypted turned out to be a WebLogic Scripting Tool Bug, WLST. We filed a bug and the Oracle team delivered a patch for this issue. See OFFLINE WLST NOT ENCRYPTING CREDENTIAL AFTER UPDATEDOMAIN() on Oracle Support under bug number 30275024.

@ddsharpe I cannot find the bug number on the Oracle support site. Will you send me a link please?

**Comment by ddsharpe** [comment]
@AaronJaegerVA and @ashok11gai it looks like the bug was published under a different number.  Please search for 30874677 instead.  Sorry, I cannot give a URL because I do not have access to the same system as you.

**Comment by AaronJaegerVA** [comment]
Thank you, Derek. I’ll find this new patch.
