### ISSUE TITLE
Copy application specific files to domain

### ISSUE THREAD

**Issue by larspusa** [oracle/weblogic-deploy-tooling#525]
Think wlsdeploy archive ZIP might be a good place for application specific files, like MQ bindings files, application property files, xml files etc used by application. Those files are not subject for domainLibraries or classpathLibraries. Files could be copied to domain_home, for example:
wlsdeploy/domainHomeFiles/mqbindings-a/.bindings
wlsdeploy/domainHomeFiles/mqbindings-b/.bindings
wlsdeploy/domainHomeFiles/properties/documentA.properties

To have those files in ZIP archive means those could easily be provided by application provider in DevOps (Jenkins) pipeline and not by infrastructure provider (providing docker wls binary image).

**Comment by ddsharpe** [comment]
@larspusa Is it sufficient to leave these files in a subdirectory of the domain, such as wlsdeploy/additionalFiles?  If so, then we can add an extract to the create domain and update that looks for that same folder in the archive, and extracts it to the domain as wlsdeploy/additionalFiles.

**Comment by larspusa** [comment]
@ddsharpe Would prefer to have it something like i specified, because if we will be starting moving applications one-by-one to docker environments we will not need to investigate if those paths are hardcoded in application or not. I can't say it is a hard requirement from us at the moment though as we still are just doing some research in this technology.
If you at the moment don't think it's a good idea to implement this we can maybe postpone this.

Another question is about .bindings files for ForeignServer. Maybe those should be included in wlsdeploy archive ZIP by default? What do you think?
