### ISSUE TITLE
 WLSDPLY-06011 Failed to get the WLST MBean type for location

### ISSUE THREAD

**Issue by prgaly** [oracle/weblogic-deploy-tooling#529]
Trying to discover a working 12.1.3 domain fails with below error -

SEVERE Messages:
        1. WLSDPLY-06011: discoverDomain failed to discover domain admin at /apps/web/weblogic/xxxx/wls-12.1.3.0/admin : Failed to get the WLST MBean type for location (model_folders = ['ServerTemplate'],  'name_tokens' = {'DOMAIN': 'xxxxx'}): Alias entry for model attribute PrefixName in folder ServerTemplate/TransactionLogJDBCStore has overlapping definitions that match WLS version 12.1.3.0.0 and WLST mode ONLINE

**Comment by prgaly** [comment]
Looks like the issue is various additional attributes (UploadDirectoryName, FileName, StagingDirectoryName etc.) in [ServerTemplate.json](https://github.com/oracle/weblogic-deploy-tooling/blob/master/core/src/main/resources/oracle/weblogic/deploy/aliases/category_modules/ServerTemplate.json#L1554) have duplicate definitions matching 12.1.3.x. 

As a test, I modified the 2nd one to 12.3.3 which doesn't exist and the domain discovery succeeded (for some definition of succeeded lol - not sure what the impact of removing the duplicate was as I haven't validated creating the domain using the archive/model.)

**Comment by CarolynRountree** [comment]
merged fix to master
