### ISSUE TITLE
Unpack fails if managed server name in model is same as directory used to unpack the domain.

### ISSUE THREAD

**Issue by prgaly** [oracle/weblogic-deploy-tooling#530]
createDomain.sh completes successfully and my model file has managed servers defined in it - so I 
 expected there to be managed instance related directory in the domain dir along with the admin server. I only saw one directory there.

So I went ahead and used pack/unpack to create the managed server directory but it fails with below error -

$ unpack.sh -domain=$HOME/WLS_current/managed1 -template=/tmp/managed-t.jar 
/apps/web/sfw/weblogic/wlserver/common/bin/unpack.sh -domain=$HOME/WLS_current/managed1 -template=/tmp/managed-t.jar       
WARNING: This is a deprecated script. Please invoke the unpack.sh script under oracle_common/common/bin.
<< read template from "/tmp/managed-t.jar"
>>  succeed: read template from "/tmp/managed-t.jar"
<< set config option DomainName to "xxxx"
>>  succeed: set config option DomainName to "xxx"
>>  validateConfig "KeyStorePasswords"
>>  succeed: validateConfig "KeyStorePasswords"
<< write Domain to "/apps/web/weblogic_svc/WLS_current/managed1"
>>  fail: write Domain to "/apps/web/weblogic_svc/WLS_current/managed1"
>>  60301: Domain name conflict.
60301: The name of the WebLogic domain and the server and cluster names within it must be unique. A server or cluster already exists with the WebLogic domain name you specified.
60301: Change the name of the domain, conflicting server or cluster.

I had to use a new managed server name and then it succeeds but that is not what I want - I need a domain dir corresponding to the already defined managed1 server.

I think the documents should clarify what the process for creating both admin and manged instances to be deployed on remote nodes (not the same node where admin is) looks like.

**Comment by prgaly** [comment]
Looks like I have to name the managed servers differently in the model than the directory name you are planning to use for their domain unpack.  I did not readily make this connection - just leaving this here so anyone else encountering the same issue will be helped.

**Comment by mriccell** [comment]
@prgaly prgaly I do not understand why you need to create a managed server directory with pack/unpack.  WDT create will at first create the AS directory but when the managed servers go to running state each one should have its own directory.  Is this not the case?

**Comment by prgaly** [comment]
@mriccell - 

> I do not understand why you need to create a managed server directory with pack/unpack. WDT create will at first create the AS directory but when the managed servers go to running state each one should have its own directory. Is this not the case?

The reason is that in our case we have admin server on one VM, and managed servers on their own VMs - which means once the domain is created on the Admin VM we have to have a way to create the managed servers on their own separate VMs. 

I did not see an example of this using WLDT - except for one bug report comment mentioning to use pack/unpack if your managed instance is on different server. What is the right way to address our scenario using WLDT?

**Comment by prgaly** [comment]
We are just going to try and run createDomain on all managed server VMs and just start managed instances there - we will have to clean up the admin server specific things from the domain dir intended for the managed instances I guess?

It would be better to have the createDomain script do it - perhaps with a switch for creating managed instance on remote server using ssh?
