### ISSUE TITLE
Considerations for Jolt and WebLogic Tuxedo Connector definitions?

### ISSUE THREAD

**Issue by gthomas01** [oracle/weblogic-deploy-tooling#532]
It appears that wdt does not support the creation of Jolt pools or wtc servers.  Has there been any thought to add this in the future.   We are very interested in this tool but we currently connect to Tuxedo with about 50% of our WebLogic domains using wtc.  It seems we would need to continue to maintain wlst externally to update configurations once in place.

**Comment by CarolynRountree** [comment]
Adding support for JoltConnectionPools and WTCServers MBeans. Is that sufficient? Also, what version is your WebLogicServer?

**Comment by gthomas01** [comment]
wow! yes that would be sufficient.   Most of our stuff is 12.2.1.3, 12.2.1.4.

**Comment by CarolynRountree** [comment]
Supported in 1.17.1
