### ISSUE TITLE
Error in discoverDomain tool in WLST Online mode

### ISSUE THREAD

**Issue by luizooliveira** [oracle/weblogic-deploy-tooling#539]
Hello,

When I try to use the online mode with discoverDomain tool, I'm getting some errors misclassified as INFO, as follows:

`####<Feb 12, 2020 5:23:40 PM> <INFO> <Discoverer> <_add_to_dictionary> <WLSDPLY-06106> <Unable to add MemoryBufferFilter from location /Log/WLS_PSTN_INVENTORY_QA to the model : The wlst attribute MemoryBufferFilter is not defined for the model folder /Log>
####<Feb 12, 2020 5:23:41 PM> <INFO> <Discoverer> <_add_to_dictionary> <WLSDPLY-06106> <Unable to add ServerFailureTrigger from location /Clusters/WLS_PSTN_INVENTORY_QA_CLUSTER/OverloadProtection/WLS_PSTN_INVENTORY_QA_CLUSTER to the model : The wlst attribute ServerFailureTrigger is not defined for the model folder /Cluster/OverloadProtection>
####<Feb 12, 2020 5:23:41 PM> <INFO> <Discoverer> <_add_to_dictionary> <WLSDPLY-06106> <Unable to add JTAMigratableTarget from location /Servers/WLS_PSTN_INVENTORY_QA_Admin to the model : The wlst attribute JTAMigratableTarget is not defined for the model folder /Server>
####<Feb 12, 2020 5:23:43 PM> <INFO> <Discoverer> <_add_to_dictionary> <WLSDPLY-06106> <Unable to add MemoryBufferFilter from location /Servers/WLS_PSTN_INVENTORY_QA_Admin/Log/WLS_PSTN_INVENTORY_QA_Admin to the model : The wlst attribute MemoryBufferFilter is not defined for the model folder /Server/Log>
####<Feb 12, 2020 5:23:43 PM> <INFO> <Discoverer> <_add_to_dictionary> <WLSDPLY-06106> <Unable to add ServerFailureTrigger from location /Servers/WLS_PSTN_INVENTORY_QA_Admin/OverloadProtection/WLS_PSTN_INVENTORY_QA_Admin to the model : The wlst attribute ServerFailureTrigger is not defined for the model folder /Server/OverloadProtection>
####<Feb 12, 2020 5:23:48 PM> <INFO> <Discoverer> <_add_to_dictionary> <WLSDPLY-06106> <Unable to add MemoryBufferFilter from location /Servers/WLS_PSTN_INVENTORY_QA_Srv01/Log/WLS_PSTN_INVENTORY_QA_Srv01 to the model : The wlst attribute MemoryBufferFilter is not defined for the model folder /Server/Log>
####<Feb 12, 2020 5:23:48 PM> <INFO> <Discoverer> <_add_to_dictionary> <WLSDPLY-06106> <Unable to add ServerFailureTrigger from location /Servers/WLS_PSTN_INVENTORY_QA_Srv01/OverloadProtection/WLS_PSTN_INVENTORY_QA_Srv01 to the model : The wlst attribute ServerFailureTrigger is not defined for the model folder /Server/OverloadProtection>
####<Feb 12, 2020 5:23:52 PM> <INFO> <Discoverer> <_add_to_dictionary> <WLSDPLY-06106> <Unable to add MemoryBufferFilter from location /Servers/WLS_PSTN_INVENTORY_QA_Srv02/Log/WLS_PSTN_INVENTORY_QA_Srv02 to the model : The wlst attribute MemoryBufferFilter is not defined for the model folder /Server/Log>
####<Feb 12, 2020 5:23:52 PM> <INFO> <Discoverer> <_add_to_dictionary> <WLSDPLY-06106> <Unable to add ServerFailureTrigger from location /Servers/WLS_PSTN_INVENTORY_QA_Srv02/OverloadProtection/WLS_PSTN_INVENTORY_QA_Srv02 to the model : The wlst attribute ServerFailureTrigger is not defined for the model folder /Server/OverloadProtection>
####<Feb 12, 2020 5:23:56 PM> <INFO> <Discoverer> <_add_to_dictionary> <WLSDPLY-06106> <Unable to add PasswordValidatorTypes from location /SecurityConfiguration/WLS_PSTN_INVENTORY_QA/Realms/myrealm to the model : The wlst attribute PasswordValidatorTypes is not defined for the model folder /SecurityConfiguration/Realm>
`

In Offline mode the errors doesn't occur, but I can't get the security information.

Attached full log.

Regards.
[discoverDomain.log](https://github.com/oracle/weblogic-deploy-tooling/files/4194919/discoverDomain.log)
[System.out.log](https://github.com/oracle/weblogic-deploy-tooling/files/4194928/System.out.log)

**Comment by CarolynRountree** [comment]
Could you provide the discovered model please?

**Comment by ddsharpe** [comment]
@luizooliveira the logs were fairly long.  Could you run your test again with the current release?  We believe that many of these should be fixed now.

**Comment by ddsharpe** [comment]
@luizooliveira closing this issue due to no response.  Please re-open if issue still exists.
