### ISSUE TITLE
enhance model to support inline-ing file contents 

### ISSUE THREAD

**Issue by ddsharpe** [oracle/weblogic-deploy-tooling#54]
I need a way to inline kubernetes secrets (from a file in the pod) into the model during a create operation.  For example, the file, "my-pass.txt", contains a simple string "welcome1".  Can we have a macro that lets me identify that file in the domain model yaml/json and inlines the contents during create?

**Comment by tbarnes-us** [comment]
1) Also, can the 'filename macro' provide a way to separately specify a global parameter that'll be used as the filename prefix if the filename is specified as a relative path?    

2) I'm just brain-storming here, but if "/" is currently an illegal character in a macro, then it might be a reasonable solution to assume that any macro name with a '/' in it is a filename.
