### ISSUE TITLE
Encrypt Model does not support multiple model files

### ISSUE THREAD

**Issue by Techinica** [oracle/weblogic-deploy-tooling#547]
As the title states, the current implementation of the encrypt model function doesn't support multiple model files in the same manner that the create and update domain functions do. Thus currently such models cannot use the function to encrypt a separate properties file.

Concatenating all the files to a single file also does not work as the resulting topology is not correct, resulting in most values that should be encrypted being skipped.

Current Behaviour:

**encryptModel.sh -oracle_home /home/user/oracle -model_file model1.yaml,model2.yaml -variable_file model.variables**
`<encryptModel argument processing failed: encryptModel requires the model file argument model1.yaml,model2.yaml to be an existing file:`

Expected Behaviour:

The functionality should be able to read multiple model files, build the appropriate topology as per create/update functions, then update the specified variable_file correctly.

**Comment by ddsharpe** [comment]
@Techinica Why is there an issue with running encrypt once for each model file?  Is there a technical reason this does not work? 

If we created a solution that would encrypt each model in a list as you describe, the solution depends on the answers to these questions.  Please let us know.

**Comment by Techinica** [comment]
@ddsharpe if a single property exists in both model files, doing this "double-encrypts" the property in the variables file, which then doesn't work to create a domain.

**Comment by ddsharpe** [comment]
@Techinica Thanks, we will do that and try to get it in the next release.

**Comment by rakillen** [comment]
Fixed with #647 and will be in the next release
