### ISSUE TITLE
RCU dbUser

### ISSUE THREAD

**Issue by dborysenko** [oracle/weblogic-deploy-tooling#565]
Hi,
Is it possible to set RCU dbUser in WDT? Looks like WDT always use default SYS user. Snippet from RCURunner.java:
```java
private static final String DB_USER = "SYS";
```
We'd like to have RCU admin user name as a variable, with default set to SYS.

**Comment by ddsharpe** [comment]
User should be provided in the dbinfo section of the model, default is SYS.  Target feature to next release.

**Comment by jshum2479** [comment]
We can add option to both command line and also RCUDbInfo section to take different user `rcu_db_user` .  This user, however must have SYSDBA privilege.
