### ISSUE TITLE
libOVD keystore

### ISSUE THREAD

**Issue by dborysenko** [oracle/weblogic-deploy-tooling#566]
Hi Team,
We've discovered that if one wants to have weblogic 12c domain (with Oracle Service Bus and/or Oracle SOA suite) talk to ldapS authentication provider , the one should setup libOVD keystore (procedure is described in Doc ID 1465228.1). I wonder if it is something that can be implemented in WDT? So libOVD keystore configuration been done during domain creation or post creation step?

**Comment by ddsharpe** [comment]
I have been unable to get traction with the SOA/OSB development team.  Without insight or review from people that know more about libOVD configuration, I am very reluctant to release a feature in this area.  For now, I am archiving this issue until such a time that the SOA/OSB team has time to discuss WDT.
