### ISSUE TITLE
Application roles

### ISSUE THREAD

**Issue by dborysenko** [oracle/weblogic-deploy-tooling#567]
Hi Team,
Do you have any plans to implement application role mappings like you did with WLSRoles? 
WLST example:
```python
grantAppRole(appStripe="soa-infra", appRoleName="SOAAdmin",principalClass="weblogic.security.principal.WLSGroupImpl", principalName="myAdminGroup")
```

**Comment by ddsharpe** [comment]
There are not any plans to implement this, currently.  What is the challenge for you now without this feature?

**Comment by dborysenko** [comment]
Hi @ddsharpe ,
There is no way to create domain with application roles assigned to LDAP groups. As example to be able to access SOA admin console the one has to have SOAAdmin application role.

**Comment by pwninja** [comment]
Voting up for this feature

**Comment by robertpatrick** [comment]
Only works online so no plans to implement.  Closing for now
