### ISSUE TITLE
Online update for JRF fails when a new datasource is added

### ISSUE THREAD

**Issue by rakillen** [oracle/weblogic-deploy-tooling#568]
```
WLSDPLY-09015: updateDomain deployment failed: Unable to save current changes and close the domain session : wlst.save() failed : Error occurred while performing save : Save failed: There are some invalid changes which need to be resolved. : weblogic.descriptor.DescriptorValidateException: The following failures occurred:
-- JDBCDataSource: Name cannot be null
```

Need to set JDBCSystemResource / JdbcResource / Name when creating placeholders.

**Comment by vkwjope** [comment]
I am facing a similar issue, i am using WDT version 1.9.5. Can you please share a sample .yaml file for reference ?

**Comment by vkwjope** [comment]
This is a sample of the yaml file i am using for creating datasource using updateDomain.sh in online mode.

**JDBCSystemResource:
        FLEXTEST.WORLD:
            Target: '@@PROP:target.server@@'
            JdbcResource:
                JDBCDataSourceParams:
                    JNDIName: FLEXTEST.WORLD
                JDBCDriverParams:
                    DriverName: oracle.jdbc.OracleDriver
                    URL: 'jdbc:oracle:thin:@//@@PROP:db.host.name@@:@@PROP:db.port@@/@@PROP:db.name@@'
                    PasswordEncrypted: '{AES}eG5kczRmTitKclRYL0I4bjlOcHhQblRaWkNxc2RKdGhVTEhWY0E9PTpSK2pIakhNczdNNGY5UXhUOnpFOVRKZWJsR0dFPQ=='
                    Properties:
                        user:
                            Value: '@@PROP:ds.user.name@@'
                JDBCConnectionPoolParams:
                    ConnectionReserveTimeoutSeconds: '@@PROP:jdbc.connectionpool.conn.reserve.timeout.seconds@@'
                    TestFrequencySeconds: '@@PROP:jdbc.connectionpool.test.freq.seconds@@'
                    InactiveConnectionTimeoutSeconds: '@@PROP:jdbc.connectionpool.inactive.conn.timeout.seconds@@'
                    InitialCapacity: '@@PROP:jdbc.connectionpool.initial.capacity@@'
                    MaxCapacity: '@@PROP:jdbc.connectionpool.max.capacity@@'
                    CapacityIncrement: '@@PROP:jdbc.connectionpool.capacity.increment@@'
                    ShrinkFrequencySeconds: '@@PROP:jdbc.connectionpool.shrink.freq.seconds@@'
                    TestConnectionsOnReserve: '@@PROP:jdbc.connectionpool.test.conn.on.reserve@@'**

**Comment by rakillen** [comment]
vkwjope -

I was able to update in online mode with the latest WDT using your supplied JDBCSystemResource section (replacing all the @@PROP variables, and using an unencrypted value for PasswordEncrypted). What error message are you getting?

**Comment by vkwjope** [comment]
rakillen -

I was creating multiple datasources at a time in using .yaml file , The above mentioned resource was successful  but the below datasource creation is getting failed in online mode. The same works seamlessly in offline mode.

**Comment by vkwjope** [comment]
resources:
    JDBCSystemResource:
        jdbc/fcjdevDS_ASYNC:
            Target: '@@PROP:target.server@@'
            JdbcResource:
                JDBCDataSourceParams:
                    JNDIName: jdbc/fcjdevDS_ASYNC
                JDBCDriverParams:
                    DriverName: oracle.jdbc.OracleDriver
                    URL: 'jdbc:oracle:thin:@//@@PROP:db.host.name@@:@@PROP:db.port@@/@@PROP:db.name@@'
                    PasswordEncrypted: '@@PROP:ds.user.password@@'
                    Properties:
                        user:
                            Value: '@@PROP:ds.user.name@@'
                JDBCConnectionPoolParams:
                    ConnectionReserveTimeoutSeconds: '@@PROP:jdbc.connectionpool.conn.reserve.timeout.seconds@@'
                    TestFrequencySeconds: '@@PROP:jdbc.connectionpool.test.freq.seconds@@'
                    InactiveConnectionTimeoutSeconds: '@@PROP:jdbc.connectionpool.inactive.conn.timeout.seconds@@'
                    InitialCapacity: '@@PROP:jdbc.connectionpool.initial.capacity@@'
                    MaxCapacity: '@@PROP:jdbc.connectionpool.max.capacity@@'
                    CapacityIncrement: '@@PROP:jdbc.connectionpool.capacity.increment@@'
                    ShrinkFrequencySeconds: '@@PROP:jdbc.connectionpool.shrink.freq.seconds@@'
                    TestConnectionsOnReserve: '@@PROP:jdbc.connectionpool.test.conn.on.reserve@@'

**Comment by vkwjope** [comment]
Error in online mode :

**1. WLSDPLY-09015: updateDomain deployment failed: save() failed : Error occurred while performing save : Save failed: There are some invalid changes which need to be resolved. : weblogic.descriptor.DescriptorValidateException: The following failures occurred:
-- JDBCDataSource: Name cannot be null**

**Comment by rakillen** [comment]
vkwjope -
I was able to deploy the second model as well with WDT 1.9.5 in online mode. The fix that resolved the original problem has been in place since WDT 1.7.2, and seems to be included in 1.9.5. Can you post the last several lines of your console output, such as:
```
####<Nov 6, 2020 9:52:24 AM> <INFO> <DatasourceDeployer> <_add_named_elements> <WLSDPLY-09606> <Adding Properties user to JDBCDriverParams>
####<Nov 6, 2020 9:52:24 AM> <INFO> <DatasourceDeployer> <_add_model_elements> <WLSDPLY-09603> <Updating JDBCConnectionPoolParams for JdbcResource>

Issue Log for updateDomain version 1.9.5 running WebLogic version 12.2.1.3.0 online mode:

Total:       WARNING :     0    SEVERE :     0

updateDomain.cmd completed successfully but the domain requires a restart for the changes to take effect (exit code = 103)
```
I'd also like to see your command-line options, to see if I can reproduce the problem. Thanks.

**Comment by vkwjope** [comment]
rakillen -

Sincere apologies for the delayed response. Was held up with something

**Comment by vkwjope** [comment]
The .yaml file is as below

**Comment by vkwjope** [comment]
resources:
    JDBCSystemResource:
        jdbc/fcjdevDSBranch:
            Target: '@@PROP:target.server@@'
            JdbcResource:
                JDBCDataSourceParams:
                    JNDIName: jdbc/fcjdevDSBranch
                JDBCDriverParams:
                    DriverName: oracle.jdbc.xa.client.OracleXADataSource
                    URL: 'jdbc:oracle:thin:@//@@PROP:db.host.name@@:@@PROP:db.port@@/@@PROP:db.name@@'
                    PasswordEncrypted: '@@PROP:ds.user.password@@'
                    Properties:
                        user:
                            Value: '@@PROP:ds.user.name@@'
                JDBCConnectionPoolParams:
                    ConnectionReserveTimeoutSeconds: '@@PROP:jdbc.connectionpool.conn.reserve.timeout.seconds@@'
                    TestFrequencySeconds: '@@PROP:jdbc.connectionpool.test.freq.seconds@@'
                    InactiveConnectionTimeoutSeconds: '@@PROP:jdbc.connectionpool.inactive.conn.timeout.seconds@@'
                    InitialCapacity: '@@PROP:jdbc.connectionpool.initial.capacity@@'
                    MaxCapacity: '@@PROP:jdbc.connectionpool.max.capacity@@'
                    CapacityIncrement: '@@PROP:jdbc.connectionpool.capacity.increment@@'
                    ShrinkFrequencySeconds: '@@PROP:jdbc.connectionpool.shrink.freq.seconds@@'
                    TestConnectionsOnReserve: '@@PROP:jdbc.connectionpool.test.conn.on.reserve@@'

**Comment by vkwjope** [comment]
Error logs:

####<Nov 12, 2020 5:35:18 PM> <SEVERE> <update> <main> <WLSDPLY-09015> <updateDomain deployment failed: save() failed : Error occurred while performing save : Save failed: There are some invalid changes which need to be resolved. : weblogic.descriptor.DescriptorValidateException: The following failures occurred:
-- JDBCDataSource: Name cannot be null

Use dumpStack() to view the full stacktrace :>

Issue Log for updateDomain version 1.9.5 running WebLogic version 12.2.1.4.0 online mode:

SEVERE Messages:

        1. WLSDPLY-09015: updateDomain deployment failed: save() failed : Error occurred while performing save : Save failed: There are some invalid changes which need to be resolved. : weblogic.descriptor.DescriptorValidateException: The following failures occurred:
-- JDBCDataSource: Name cannot be null

Use dumpStack() to view the full stacktrace :

Total:       WARNING :     0    SEVERE :     1

updateDomain.sh failed (exit code = 2)

**Comment by vkwjope** [comment]
Command used:

**$WDT_HOME/updateDomain.sh -oracle_home $ORACLE_HOME -domain_type WLS -domain_home $DOMAIN_HOME -model_file $SCRIPTS_HOME/$DEPLOY_CONFIG_FILE -variable_file $SCRIPTS_HOME/$DEPLOY_PROP_FILE  -admin_url t3://<actual-server-name>:7001 -admin_user weblogic**

**Comment by vkwjope** [comment]
Command used:

$WDT_HOME/updateDomain.sh -oracle_home $ORACLE_HOME -domain_type WLS -domain_home $DOMAIN_HOME -model_file $SCRIPTS_HOME/$DEPLOY_CONFIG_FILE -variable_file $SCRIPTS_HOME/$DEPLOY_PROP_FILE  -admin_url t3://wfggg:7001 -admin_user weblogic

**Comment by rakillen** [comment]
vkwjope -
I've switched my WebLogic version to match, using the same command line, and using a separate properties file, and the domain is still updating online correctly. There are a couple of possibilities I can think of:

- despite the version 1.9.5 appearing in the console output, there could be some out-of-date Jython class files (such as abc.$py.class) under your wlsdeploy install directory. This can happen if WDT is installed in a directory where a previous version was installed. Can you re-install to an empty directory to check this possibility? You might want the newer WDT version, 1.9.7.

- are there any other JDBCSystemResource entries in your domain before the online updateDomain is run? Maybe an existing one is missing the Name attribute and causing the save() failure. Is your pre-update domain built with createDomain, or some other method?

**Comment by vkwjope** [comment]
rakillen -

* I have tested with latest WDT release 1.9.7 
* I am creating the domain using createDomain.sh only

**Comment by vkwjope** [comment]
PFB my latest observations.

* I am trying to create multiple data sources at a time using .yaml config file using online mode.
* The issue is occurring when there are 2 data sources with almost similar names but not exactly similar. 
For ex: 
DS name 1 - jdbc/fcjdevDS
DS name 2 - jdbc/fcjdevDSBranch

We get an error in this case

**Comment by vkwjope** [comment]
**The yaml file for the same.**

resources:
    JDBCSystemResource:
        jdbc/fcjdevDS:
            Target: '@@PROP:target.server@@'
            JdbcResource:
                JDBCDataSourceParams:
                    JNDIName: jdbc/fcjdevDS
                JDBCDriverParams:
                    DriverName: oracle.jdbc.OracleDriver
                    URL: 'jdbc:oracle:thin:@//@@PROP:db.host.name@@:@@PROP:db.port@@/@@PROP:db.name@@'
                    PasswordEncrypted: '@@PROP:ds.user.password@@'
                    Properties:
                        user:
                            Value: '@@PROP:ds.user.name@@'
                JDBCConnectionPoolParams:
                    ConnectionReserveTimeoutSeconds: '@@PROP:jdbc.connectionpool.conn.reserve.timeout.seconds@@'
                    TestFrequencySeconds: '@@PROP:jdbc.connectionpool.test.freq.seconds@@'
                    InactiveConnectionTimeoutSeconds: '@@PROP:jdbc.connectionpool.inactive.conn.timeout.seconds@@'
                    InitialCapacity: '@@PROP:jdbc.connectionpool.initial.capacity@@'
                    MaxCapacity: '@@PROP:jdbc.connectionpool.max.capacity@@'
                    CapacityIncrement: '@@PROP:jdbc.connectionpool.capacity.increment@@'
                    ShrinkFrequencySeconds: '@@PROP:jdbc.connectionpool.shrink.freq.seconds@@'
                    TestConnectionsOnReserve: '@@PROP:jdbc.connectionpool.test.conn.on.reserve@@'
        jdbc/fcjdevDSBranch:
            Target: '@@PROP:target.server@@'
            JdbcResource:
                JDBCDataSourceParams:
                    JNDIName: jdbc/fcjdevDSBranch
                JDBCDriverParams:
                    DriverName: oracle.jdbc.xa.client.OracleXADataSource
                    URL: 'jdbc:oracle:thin:@//@@PROP:db.host.name@@:@@PROP:db.port@@/@@PROP:db.name@@'
                    PasswordEncrypted: '@@PROP:ds.user.password@@'
                    Properties:
                        user:
                            Value: '@@PROP:ds.user.name@@'
                JDBCConnectionPoolParams:
                    ConnectionReserveTimeoutSeconds: '@@PROP:jdbc.connectionpool.conn.reserve.timeout.seconds@@'
                    TestFrequencySeconds: '@@PROP:jdbc.connectionpool.test.freq.seconds@@'
                    InactiveConnectionTimeoutSeconds: '@@PROP:jdbc.connectionpool.inactive.conn.timeout.seconds@@'
                    InitialCapacity: '@@PROP:jdbc.connectionpool.initial.capacity@@'
                    MaxCapacity: '@@PROP:jdbc.connectionpool.max.capacity@@'
                    CapacityIncrement: '@@PROP:jdbc.connectionpool.capacity.increment@@'
                    ShrinkFrequencySeconds: '@@PROP:jdbc.connectionpool.shrink.freq.seconds@@'
                    TestConnectionsOnReserve: '@@PROP:jdbc.connectionpool.test.conn.on.reserve@@'

**Comment by vkwjope** [comment]
Error log:

####<Nov 13, 2020 4:02:46 PM> <SEVERE> <update> <main> <WLSDPLY-09015> <updateDomain deployment failed: save() failed : Error occurred while performing save : Save failed: There are some invalid changes which need to be resolved. : weblogic.descriptor.DescriptorValidateException: The following failures occurred:
-- JDBCDataSource: Name cannot be null

Use dumpStack() to view the full stacktrace :>

Issue Log for updateDomain version 1.9.7 running WebLogic version 12.2.1.4.0 online mode:

SEVERE Messages:

        1. WLSDPLY-09015: updateDomain deployment failed: save() failed : Error occurred while performing save : Save failed: There are some invalid changes which need to be resolved. : weblogic.descriptor.DescriptorValidateException: The following failures occurred:
-- JDBCDataSource: Name cannot be null

Use dumpStack() to view the full stacktrace :

Total:       WARNING :     0    SEVERE :     1

updateDomain.sh failed (exit code = 2)

**Comment by vkwjope** [comment]
For testing purposes, I changed one of the DS name to a different name **jdbc/testDS** , it worked fine . It didn't throw any error and data sources were also created successfully.

Ex:
DS name 1 - **jdbc/testDS**
DS name 2 - jdbc/fcjdevDSBranch

**Comment by vkwjope** [comment]
Please find below the working yaml config file after name change

**Comment by vkwjope** [comment]
resources:
    JDBCSystemResource:
        jdbc/testDS:
            Target: '@@PROP:target.server@@'
            JdbcResource:
                JDBCDataSourceParams:
                    JNDIName: jdbc/testDS
                JDBCDriverParams:
                    DriverName: oracle.jdbc.OracleDriver
                    URL: 'jdbc:oracle:thin:@//@@PROP:db.host.name@@:@@PROP:db.port@@/@@PROP:db.name@@'
                    PasswordEncrypted: '@@PROP:ds.user.password@@'
                    Properties:
                        user:
                            Value: '@@PROP:ds.user.name@@'
                JDBCConnectionPoolParams:
                    ConnectionReserveTimeoutSeconds: '@@PROP:jdbc.connectionpool.conn.reserve.timeout.seconds@@'
                    TestFrequencySeconds: '@@PROP:jdbc.connectionpool.test.freq.seconds@@'
                    InactiveConnectionTimeoutSeconds: '@@PROP:jdbc.connectionpool.inactive.conn.timeout.seconds@@'
                    InitialCapacity: '@@PROP:jdbc.connectionpool.initial.capacity@@'
                    MaxCapacity: '@@PROP:jdbc.connectionpool.max.capacity@@'
                    CapacityIncrement: '@@PROP:jdbc.connectionpool.capacity.increment@@'
                    ShrinkFrequencySeconds: '@@PROP:jdbc.connectionpool.shrink.freq.seconds@@'
                    TestConnectionsOnReserve: '@@PROP:jdbc.connectionpool.test.conn.on.reserve@@'
        jdbc/fcjdevDSBranch:
            Target: '@@PROP:target.server@@'
            JdbcResource:
                JDBCDataSourceParams:
                    JNDIName: jdbc/fcjdevDSBranch
                JDBCDriverParams:
                    DriverName: oracle.jdbc.xa.client.OracleXADataSource
                    URL: 'jdbc:oracle:thin:@//@@PROP:db.host.name@@:@@PROP:db.port@@/@@PROP:db.name@@'
                    PasswordEncrypted: '@@PROP:ds.user.password@@'
                    Properties:
                        user:
                            Value: '@@PROP:ds.user.name@@'
                JDBCConnectionPoolParams:
                    ConnectionReserveTimeoutSeconds: '@@PROP:jdbc.connectionpool.conn.reserve.timeout.seconds@@'
                    TestFrequencySeconds: '@@PROP:jdbc.connectionpool.test.freq.seconds@@'
                    InactiveConnectionTimeoutSeconds: '@@PROP:jdbc.connectionpool.inactive.conn.timeout.seconds@@'
                    InitialCapacity: '@@PROP:jdbc.connectionpool.initial.capacity@@'
                    MaxCapacity: '@@PROP:jdbc.connectionpool.max.capacity@@'
                    CapacityIncrement: '@@PROP:jdbc.connectionpool.capacity.increment@@'
                    ShrinkFrequencySeconds: '@@PROP:jdbc.connectionpool.shrink.freq.seconds@@'
                    TestConnectionsOnReserve: '@@PROP:jdbc.connectionpool.test.conn.on.reserve@@'

**Comment by rakillen** [comment]
vkwjope -
Thanks for posting these models. I was able to reproduce the problem, and your work-around. After trying some other combinations, the problem seems to occur when:
- there are slashes in the JDBCSystemResource names, and
- one name is a shorter version of the other

We've created a WebLogic bug describing this scenario, and a patch may be available at a future date. Unless your domain requires these exact JDBCSystemResource names, I recommend changing them in your model to avoid this conflict.

You can keep your existing JNDIName values (such as jdbc/fcjdevDS), only the JDBCSystemResource object names need to change.
Hope this helps.

**Comment by vkwjope** [comment]
rakillen -
Thank you for the update. Could you also share the weblogic bug id or link , for tracking purpose.

**Comment by rakillen** [comment]
The WebLogic bug number is 32153389.

**Comment by ddsharpe** [comment]
@vkwjope The bug fix is done in WebLogic Server.  You will need to file a support case and request the patch for the version(s) of WebLogic Server that you need the patch.
