### ISSUE TITLE
ErrorDestination of a Queue is not retrieved by discover functionality when it is run online

### ISSUE THREAD

**Issue by anilbuyukarslan** [oracle/weblogic-deploy-tooling#583]
When I run discoverDomain.sh offline, I see that the UniformDistributedQueue is correctly discovered but when I run it online, all attributes except ErrorDestination is discovered. I used weblogic deploy tooling version 1.7.3.

**Comment by CarolynRountree** [comment]
Recreated this issue.

**Comment by CarolynRountree** [comment]
Fixed in 1.8.0
