### ISSUE TITLE
WDT Model Diff Tool

### ISSUE THREAD

**Issue by ddsharpe** [oracle/weblogic-deploy-tooling#584]
To assist with change management processes, we need to be able to compare models (what changed) where order of objects is irrelevant.  Users need to be able to see what was changed when reviewing another developer/administrator's changes.

Servers:
  managed-1:
  managed-2:

should equate to the same (but out of order):

Servers:
  managed-2:
  managed-1:

**Comment by jshum2479** [comment]
There is a new tool now for comparing models.  Compare Model Tool.  

https://github.com/oracle/weblogic-deploy-tooling/blob/master/site/compare.md
