### ISSUE TITLE
Ability to set ImplicitBeanDiscoveryEnabled

### ISSUE THREAD

**Issue by anilbuyukarslan** [oracle/weblogic-deploy-tooling#599]
Hi,

I see that WDT does not discover CdiContainer settings and it does not mention it in source code. We have to set ImplicitBeanDiscoveryEnabled to 0 in CdiContainer folder in Domain.

Is there a way to achieve this or does it require a change by your side?

**Comment by ddsharpe** [comment]
@anilbuyukarslan I am not familiar with this container.  My first guess is that it will require a change in WDT.  @CarolynRountree can you look into this bean?

**Comment by CarolynRountree** [comment]
CDIContainer has not been implemented. We will implement the MBean and its attribute for this issue.

**Comment by anilbuyukarslan** [comment]
Thank you @ddsharpe and @CarolynRountree !

**Comment by ddsharpe** [comment]
https://docs.oracle.com/middleware/1221/wls/WLPRG/cdi.htm#WLPRG578
