### ISSUE TITLE
Error in discoverDomain tool when domain type is soaessosb (created by WKO)

### ISSUE THREAD

**Issue by GerthH** [oracle/weblogic-deploy-tooling#629]
Trying to discover a domain of type soaessosb (Weblogic Kubernetes Operator domain type for SOA, ESS and OSB using:
/u01/weblogic-deploy/bin/discoverDomain.sh -oracle_home /u01/oracle -domain_home /u01/oracle/user_projects/domains/domaind -archive_file /u01/wdt-models/domaind/version/0/domain.zip -model_file /u01/wdt-models/domaind/version/0/domain.yaml

throws the following error:
...
####<May 19, 2020 8:34:26 AM> <INFO> <DeploymentsDiscoverer> <get_applications> <WLSDPLY-06392> <Adding Application Service Bus Test Framework>
####<May 19, 2020 8:34:26 AM> <INFO> <DeploymentsDiscoverer> <add_application_to_archive> <WLSDPLY-06393> <Will not add application Service Bus Test Framework from Oracle installation directory to archive>
####<May 19, 2020 8:34:26 AM> <INFO> <MultiTenantDiscoverer> <discover> <WLSDPLY-06700> <Discover Multi-tenant>
####<May 19, 2020 8:34:26 AM> <INFO> <MultiTenantTopologyDiscoverer> <discover> <WLSDPLY-06709> <Discover Multi-tenant Topology>
####<May 19, 2020 8:34:26 AM> <INFO> <MultiTenantResourcesDiscoverer> <discover> <WLSDPLY-06707> <Discover Multi-tenant Resources>
####<May 19, 2020 8:34:26 AM> <INFO> <MultiTenantDiscoverer> <get_resource_group_templates> <WLSDPLY-06701> <Discovering 6 Resource Group Templates>
####<May 19, 2020 8:34:26 AM> <INFO> <MultiTenantDiscoverer> <get_resource_group_templates> <WLSDPLY-06702> <Adding OSBResourceGroupTemplate to Resource Group Templates>
####<May 19, 2020 8:34:26 AM> <SEVERE> <discover> <main> <WLSDPLY-06011> <discoverDomain failed to discover domain domaind at /u01/oracle/user_projects/domains/domaind : Failed to get the WLST MBean type for location (model_folders = ['ResourceGroupTempla\
te', 'SystemComponent'],  'name_tokens' = {'DOMAIN': 'domaind','RESOURCEGROUPTEMPLATE': 'OSBResourceGroupTemplate'}): Alias folder SystemComponent does not exist at path /ResourceGroupTemplate>

Issue Log for discoverDomain version 1.8.1 running WebLogic version 12.2.1.3.0 offline mode:

SEVERE Messages:

	1. WLSDPLY-06011: discoverDomain failed to discover domain domaind at /u01/oracle/user_projects/domains/domaind : Failed to get the WLST MBean type for location (model_folders = ['ResourceGroupTemplate', 'SystemComponent'],  'name_tokens' = {'DOMA\
IN': 'domaind','RESOURCEGROUPTEMPLATE': 'OSBResourceGroupTemplate'}): Alias folder SystemComponent does not exist at path /ResourceGroupTemplate

Total:       WARNING :     0    SEVERE :     1

discoverDomain.sh failed (exit code = 2)

**Comment by dpenson** [comment]
I also have this issue trying to use the tool against a SOA cloud service 12.2.1.3 domain.
[weblogic-deploy-debug.zip](https://github.com/oracle/weblogic-deploy-tooling/files/4680658/weblogic-deploy-debug.zip)

**Comment by ddsharpe** [comment]
Fixed by #632
