### ISSUE TITLE
Need ability to deploy to absolute path

### ISSUE THREAD

**Issue by roeq** [oracle/weblogic-deploy-tooling#631]
Would be helpful to be able to deploy to a common location.  I create a archive.zip which contains

$ jar tvf archive.zip 
     0 Wed May 20 17:01:02 EDT 2020 META-INF/
    69 Wed May 20 17:01:02 EDT 2020 META-INF/MANIFEST.MF
     0 Wed May 20 17:01:00 EDT 2020 /apps/
     0 Wed May 20 17:00:12 EDT 2020 /apps/simple/
  1257 Wed May 20 17:00:12 EDT 2020 /apps/simple/simple-app.war

In my deploy model I use a PATH property token

appDeployments:
    Application:
        # Quote needed because of hyphen in string
        'simple-app':
            SourcePath: '@@PROP:PATH@@'
            Target: '@@PROP:SERVER_NAME@@'
            ModuleType: war
            StagingMode: stage
            PlanStagingMode: nostage

vars =
SERVER_NAME=AdminServer
PATH=/apps/simple/simple-app.war

WLSDPLY-09015: deployApps deployment failed: Source path for Application simple-app not found in any archive: /apps/simple/simple-app.war

Why restrict the deployment to wlsdeploy/applications under the domain_home

**Comment by rakillen** [comment]
This works in offline deploy, but I get the same error using online deploy. I'll look into it.

To use an absolute (shared) location, the EAR/WAR is not extracted from the WDT archive, but has to exist in the target location. In your case, simple-app.war would need to already be present in /apps/simple . Only paths starting with /wlsdeploy are extracted from the WDT archive.
