### ISSUE TITLE
OPSS Processing error in 1.8.1 while 1.3.0 worked

### ISSUE THREAD

**Issue by vdrHorst** [oracle/weblogic-deploy-tooling#633]
Hi,
Using the weblogic deploy tooling version 1.3.0 successfully. Would like to start using latest 1.8.1 as of support for ServerComponents like OHS.
I am using exactly the same configuration (.wdt) file and createDomain command, only changed from version 1.3.0 to 1.8.1 now.
But now the domain is not created as it throws:
- Error occurred in "OPSS Processing" phase execution
- JDBC password for opss-audit-DBDS is missing for configuring security store to database. 

Attached the used configuration files (DOMFRS12213.wdt and FRS.json),
together with two log outputs, one using the working 1.3.0 and one from using 1.8.1

Hope it is something simple for you to check what is going wrong here, 
as I would like to investigate the ServerComponent integration

Greetings,
Bert van der Horst
[createDomain_DOMFRS12213_v181.log](https://github.com/oracle/weblogic-deploy-tooling/files/4667530/createDomain_DOMFRS12213_v181.log)
[createDomain_DOMFRS12213_v130.log](https://github.com/oracle/weblogic-deploy-tooling/files/4667534/createDomain_DOMFRS12213_v130.log)

[DOMFRS12213.wdt.txt](https://github.com/oracle/weblogic-deploy-tooling/files/4667537/DOMFRS12213.wdt.txt)
[FRS.json.txt](https://github.com/oracle/weblogic-deploy-tooling/files/4667538/FRS.json.txt)

**Comment by vdrHorst** [comment]
Update: 
I tested the same using version the next version: The domain is created successfully using 1.4.0
I tested the same using version the next version: (same) OPSS Processing Error is introduced in 1.5.0
Something changed in OPSS creation for "opss-audit-DBDS" in 1.5.0?

**Comment by CarolynRountree** [comment]
Thank you for the investigation of versions. May I ask if your createDomain is performed against an existing domain? (which is valid, but sometimes can have problems.) If so, could you physically delete the domain and run the createDomain again. Meanwhile, I am looking at your logs.

**Comment by vdrHorst** [comment]
Hi Carolyn,
The createDomain is only performed as completely new domain each time, for all tested versions.

**Comment by CarolynRountree** [comment]
Found the problem and will be fixed in the next release. A temporary workaround is to add this template to your extensionTemplates. Even if your template is pulling this in, duplicating it will not hurt 

"Oracle JRF WebServices Asynchronous services",

**Comment by ddsharpe** [comment]
fixed by #635

**Comment by vdrHorst** [comment]
I hereby confirm that (temporary) adding the given extentionTemplate to my FRS.json definition solves the issue. Thanks !
