### ISSUE TITLE
Request for option to start application in admin mode

### ISSUE THREAD

**Issue by roeq** [oracle/weblogic-deploy-tooling#637]
Would be useful for to be able for the deployed application to start in admin mode similar to the weblogic.Deployer

java weblogic.Deployer  -start [-adminmode]

**Comment by ddsharpe** [comment]
@roeq it appears to be possible.  We will look into adding this capability in a future sprint.

NOTE - https://docs.oracle.com/middleware/12213/wls/DEPGD/deploy.htm#DEPGD245
https://docs.oracle.com/middleware/1213/wls/WLSTC/reference.htm#WLSTC202

**Comment by robertpatrick** [comment]
Closing for now, feel free to reopen if this is critical for you
