### ISSUE TITLE
Specify JPA Provider

### ISSUE THREAD

**Issue by MFYP** [oracle/weblogic-deploy-tooling#639]
How to specify JPA Provider for domain in model yaml file? By default the value is stored in domains\domain_namel\config\config.xml, property or xml attribute is
`<jpa>`
    `<default-jpa-provider>org.apache.openjpa.persistence.PersistenceProviderImpl</default-jpa-provider>`
  `</jpa>`

**Comment by ddsharpe** [comment]
@MFYP I searched the aliases, and it looks like that attribute was never added to WDT.  In the current release, there is no way to set that value with WDT.  Please let me know the priority of your needs for this setting, and we will add the work to the schedule appropriately.

**Comment by MFYP** [comment]
I would like it to be available ASAP. So sooner the better. Because I can't insert/change the property inside config.xml using ant task either.

**Comment by rakillen** [comment]
This was fixed with PR #644, and will be in the next release

**Comment by MFYP** [comment]
Thank you. Will documentation be updated as to which model tokens/topology to be used?
Also currently do we have option to change jta timeout?

**Comment by rakillen** [comment]
Details about the JPA MBean and attributes can be displayed using the modelHelp tool (once JPA is released):
```
modelHelp.sh -oracle_home /oracle/home /JPA
```
I see three Timeout attributes in JTA:
```
modelHelp.sh -oracle_home /oracle/home /JTA
```
JTA is already in the latest release.
https://github.com/oracle/weblogic-deploy-tooling/blob/master/site/model_help.md

**Comment by MFYP** [comment]
Thanks for all the information regarding modelHelp tool. I was able to make changes to JTA. Would wait for the release for JPA change.

**Comment by MFYP** [comment]
When would be the next release? It's been more than a month since last release.

**Comment by ddsharpe** [comment]
@MFYP https://github.com/oracle/weblogic-deploy-tooling/releases/tag/weblogic-deploy-tooling-1.9.1

**Comment by MFYP** [comment]
Thanks for the update. The tool works and solves the issue of JPA provider.
