### ISSUE TITLE
StagingMode not working

### ISSUE THREAD

**Issue by roeq** [oracle/weblogic-deploy-tooling#661]
When specifying StagingMode: nostage,  as in the example model below,  the code is still deployed to the managed servers staging area when using deployApps.sh version 1.9.0

appDeployments:
    Application:
        # Quote needed because of hyphen in string
        'simple-app':
            SourcePath: 'wlsdeploy/applications/simple-app.war'
            Target: '@@PROP:CLUSTER_NAME@@'
            ModuleType: war
            StagingMode: nostage
            PlanStagingMode: nostage

**Comment by CarolynRountree** [comment]
Would you provide the app deployment snippet from the config.xml after the deploy to the domain occurs please?

**Comment by roeq** [comment]
> Would you provide the app deployment snippet from the config.xml after the deploy to the domain occurs please?

It seems to work with offline deployment.  config.xml is updated properly.

Online deployment the StagingMode parameter is not passed to the wlst_helper method

**Comment by CarolynRountree** [comment]
This is an issue. Online deployment does not set the staging mode option. Will address this in an upcoming sprint.

**Comment by CarolynRountree** [comment]
1.9.2
