### ISSUE TITLE
Logging Doesn't Work for Domain created with WDT

### ISSUE THREAD

**Issue by MFYP** [oracle/weblogic-deploy-tooling#663]
Hi
When I create a domain using WDT create domain and application is deployed from domain.yaml file, Logging Doesn't Work for web-application like custom logs app.log etc which are stored in domain_name/logs folder. If I deploy application (through eclipse/ant) again without any changes to domain then logging works. So the default create domain+web-application deployment through WDT tool disables custom logs. Is there any specific change/attribute which needs to be set?

**Comment by ddsharpe** [comment]
@MFYP Can you share the snipped of config.xml for the application deployed with ANT or Eclipse, as well as the one that you that you deployed with WDT?

**Comment by MFYP** [comment]
I'm attaching both config.xml
[config_ant.xml.txt](https://github.com/oracle/weblogic-deploy-tooling/files/4887156/config_ant.xml.txt)
[config_wdt.xml.txt](https://github.com/oracle/weblogic-deploy-tooling/files/4887157/config_wdt.xml.txt)

**Comment by ddsharpe** [comment]
@MFYP it looks like you have your custom logger setup as a Startup class.  For startup classes to work in WLS, the JAR or those classes must be in the WLS system classpath for each server.  When you created the domain with WDT, how did you add those classes to the server classpath?  How do you start each server in the domain?

**Comment by MFYP** [comment]
I have the jar file in domain/lib folder. I only have 1 server - Admin Server. For starting the domain, I just start server through eclipse or using startWebLogic.cmd.

**Comment by ddsharpe** [comment]
@MFYP The WLS documentation says that classes used as startup classes must be in the Java system classpath.  One of our team tried the domain/lib folder just to double check.  The domain/lib classpath is not available in time for the startup classes for WLS.  This should be the same whether you are using Eclipse, ANT, WDT, or ... anything else.

**Comment by MFYP** [comment]
After adding jars from domain\lib folder to classpath environment variable, the logging works for domain created with WDT. But logging works for eclipse and ant without environment variable.
