### ISSUE TITLE
Global Role not discovered

### ISSUE THREAD

**Issue by flistell** [oracle/weblogic-deploy-tooling#673]
Hi, I'm using the tool at commit:53ed38e95fd59ec64c7199541e7f83b6c34f19a3.
I've used discoverDomain against a Domain where there is a custom rule added to "Admin" GlobalRole.

This is the WLST code that was used to configure the role:

```python
   realm = cmo.getSecurityConfiguration().getDefaultRealm()
    rolemapper = realm.lookupRoleMapper('XACMLRoleMapper')
    rolemapper.setRoleExpression(None, "Admin", "Grp(%s)|?weblogic.entitlement.rules.AdministrativeGroup(Administrators)" % authorized_ad_group)
```
The resulting model does not contains any WLSRoles section.

**Comment by ddsharpe** [comment]
Thanks @flistell, we will try to replicate the issue.

**Comment by robertpatrick** [comment]
@flistell I am looking at what we could do to add discovery of the Global Roles for online discovery. My first thought is to try to do a limited implementation that only adds Global Roles to the discovered model if:

1. a built-in Global Role has been modified from the default
2. a non-built-in Global Role has been added

What I would like your feedback on is the types of changes you are making to the global roles. For example, if the first pass would only support associating groups with the roles, is that sufficient for your use case(s)?

**Comment by flistell** [comment]
@robertpatrick for my current use case it would be ok to have at least the discovery of group associated with global roles.
Thanks.

**Comment by robertpatrick** [comment]
Added in WDT 1.9.18
