### ISSUE TITLE
Generate unique JTA Migratable Target names in configured clusters

### ISSUE THREAD

**Issue by tbarnes-us** [oracle/weblogic-deploy-tooling#678]
A while back, WDT was fixed so that it generates unique JTA Migratable Target names in a dynamic cluster, but it looks like the same fix is also needed for configured clusters.

Namely the following configured server stanza:
```
             JTAMigratableTarget:
                Cluster: "@@PROP:CLUSTER_NAME@@"
                UserPreferredServer: "@@PROP:MANAGED_SERVER_NAME_BASE@@2"
```
Generates the same Name on each server in the cluster, for example:
```
  <jta-migratable-target>
      <name>NO_NAME_0</name>
      <user-preferred-server>managed-server1</user-preferred-server>
      <cluster>cluster-1</cluster>
    </jta-migratable-target>
```
The work around is to alter the WDT to specify a unique name:
```
 JTAMigratableTarget:
                Name: "@@PROP:MANAGED_SERVER_NAME_BASE@@2"
                Cluster: "@@PROP:CLUSTER_NAME@@"
                UserPreferredServer: "@@PROP:MANAGED_SERVER_NAME_BASE@@2"
```

**Comment by preethig8** [comment]
Workaround suggested will not work as Name is not one of the attribute allowed in the JTAMigratable section-
Issue Log for createDomain version 1.9.1 running WebLogic version 12.2.1.4.0 offline mode:
SEVERE Messages:
        1. WLSDPLY-05029: Name is not one of the attribute names allowed in model location topology:/Server/managed-server1/JTAMigratableTarget
        2. WLSDPLY-05029: Name is not one of the attribute names allowed in model location topology:/Server/managed-server2/JTAMigratableTarget
        3. WLSDPLY-05029: Name is not one of the attribute names allowed in model location topology:/Server/managed-server3/JTAMigratableTarget
        4. WLSDPLY-20001: createDomain did not complete the operation because validation failed
Total:       WARNING :     0    SEVERE :     4
