### ISSUE TITLE
syntax error: `scriptPath=$' unexpected

### ISSUE THREAD

**Issue by jonwilliams84** [oracle/weblogic-deploy-tooling#702]
Hi,

I am trying to run the discover tool in online mode against a WL 10.3.6 domain running on Sun 5.10 Generic_150400-23 sun4v sparc sun4v machine but getting this error:

weblogic-deploy/bin/discoverDomain.sh: syntax error at line 91: `scriptPath=$' unexpected

I have managed to use an earlier version of the tool with relative success.

I have also taken a model produced using this older version and tried the kubernetes domain resource tool with a similar error:
weblogic-deploy/bin/extractDomainResource.sh: syntax error at line 73: `scriptPath=$' unexpected

Any thoughts?

Thanks in advance

**Comment by ddsharpe** [comment]
@jonwilliams84 We are fairly certain that its related to our change from back-tick to $(), which was done to be more POSIX compliant in the shell scripts.  The $() construct, also, allows nesting, versus back-ticks that do not.  From your error message, it would appear that your shell does not support the $() construct.
Try running a simple echo command to see if your shell supports $().  Like `echo "$(ls)"`.  Then try the same thing but replace the $() with back-ticks.

**Comment by ddsharpe** [comment]
Closing this issue due to lack of response.  Please re-open or create a new issue when you are available to discuss further.
