### ISSUE TITLE
Invalid token syntax for Target value

### ISSUE THREAD

**Issue by textanalyticsman** [oracle/weblogic-deploy-tooling#708]
Hello,

I have used discoverDomain.sh to generate a model file and a properties file and then when I executed createDomain.sh I got below messages

    Issue Log for createDomain version 1.9.3 running WebLogic version 12.2.1.4.0 offline mode:

    SEVERE Messages:

        1. WLSDPLY-01746: Invalid token syntax for Target value "@@PROP:Lib.oracle.wsm.idmrest.sharedlib#1.0@12.2.1.3.Target@@", should match "@@PROP:<name>@@"
        2. WLSDPLY-20004: createDomain variable substitution failed: Invalid token syntax for Target value "@@PROP:Lib.oracle.wsm.idmrest.sharedlib#1.0@12.2.1.3.Target@@", should match "@@PROP:<name>@@"

This is that I see in my properties file.

    Lib.oracle.wsm.idmrest.sharedlib#1.0@12.2.1.3.Target=soa_cluster,AdminServer

This is that I see in my model file.

    appDeployments:
        Library:
            'oracle.wsm.idmrest.sharedlib#1.0@12.2.1.3':
                SourcePath: '@@ORACLE_HOME@@/oracle_common/modules/oracle.wsm.common/wsm-idmrest-sharedlib.war'
                StagingMode: nostage
                Target: '@@PROP:Lib.oracle.wsm.idmrest.sharedlib#1.0@12.2.1.3.Target@@'

I am trying to create a SOA domain 12.2.1.4 and I am using WLDT version 1.9.3.

Kindly help me with this issue.

**Comment by rakillen** [comment]
Hello textanalyticsman - it looks like the name of the discovered property includes some characters that are not currently allowed, in this case "#" and "@". We'll look into a solution for this.

If you need to work around this problem in the meantime, just replace those two characters with "-" in the properties file and in your model.

**Comment by textanalyticsman** [comment]
Thanks a lot, I will use the workaround.
