### ISSUE TITLE
No boot.properties when using PROD mode

### ISSUE THREAD

**Issue by flyingZippo** [oracle/weblogic-deploy-tooling#709]
Hi,

I am using WDT create domain command to deploy my application, but when I using prod mode I found that boot.properties is not created, so I checked the source code mothod  __create_boot_dot_properties in https://github.com/oracle/weblogic-deploy-tooling/blob/master/core/src/main/python/wlsdeploy/tool/create/domain_creator.py, it seems intentionally to do it, could you please tell me why? And how can I get the boot.properties when using prod mode?

If the file boot.properties does not exists, then I will get an issue when starting weblogic:
<Aug 19, 2020 8:33:12 AM CEST> <Info> <Security> <BEA-090065> <Getting boot identity from user.>
Enter username to boot WebLogic server:<Aug 19, 2020 8:33:12 AM CEST> <Error> <Security> <BEA-090782> <Server is running in Production Mode and the System Console to read the password securely from the command line was not found. The System Console is not present if stdin, stdout, or stderr is redirected when starting WebLogic Server.>

**Comment by CarolynRountree** [comment]
We are following best practices by not creating a boot.properties for the production environment for a) security and b) many of our customers use node manager in production to manage the environment.
Are you running the admin server in a Docker container? If so, can you create your boot.properties file after creating the domain and before starting the Admin Server? We have a sample Dockerfile and scripts in our sample directory that creates the boot.property in the container. For production though, perhaps you can mount the file and copy into your domain before starting the AdminServer. 

If this is an on premise domain, then you can create the boot.properties as described here.
https://www.oracle.com/webfolder/technetwork/tutorials/obe/fmw/wls/12c/15-BootProp--4471/bootproperties.htm

**Comment by flyingZippo** [comment]
Hi @CarolynRountree ,
Yes, I am running the admin server in a Docker container. Could you share the sample you mentioned above?
I did create a boot.properties file after wdt create domain with plaintext string, and after the weblogic start up it will be encrypted automatically. But it may has some security issue, if someone startup the container without startup the weblogic, eg override the entrypoint, then he can see the plaintext boot.properties. Do you have some ideas for this?

**Comment by CarolynRountree** [comment]
I am giving you two examples. The sample in weblogic-deploy-tooling was used as the base for a git-hub repository for WebLogic images. Both of the samples mount a properties file from your local file system to a container volume during the run command. The boot.properties is built from the data in the properties file. Let me know if you have any questions about this.

https://github.com/oracle/weblogic-deploy-tooling/tree/master/samples/docker-domain
https://github.com/oracle/docker-images/tree/master/OracleWebLogic/samples/12213-domain-home-in-image-wdt

**Comment by CarolynRountree** [comment]
These both use WDT to create the domain in the build stage.On Aug 20, 2020 4:46 PM, Carolyn Rountree <notifications@github.com> wrote:
I am giving you two examples. The sample in weblogic-deploy-tooling was used as the base for a git-hub repository for WebLogic images. Both of the samples mount a properties file from your local file system to a container volume during the run command. The boot.properties is built from the data in the properties file. Let me know if you have any questions about this.
https://github.com/oracle/weblogic-deploy-tooling/tree/master/samples/docker-domain
https://github.com/oracle/docker-images/tree/master/OracleWebLogic/samples/12213-domain-home-in-image-wdt

**Comment by flyingZippo** [comment]
Hi @CarolynRountree ,
Thanks for providing the links. 
Since we are using kubernetes environment, so I will switch to using environment variables when startup the container, and create the boot.properties via a shell script before startup weblogic server.

I will close the issue, thank you for help.
