### ISSUE TITLE
Wrong targets for SOA domain

### ISSUE THREAD

**Issue by textanalyticsman** [oracle/weblogic-deploy-tooling#729]
I executed createDomain.sh and it finished without issues. However, when I tried to start the AdminServer I got several errors like this.

    <13-Sep-2020 17:45:03,967 o'clock CEST> <Error> <Deployer> <BEA-149205> <Failed to initialize the application 
    "oracle.dconfig-infra" due to error weblogic.application.library.LibraryDeploymentException: [J2EE:160145]Failed to deploy library
     Extension-Name: oracle.dconfig-infra, Implementation-Version: 12.2.1, because of conflicting library Manifest values, and library
     information registered with the server: [Implementation-Version: 12.2.1 vs. <not-set>]. Check the library MANIFEST.MF file and
     correct version information there to match server settings, or undeploy the misconfigured library.

The DOMAIN_HOME/config/config.xml file has several libraries/applications like this

    <library>
      <name>oracle.dconfig-infra#2.0@12.2.1</name>
      <target>soa_cluster,AdminServer,soa_server1</target>
      <source-path>/u01/oracle/product/fmw12214/oracle_common/modules/oracle.dconfig-infra.jar</source-path>
      <staging-mode>nostage</staging-mode>
    </library>

Within the previous snippet soa_server1 must not be a target. Importantly, my properties file does not state this wrong target as you can see here.

    Lib.oracle.dconfig-infra-2.0-12.2.1.Target=soa_cluster,AdminServer

This is my model file

            'oracle.dconfig-infra#2.0@12.2.1':
            SourcePath: '@@ORACLE_HOME@@/oracle_common/modules/oracle.dconfig-infra.jar'
            StagingMode: nostage
            Target: '@@PROP:Lib.oracle.dconfig-infra-2.0-12.2.1.Target@@'

Kindly help me to fix this.

**Comment by rakillen** [comment]
Hi textanalyticsman -

I think the original error occurs because the model specifies explicit version info, like: `#2.0@12.2.1` , and the jar from the WLS installation does not have any version information (I'm looking at that library jar in my 12.2.1 install). Please try removing the version information from the model, such as:
```
'oracle.dconfig-infra':
        SourcePath: '@@ORACLE_HOME@@/oracle_common/modules/oracle.dconfig-infra.jar'
        StagingMode: nostage
        Target: '@@PROP:Lib.oracle.dconfig-infra-2.0-12.2.1.Target@@'
```
Did the version information in your existing model come from the discoverDomain process? And was that from a different WLS version?

Still looking at the targeting issue. Can you tell me if soa_server1 is a member of soa_cluster?

Thanks

**Comment by textanalyticsman** [comment]
Thanks for answering.

Yes, the version information comes from the discoverDomain process. Regarding WLS version, I am using 12.2.1.4.

I have also installed my domain using a manual process and this is a snippet from config.xml file

    <library>
      <name>oracle.dconfig-infra#2.0@12.2.1</name>
      <target>soa_cluster,AdminServer</target>
      <source-path>/u01/oracle/product/fmw12214/oracle_common/modules/oracle.dconfig-infra.jar</source-path>
      <staging-mode>nostage</staging-mode>
   </library>

On previous snippet you can see the version is used even though the JAR file does not include it. However, the version is part of the META-INF/MANIFEST.MF as you can see below.

    Manifest-Version: 1.0
    Implementation-Version: 12.2.1
    Built-By: wls
    Source-Repository-Change-Id: 1974694
    Built-JDK: 1.8.0_211
    Created-By: Gradle
    Implementation-Vendor: Oracle

Therefore, I think the information about libraries is correct and the message I got while I tried to start AdminServer is caused by a wrong targeting; first on the cluster and then the same on a particular server, which is member of the cluster. Yes, soa_server1 is a member of soa_cluster.

**Comment by rakillen** [comment]
I've run a createDomain with this library in the model:
```
    Library:
        'oracle.dconfig-infra#2.0@12.2.1':
            SourcePath: '@@ORACLE_HOME@@/oracle_common/modules/oracle.dconfig-infra.jar'
```
and this resulted in the config.xml containing:
```
  <library>
    <name>oracle.dconfig-infra</name>
```
This is different from your original post? If I try to start the admin server with this (regardless of changes to the targeting), I get the error you saw above:
```
... conflicting library Manifest values, and library information registered with the server: [Implementation-Version: 12.2.1 vs. <not-set>]
```
That makes sense, because the config.xml versioning (none) does not match the manifest. If I manually edit the config.xml to contain:
```
  <library>
    <name>oracle.dconfig-infra#2.0@12.2.1</name>
```
The admin server starts up correctly, even when I add or remove the managed server targeting.

The source of the problem seems to be that WDT is stripping the version information because **Specification-Version** is not present in the jar MANIFEST.MF. If I hard-code this in WDT and run createDomain, the admin server starts up cleanly.

I'll look into how WDT can include this versioning information in the configuration.

**Comment by rakillen** [comment]
I tried running this with discover/create, and changed my last response. The short answer is that many of these libraries should not be discovered. There is a mechanism in the typedef file that prevents system files from being discovered, and cluttering up the discovered model (and creating problems like the ones above).

The typedef should contain this section:
```
    "system-elements": {
    . . .
        "shared-libraries": [
            "^adf\\.oracle\\.businesseditor.*",
            "^adf\\.oracle\\.domain.*",
            "^adf\\.oracle\\.domain\\.webapp.*",
            . . .
            "^oracle\\.dconfig-infra.*",
            . . .
        ],
        . . .
```
These are regexes that should match library names, I see one there that should match oracle.dconfig-infra#2.0@12.2.1 and exclude it. I tried this with the supplied JRF typedef, and that library was excluded correctly.

Have you created a new typedef for your SOA domains, and have you included these entries?

**Comment by textanalyticsman** [comment]
I am using a file called weblogic-deploy/lib/typedefs/SOA.json. This is my content.

    {
        "name": "SOA",
        "description": "SOA type domain definitions",
        "versions": {
            "12.2.1.4": "SOA_12214"
        },
        "definitions": {
            "SOA_12214": {
                "baseTemplate": "Basic WebLogic Server Domain",
                "extensionTemplates": [
                    "Oracle SOA Suite"
                ],
                "serverGroupsToTarget": [ "JRF-MAN-SVR", "WSMPM-MAN-SVR",  "SOA-MGD-SVRS" ],
                "rcuSchemas": [ "STB", "WLS", "MDS", "IAU", "IAU_VIEWER", "IAU_APPEND", "OPSS", "UCSUMS", "SOAINFRA" ]
            }
        }
    }

**Comment by rakillen** [comment]
The best first step would be to copy the system-elements section from the typedef file JRF.json and re-run the discover domain. SOA is based on JRF, so this will eliminate many of the libraries, including the one in your original error. If there are any left that are not specific to your application, they should be added to the typedef as regexes.

The idea of the system-elements section is to exclude libraries (and other elements) that are added by the specified domain templates. That prevents them from being added to the model when they are not needed, and makes the model more portable across WLS versions. But it also makes them specific to the set of domain templates being used, and the template dependencies.

**Comment by textanalyticsman** [comment]
I have checked the file JRF.json and it is not only about libraries, but it is also about apps, datasources, shutdown-classes, startup-classes, etc. The point is that I do not know which elements to include there when it comes to SOA. Would not it be better if this provided on the repository?

**Comment by textanalyticsman** [comment]
I will do it. Thanks a lot.
