### ISSUE TITLE
Unable to convert argument to type java.lang.Class

### ISSUE THREAD

**Issue by JaredZieche** [oracle/weblogic-deploy-tooling#744]
WebLogic Deploy Tooling Version:  1.9.5
WebLogic version: 12.2.1.3.0

I see this attribute is defined in SecurityConfiguration.json

I am trying to create domain with ActiveDirectoryAuthenticator.
In my model file i have provided 
  RetrieveUserAccountControl: true

I receive this exception:
WLSDPLY-12409: createDomain failed to create the domain: Failed to set attribute RetrieveUserAccountControl in path /SecurityConfiguration/my_domain/Realm/myrealm/AuthenticationProvider/WebLogicADProvider to value false: Unable to co
nvert argument to type java.lang.Class", " @com.oracle.cie.domain.script.jython.WLScriptContext.set(WLScriptContext.java:2579)

Even with the property left blank or removed create fails trying to set the default of 'false'

Issue #157 seems to be the same problem with a different attribute.
Is there a way to work around this issue without deploying a new build?

SecurityConfiguration section from Model:
[model.txt](https://github.com/oracle/weblogic-deploy-tooling/files/5342377/model.txt)

**Comment by rakillen** [comment]
hello JaredZieche -

I'm able to recreate your issue and working on a fix for that. There are two problem values in your model, if you comment those out you should be able to get a clean run. 
```
#                            RetrieveUserAccountControl: true)

#                            EnableCacheStatistics: true
```
Also, there's a typo on "true)", but that's not the cause of your original problem.

**Comment by JaredZieche** [comment]
Thanks @rakillen  -
That was a typo on my part. I tried putting Boolean(true) in the model as a test.
Commenting did the trick.
I ran some unit tests base on  PR #159 and changed wlst_type to:
  java.lang.Boolean", "wlst_read_type": "boolean", "set_method": "MBEAN.set_attribute_with_cmo
The build passed with that change.
