### ISSUE TITLE
Question  - Oracle Access Manager (OAM)

### ISSUE THREAD

**Issue by textanalyticsman** [oracle/weblogic-deploy-tooling#747]
Hello,

I have a question, could we use Weblogic Deploy Tooling to provision OAM 11.1.2.3? I mean, OAM configuration needs several steps performed on OAM console and then it would be good to have this automated.

Thank you.

**Comment by mriccell** [comment]
@textanalyticsman is this in the context of OAM in containers/Kubernetes?

**Comment by textanalyticsman** [comment]
@mriccell the company I am working for is using virtual machines on OCI as they are leaving Exalogic. Kindly, feel free to share your ideas about container/Kubernetes for OAM.

Thanks a lot.

**Comment by mriccell** [comment]
OAM is in the process of certifying on Kubernetes using the WebLogic kubernetes Operator.  We need input from Mehul Poladia to see where are they in the adoption of WDT.

**Comment by textanalyticsman** [comment]
Thanks a lot @mriccell, I will stay tuned.

**Comment by ddsharpe** [comment]
Can we close this issue and take the conversation to Slack?

**Comment by textanalyticsman** [comment]
Hello @ddsharpe,

Thanks a lot for your attention and kindly tell me whether I can have access to that conversation on Slack.

I am closing this question.
