### ISSUE TITLE
Request for alternative login method 

### ISSUE THREAD

**Issue by kaifricke** [oracle/weblogic-deploy-tooling#766]
WLST offers a connect method which does not requires username or password.
If WLST is started from inside domain home, it needs only the AdminServer name and the connect url and reads username and password from boot.properties. (and those parameters can be even retrieved before in offline mode)
This is extremely useful when using Ansible to configure / deploy to a lot of domains as the individual passwords don't have to be maintained (and Ansible requires anyway root access)
It would be great, if WDT would support that too as currently online access requires anyway to be on the target server.

-Kai

**Comment by ddsharpe** [comment]
yes, should be possible.  We will look at this enhancement for a future release.

**Comment by robertpatrick** [comment]
@kaifricke I have started looking at this enhancement and have a few questions, if you don't mind.

1. Can you help me better understand your use case?  
2. In which WDT tool(s) (e.g., discoverDomain, updateDomain, etc.) in WDT would you want this functionality to be available?

**Comment by robertpatrick** [comment]
No response from user, closing for now
