### ISSUE TITLE
Build gives error

### ISSUE THREAD

**Issue by ravig-kant** [oracle/weblogic-deploy-tooling#781]
I tried to build the project using the following command.

mvn -DskipTests clean install

But the compilation fails with the following error. POM doesn't specify a dependency on  JAXB API jar. So it seems I missed some steps.

weblogic-deploy-tooling/core/src/main/java/oracle/weblogic/deploy/encrypt/EncryptionUtils.java:[25,22] package javax.xml.bind does not exist

**Comment by rakillen** [comment]
You will need to specify a WLST path to do the mvn build. There are more details at:
https://github.com/oracle/weblogic-deploy-tooling/blob/master/site/developer/developer_guide.md#building-weblogic-deploy-tool
