### ISSUE TITLE
YAML parse error: extraneous input 'v$session.process' expecting {NAME, LIST_ITEM_OP, DEDENT}>   

### ISSUE THREAD

**Issue by zeusbaba** [oracle/weblogic-deploy-tooling#783]
I have exported an existing domain using `discoverDomain` but I am having issues while trying  to `createDomain` using this template.  
The error seems to be YAML parser related.  

For example:  
Such lines from  WDT template
```
v$session.process:
	Value: LocalSvcTblD
v$session.machine:
	SysPropValue: weblogic.Name
```
throws YAML parse error like  
```
<SEVERE> <ParsingErrorListener> <syntaxError> <WLSDPLY-18018> <Parse error for file ....>   
at line 1,911 position 24: extraneous input 'v$session.process' expecting {NAME, LIST_ITEM_OP, DEDENT}>   
at line 1,913 position 24: extraneous input 'v$session.machine' expecting {NAME, LIST_ITEM_OP, DEDENT}>  
```

**Comment by CarolynRountree** [comment]
Try putting those names with the special characters, including periods, in quotes.

**Comment by CarolynRountree** [comment]
quotes will not help. Addressing this as a bug.

**Comment by zeusbaba** [comment]
indeed.  notice that `v$session.process:`  was generated by `discoverDomain` 
thus, if quotes were necessary, the generation should have taken care of this as well.

**Comment by zeusbaba** [comment]
the current need is;  
- `discoverDomain` to introspect and existing domain and generate WDT template  
- `createDomain` to apply this WDT template onto another instance.  
achieving this flow smoothly is important

**Comment by zeusbaba** [comment]
a potential fix _might_ be necessary in _antlr_ template, could that be [here](https://github.com/oracle/weblogic-deploy-tooling/blob/master/core/src/main/antlr4/oracle/weblogic/deploy/yaml/Yaml.g4#L319) ?  
p.s. i'm not well versed with _antlr_

**Comment by zeusbaba** [comment]
Thanks for your fast feedback and quick fix. 💯  
I just created WDT from `master` and verified that your fix works.
