### ISSUE TITLE
 Error while creating the basic weblogic domain by using WDT

### ISSUE THREAD

**Issue by prathapdasari** [oracle/weblogic-deploy-tooling#785]
Hi,

I have created a YAML file by myself for the basic WebLogic domain creation and while executing the script, I am now getting a parse error which is odd as I have not edited these lines. Any advice?

####<Nov 18, 2020 1:31:59 AM> <INFO> <WebLogicDeployToolingVersion> <logVersionInfo> <WLSDPLY-01750> <The WebLogic Deploy Tooling createDomain version is 1.9.7:master.2266258:Nov 06, 2020 22:20 UTC>
####<Nov 18, 2020 1:31:59 AM> <SEVERE> <Validator> <__validate_root_level> <WLSDPLY-05007> <Model file /u01/oracle/product/12.2.1.4.0/weblogic-deploy/lib/typedefs/basicwlsdomain.yml contains an unrecognized section: UnixMachine. The recognized sections are domainInfo, topology, resources, appDeployments, kubernetes>
####<Nov 18, 2020 1:31:59 AM> <SEVERE> <Validator> <__validate_root_level> <WLSDPLY-05007> <Model file /u01/oracle/product/12.2.1.4.0/weblogic-deploy/lib/typedefs/basicwlsdomain.yml contains an unrecognized section: SecurityConfiguration. The recognized sections are domainInfo, topology, resources, appDeployments, kubernetes>
####<Nov 18, 2020 1:32:00 AM> <SEVERE> <Validator> <__process_model_node> <WLSDPLY-05029> <ListeinAddress is not one of the attribute names allowed in model location topology:/Server/wls_ms1>
####<Nov 18, 2020 1:32:00 AM> <SEVERE> <Validator> <__process_model_node> <WLSDPLY-05029> <ListeinPort is not one of the attribute names allowed in model location topology:/Server/wls_ms1>
####<Nov 18, 2020 1:32:00 AM> <SEVERE> <Validator> <__process_model_node> <WLSDPLY-05029> <machine is not one of the attribute names allowed in model location topology:/Server/wls_ms1>
####<Nov 18, 2020 1:32:00 AM> <SEVERE> <cla_helper> <validate_model> <WLSDPLY-20001> <createDomain did not complete the operation because validation failed>

Issue Log for createDomain version 1.9.7 running WebLogic version 12.2.1.4.0 offline mode:

SEVERE Messages:

        1. WLSDPLY-05007: Model file /u01/oracle/product/12.2.1.4.0/weblogic-deploy/lib/typedefs/basicwlsdomain.yml contains an unrecognized section: UnixMachine. The recognized sections are domainInfo, topology, resources, appDeployments, kubernetes
        2. WLSDPLY-05007: Model file /u01/oracle/product/12.2.1.4.0/weblogic-deploy/lib/typedefs/basicwlsdomain.yml contains an unrecognized section: SecurityConfiguration. The recognized sections are domainInfo, topology, resources, appDeployments, kubernetes
        3. WLSDPLY-05029: ListeinAddress is not one of the attribute names allowed in model location topology:/Server/wls_ms1
        4. WLSDPLY-05029: ListeinPort is not one of the attribute names allowed in model location topology:/Server/wls_ms1
        5. WLSDPLY-05029: machine is not one of the attribute names allowed in model location topology:/Server/wls_ms1
        6. WLSDPLY-20001: createDomain did not complete the operation because validation failed

Total:       WARNING :     0    SEVERE :     6

createDomain.sh failed (exit code = 2)

Here is my YAML file:

```
domainInfo:
   AdminUserName: weblogic
   AdminPassword: welcome1
   ServerStartMode: prod
topology:
   Name: WlsDomain
   AdminServerName: AdminServer
   Cluster:
       wlscluster:
   Server:
       AdminServer:
           ListenAddress: sejenk01
           ListenPort: 7001
           Machine: sejenk01
           Log:
               FileCount: 9
               LogFileSeverity: Info
               FileMinSize: 5000
           SSL:
               Enabled: true
               ListenPort: 5556
               HostnameVerificationIgnored: true
       wls_ms1:
          ListeinAddress: sejenk01
          ListeinPort: 8010
          machine: sejenk01
          Log:
             DomainLogBroadcastSeverity: Error
             FileCount: 7
             FileMinSize: 5000
             FileName: 'logs/AdminServer.log'
             LogFileSeverity: Info
             MemoryBufferSeverity: Notice
             NumberOfFilesLimited: true
             RotateLogOnStartup: true
             RotationType: bySize
          ServerStart:
             Arguments: '-Dosgi=true -Dtangosol.coherence.management=all -D -Xms=1024m -Xmx=1024'
UnixMachine:
          sejenk01:
             NodeManager:
                ListenAddress: sejenk01
                ListenPort: 5556
SecurityConfiguration:
          NodeManagerUsername: nmUser
          NodeManagerPasswordEncrypted: welcome1
          UseKSSForDemo: true
          Realm:
             myrealm:
                AuthenticationProvider:
                      Trust Service Identity Asserter:
                            TrustServiceIdentityAsserter:
                      DefaultAuthenticator:
                            DefaultAuthenticator:
                                UseRetrievedUserNameAsPrincipal: true
                      DefaultIdentityAsserter:
                            DefaultIdentityAsserter:
resources:
          CoherenceClusterSystemResource:
             defaultCoherenceCluster:
                 Target: soa_cluster
                 CoherenceResource:
                     CoherenceClusterParams:
                           ClusterListenPort: 7574
```

**Comment by prathapdasari** [comment]
Any update on this ?

**Comment by rakillen** [comment]
UnixMachine and SecurityConfiguration need to be indented one level to be inside topology.
Under wls_ms1:
- ListeinAddress and ListeinPort are misspelled (ListenAddress and ListenPort).
- machine should be Machine

Hope that helps. The modelHelp tool can build the model. For example, to display the attributes for a server:

modelHelp.sh -oracle_home <directory> topology:/Server

https://github.com/oracle/weblogic-deploy-tooling/blob/master/site/model_help.md

**Comment by prathapdasari** [comment]
Thank you ... 

An earlier error is gone but getting a different RCU error .. 
####<Nov 18, 2020 4:08:02 PM> <SEVERE> <PyReflectedFunction> <__call__> <WLSDPLY-12408> <Domain type JRF definition has RCU schemas defined so the -rcu_db and -rcu_prefix arguments are required>

Issue Log for createDomain version 1.9.7 running WebLogic version 12.2.1.4.0 offline mode:

SEVERE Messages:

        1. WLSDPLY-12408: Domain type JRF definition has RCU schemas defined so the -rcu_db and -rcu_prefix arguments are required

Total:       WARNING :     0    SEVERE:     1

createDomain.sh failed (exit code = 2)

Just I would like to create a basic WebLogic domain without  RCU. Is it possible to do that?

**Comment by prathapdasari** [comment]
Discard my last comment.
I used -domain_type WLS instead of JRE IN the command but it´s failing with a different error.

####<Nov 18, 2020 4:28:56 PM> <SEVERE> <create> <main> <WLSDPLY-12409> <createDomain failed to create the domain: Unable to create(Trust Service Identity Asserter, oracle.security.jps.wls.providers.trust.TrustServiceIdentityAsserter, AuthenticationProvider) in offline mode at location /SecurityConfiguration/WlsDomain/Realm/myrealm : null
 @com.oracle.cie.domain.aspect.AbstractConfigAspect.getAspectClass(AbstractConfigAspect.java:126)>

Issue Log for createDomain version 1.9.7 running WebLogic version 12.2.1.4.0 offline mode:

SEVERE Messages:

        1. WLSDPLY-12409: createDomain failed to create the domain: Unable to create(Trust Service Identity Asserter, oracle.security.jps.wls.providers.trust.TrustServiceIdentityAsserter, AuthenticationProvider) in offline mode at location /SecurityConfiguration/WlsDomain/Realm/myrealm : null
 @com.oracle.cie.domain.aspect.AbstractConfigAspect.getAspectClass(AbstractConfigAspect.java:126)

Total:       WARNING :     0    SEVERE :     1

createDomain.sh failed (exit code = 2)

**Comment by CarolynRountree** [comment]
remove the 'Trust Identity Asserter' from your SecurityConfiguration and then you can create just a basic WLS domain. run without the -domain_type and it will create a basic domain.

**Comment by prathapdasari** [comment]
Thank you for your quick help !

It worked :)
Issue Log for createDomain version 1.9.7 running WebLogic version 12.2.1.4.0 offline mode:

Total:       WARNING :     0    SEVERE :     0

createDomain.sh completed successfully (exit code = 0)

I will close this ticket now . Will create a new case when I am creating SOA and OSB domains

**Comment by prathapdasari** [comment]
While starting the AdminServrer getting the below Keystore errors ..

<Nov 18, 2020 4:43:38 PM CET> <Critical> <WebLogicServer> <BEA-000386> <Server subsystem failed. Reason: A MultiException has 5 exceptions.  They are:
1. weblogic.management.provider.internal.RuntimeAccessImpl$ParseException: [Management:141266]Parsing failure in config.xml: java.lang.IllegalArgumentException: Unable to use KSS for Demo Key Stores, KSS is unavailable..
2. java.lang.IllegalStateException: Unable to perform operation: create on weblogic.management.provider.internal.RuntimeAccessImpl
3. java.lang.IllegalStateException: Unable to perform operation: post construct on weblogic.management.provider.internal.RuntimeAccessService
4. java.lang.IllegalArgumentException: While attempting to resolve the dependencies of weblogic.t3.srvr.FinalThreadLocalService errors were found
5. java.lang.IllegalStateException: Unable to perform operation: resolve on weblogic.t3.srvr.FinalThreadLocalService

**Comment by prathapdasari** [comment]
All issues fixed. Thank you
