### ISSUE TITLE
Getting error while creating the OSB domain

### ISSUE THREAD

**Issue by prathapdasari** [oracle/weblogic-deploy-tooling#788]
Hi, 

Getting below errors while creating the OSB domain with WDT. 

####<Nov 18, 2020 10:47:16 PM> <SEVERE> <create> <main> <WLSDPLY-12409> <createDomain failed to create the domain: selectTemplate(Oracle OSB Suite) failed : Error adding Template:
60708: Template not found.
60708: Found no templates with Oracle OSB Suite name and null version
60708: Select a different template.>

Issue Log for createDomain version 1.9.7 running WebLogic version 12.2.1.4.0 offline mode:

SEVERE Messages:

        1. WLSDPLY-12409: createDomain failed to create the domain: selectTemplate(Oracle OSB Suite) failed : Error adding Template:
60708: Template not found.
60708: Found no templates with Oracle OSB Suite name and null version
60708: Select a different template.

Total:       WARNING :     0    SEVERE :     1

createDomain.sh failed (exit code = 2)

**Comment by rakillen** [comment]
I believe the correct name for the OSB template is "Oracle Service Bus".
The entry in your typedef file would look like:
```
             "extensionTemplates": [
                 "Oracle Service Bus"
             ],
```
Be sure to install OSB in the Oracle Home you are using for create.

**Comment by prathapdasari** [comment]
Ok. Let me check the OSB.json file once

**Comment by prathapdasari** [comment]
"definitions": {
        "OSB_12214": {
            "baseTemplate": "Basic WebLogic Server Domain",
            "extensionTemplates": [
                "Oracle OSB Suite"

**Comment by prathapdasari** [comment]
Hi,

Getting a different error while creating the OSB domain. Any advice?

####<Nov 18, 2020 11:48:02 PM> <SEVERE> <create> <main> <WLSDPLY-12409> <createDomain failed to create the domain: Unable to create(Trust Service Identity Asserter, oracle.security.jps.wls.providers.trust.TrustServiceIdentityAsserter, AuthenticationProvider) in offline mode at location /SecurityConfiguration/osb_domain/Realm/myrealm : null
 @com.oracle.cie.domain.aspect.AbstractConfigAspect.getAspectClass(AbstractConfigAspect.java:126)>

Issue Log for createDomain version 1.9.7 running WebLogic version 12.2.1.4.0 offline mode:

SEVERE Messages:

        1. WLSDPLY-12409: createDomain failed to create the domain: Unable to create(Trust Service Identity Asserter, oracle.security.jps.wls.providers.trust.TrustServiceIdentityAsserter, AuthenticationProvider) in offline mode at location /SecurityConfiguration/osb_domain/Realm/myrealm : null
 @com.oracle.cie.domain.aspect.AbstractConfigAspect.getAspectClass(AbstractConfigAspect.java:126)

Total:       WARNING :     0    SEVERE :     1

createDomain.sh failed (exit code = 2)

**Comment by rakillen** [comment]
Unless you are customizing security providers, you can probably remove the whole SecurityConfiguration section from your model.

**Comment by prathapdasari** [comment]
Thanks a lot for the help @Carolyn Rountree @rakillen 

The issue has been fixed as per the below document and the OSB domain has been created without any errors.

https://github.com/oracle/weblogic-deploy-tooling/blob/master/site/use_cases.md#modeling-security-providers

**Comment by prathapdasari** [comment]
After unpack , the config.xml is not uploading into node2 under config folder . Any advice ?

**Comment by ddsharpe** [comment]
Closing this issue as it appears to be resolved.  @prathapdasari Please post your pack/unpack question to the WebLogic public slack channel and the broader WebLogic teams will be able to see it and hopefully jump in to help.

**Comment by prathapdasari** [comment]
Ok, thank you. I will do the same public slack channel
