### ISSUE TITLE
Classic SOA domain with BPM

### ISSUE THREAD

**Issue by textanalyticsman** [oracle/weblogic-deploy-tooling#791]
Hello,

According to this [document ](https://docs.oracle.com/en/middleware/soa-suite/soa/12.2.1.4/administer/configuring-reference-configuration-domain.html#GUID-C1C21FAC-282E-4ED8-9567-3371CB9F21E2) we need to create a classic SOA domain to extend the domain with BPM. Thus, the question is how could I include the templates needed for this kind of domain?

I have tried below configuration without success.
```
{
    "name": "SOA",
    "description": "SOA type domain definitions",
    "versions": {
        "12.2.1.4": "SOA_12214"
    },
    "definitions": {
        "SOA_12214": {
            "baseTemplate": "Basic WebLogic Server Domain",
            "extensionTemplates": [],
            "customExtensionTemplates": [
                "@@ORACLE_HOME@@/soa/common/templates/wls/oracle.soa_template.jar",
                "@@ORACLE_HOME@@/soa/common/templates/wls/oracle.soa.classic.domain_template.jar"
            ],
            "serverGroupsToTarget": [ "JRF-MAN-SVR", "WSMPM-MAN-SVR", "SOA-MGD-SVRS" ],
            "rcuSchemas": [ "STB", "WLS", "MDS", "IAU", "IAU_VIEWER", "IAU_APPEND", "OPSS", "UCSUMS", "SOAINFRA" ]
        }
    }
}
```
I have got this error.

####<Nov 23, 2020 9:10:44 PM> <SEVERE> <create> <main> <WLSDPLY-12409> <createDomain failed to create the domain: writeDomain failed : Error writing domain:
64254: Error occurred in "OPSS Processing" phase execution
64254: Encountered error: oracle.security.opss.tools.lifecycle.LifecycleException: JDBC password for opss-audit-DBDS is missing for configuring security store to database.
64254: Check log for more detail.
null>

**Comment by CarolynRountree** [comment]
SOA requires RCU , which you can pre-configure or create during the createDomain.
https://github.com/oracle/weblogic-deploy-tooling/blob/master/site/create.md

**Comment by textanalyticsman** [comment]
Thank you, but I know that SOA need RCU. My question would be how could I create a BPM domain using WDT? Could you please provide an example? I have tried below definition and I ended up with a SOA domain without BPM.

> {
    "name": "SOA",
    "description": "SOA type domain definitions",
    "versions": {
        "12.2.1.4": "SOA_12214"
    },
    "definitions": {
        "SOA_12214": {
            "baseTemplate": "Basic WebLogic Server Domain",
            "extensionTemplates": ["Oracle SOA Suite"],
            "customExtensionTemplates": [
                "@@ORACLE_HOME@@/soa/common/templates/wls/oracle.soa.classic.domain_template.jar"
            ],            
            "serverGroupsToTarget": [ "JRF-MAN-SVR", "WSMPM-MAN-SVR", "SOA-MGD-SVRS" ],
            "rcuSchemas": [ "STB", "WLS", "MDS", "IAU", "IAU_VIEWER", "IAU_APPEND", "OPSS", "UCSUMS", "SOAINFRA" ]
        }
    }
}

**Comment by rakillen** [comment]
Hi textanalyticsman -

This document indicates that "Oracle BPM Suite" is the correct name to use for BPM:
https://docs.oracle.com/middleware/12212/lcm/INSOA/GUID-19EF7588-E27A-4B2D-82B4-AEFFBEC2A1A4.htm#INSOA383
It says that selecting this template will automatically include templates for SOA, JRF, etc., so you shouldn't need any additional templates.

I think your typedef file should have:
```
            "baseTemplate": "Basic WebLogic Server Domain",
            "extensionTemplates": [
                "Oracle BPM Suite"
            ],
            "customExtensionTemplates": [ ],
```
Your server groups and schemas appear to be correct, according to our SOA example, but I don't know if there are additional requirements for BPM:
https://github.com/oracle/weblogic-deploy-tooling/blob/master/site/tool_configuration.md#domain-type-definitions

Hope this helps.

**Comment by textanalyticsman** [comment]
Hi @rakillen 

Your suggestion works. I will continue testing and I will raise a new ticket if needed.

Thanks a lot
