### ISSUE TITLE
IdentityAsserter ActiveTypes attribute was set to an illegal value

### ISSUE THREAD

**Issue by knutze** [oracle/weblogic-deploy-tooling#811]
WDT version is 1.9.7 and the WLS version is 12.2.1.4.

When I createDomain using the model file that I discoverDomain in online mode, the domain is created and started successfully.

However, when I try to login in the Administration Console, I get the following error.

> A serious condition has been detected which prevents the proper operation of the Weblogic Administration Console.
> 
> It's likely that this condition is the result of a configuration problem. See the log files for more information.

When I look at the server logs, there are the following messages that seem to be related.

> The IdentityAsserter ActiveTypes attribute was set to an illegal value.

I tried deleting the Realm definition from the model file and rerunning createDomain, and I was able to connect to the Administration Console.

```diff
 topology:
     SecurityConfiguration:
-        Realm:
-            myrealm:
-                AuthenticationProvider:
-                    DefaultAuthenticator:
-                        DefaultAuthenticator:
-                    DefaultIdentityAsserter:
-                        DefaultIdentityAsserter:
-                            ActiveType: [ 'java.lang.String[AuthenticatedUser, weblogic-jwt-token]' ]
```

Is this a bug in WLST?

I would be happy if discoverDomain in online mode did not output unnecessary defaults.

**Comment by CarolynRountree** [comment]
For troubleshooting purposes, did you run discoverDomain in online mode?

This is a WDT bug for the definition of the ActiveType.

**Comment by knutze** [comment]
> For troubleshooting purposes, did you run discoverDomain in online mode?

At first, I was running in WLS 10.3.6.0, and discoverDomain was only available in online mode. Then I had the same problem with WLS 12.2.1.4 and reported that.
