### ISSUE TITLE
Unable to create user without group, even after applying patch

### ISSUE THREAD

**Issue by vdrHorst** [oracle/weblogic-deploy-tooling#818]
Hi,

I am aware of https://github.com/oracle/weblogic-deploy-tooling/blob/master/KnownIssues.md#assigning-security-groups-to-users and applied the given patch successfully. At least now we can create WebLogic users to different groups and skip the default Administrators group. 

However, it is not possible to create a new user without assigning it to any group.
Leaving the GroupMemberOf empty "[ ]" or with "[ !Administrators ]" will not work; throws WLSDPLY-12409: createDomain failed to create the domain: Failed to set attribute GroupMemberOf
Would expect that when we leave out the GroupMemberOf completly, no group memberships would be created. Currently still defaults to Administrators, even when WLS patch is applied.

Currently it is not possible to create users without group assignment. 
Workarround: create dummy group and assign user to that group

**Comment by CarolynRountree** [comment]
fied in 1.9.14
