### ISSUE TITLE
Different behaviour 1.9.8 vs 1.9.7 in create mode

### ISSUE THREAD

**Issue by vdrHorst** [oracle/weblogic-deploy-tooling#819]
After upgrading to 1.9.8 our standard create domain scripts failed, while configuration was left identical. We returned to use 1.9.7 successfully, analysing the issue later:

Until **1.9.7**. is was possible to define the SSL port and disable it all together.
<wdt config snippet>
```
      SSL:
        ListenPort: 7600
        Enabled: false
```
Running **createDomain** would define the portnumber but disable the SSL like we designed.
(it is out of scope why we designed it this way)

From **1.9.8** running **createDomain** with this same configuration raises:
```
WLSDPLY-**12409**: createDomain failed to create the domain: Failed to set attribute ListenPort in path /Server/AS_FRS12214/SSL/NO_NAME_0 to value 7,600: 64016: Attempt to set disabled property.
64016: The property "SSL Listen Port" is disabled on type SSL. 
```
and the same behaviour in **updateDomain**, though different error code:
```
WLSDPLY-**09015**: updateDomain deployment failed: Failed to set attribute ListenPort in path /Server/AS_FRS12214/SSL/AS_FRS12214 to value 7,600: 64016: Attempt to set disabled property.
64016: The property "SSL Listen Port" is disabled on type SSL.
```
_(with hinesight it seemed that WLSDPLY-09015 was also raised in **1.9.7 updateDomain**, but we never used thatone before)_

Would like to understand/know if this was our design flaw, or a change in WDT

**Comment by vdrHorst** [comment]
I do not understand the response/reaction.
We are avoiding re-deployment, that was not the case/issue crought up.
Root problem is that it worked in WDT version 1.9.7 and stopped working in 1.9.8.

**Comment by rakillen** [comment]
A change between WDT 1.9.7 and 1.9.8 resulted in server and cluster components being deployed twice in a single **createDomain** run, to fix a problem with server group assignment. This exposed a problem in WebLogic where the ListenPort attribute for Server/SSL could not be set twice in a certain sequence, resulting in the 64016 error. This latest code change will eliminate the second deployment of those elements, avoiding the underlying problem for **createDomain**.

The problem still occurs with **updateDomain** for Server/SSL, even with older versions of WDT (and older versions of WLS). We have opened a WebLogic bug regarding this issue.

Hope that helps.
