### ISSUE TITLE
Request feature discoverDomain.sh optional usage of -archive_file option

### ISSUE THREAD

**Issue by rssh22** [oracle/weblogic-deploy-tooling#824]
I'd like to request a feature that could be interesting for more users: optional usage of -archife_file option. The motivation is for many purposes the archive is not needed. For example, to review the domain configuration or modify most of the parameters you just need the model file. However, gathering the archive_file is a process that could take several minutes. I do have domains where the process of creating the archive file takes an hour. That is very inconvenient. 

Thank you for evaluating the proposal.

**Comment by ddsharpe** [comment]
I agree with your proposal, and think this would be a valuable option.  Assigning for further investigation.

**Comment by Bneve5** [comment]
It's taking more time skipping the archive than making it. Do you know what is happening?

**Comment by CarolynRountree** [comment]
Could you provide the discover log file from <wlsdeploy>/logs? Would you be able to share the discovered model file?
