### ISSUE TITLE
WDT bug? NO_NAME_O in config.xml

### ISSUE THREAD

**Issue by textanalyticsman** [oracle/weblogic-deploy-tooling#826]
I have created a SOA/BPM domain by using WDT 1.9.8 and I am not able to start the AdminServer. I am using SOA/BPM 12.2.1.4 by the way and last year I was able to create a similar domain without these issues.

Below you can see a snippet of confg.xml file, which is plenty of elements with the tag `<name>NO_NAME_0</name>`

![image](https://user-images.githubusercontent.com/25264959/106295506-d2e41200-6250-11eb-8b18-793ef2dc1ed6.png)

**Comment by rakillen** [comment]
Hello textanalyticsman -

Offline WLST requires that new domain elements be given a name as part of the `create` command. In cases where an element  doesn't have a discernable name, WDT often uses NO_NAME_0, and sometimes that propagates to the config.xml. In most cases, this does not cause any problems.

Is this question in reference to the AdminServer start failure from issue #825 ? I don't think these name fields are related to that issue, but we'll look into it.

**Comment by textanalyticsman** [comment]
Hello @rakillen ,

Actually the issue in this case was the fact that AdminServer was not able to start because it was missing a store for transaction logs. Thus, I checked the AdminServer and I saw those NO_NAME0 tags and I decided to report it. However, if you see the previous picture you will see transaction-log-jdbc-store is missing a datasource and this was caused because of the model extracted with WDT as you can see below it was missing a data source.

´´´
            TransactionLogJDBCStore:
                Enabled: true
´´´

I have added the datasource manually within the model and I am testing it.

This is not related to the other issue I have reported today

**Comment by textanalyticsman** [comment]
I have tested by fixing the model manually and it works.

By fixing manually I mean adding DataSource element that the model was missing as you can see on below picture.

![image](https://user-images.githubusercontent.com/25264959/106307827-1e51ec80-6260-11eb-9f6f-9c745098ed09.png)

The original model generated by WDT was missing it.

**Comment by rakillen** [comment]
I'm able to reproduce this with online discover.
ServerTemplate / TransactionLogJDBCStore / DataSource is not discovered.
