### ISSUE TITLE
Online discoverDomain does not model SAFRemoteContext properly

### ISSUE THREAD

**Issue by textanalyticsman** [oracle/weblogic-deploy-tooling#834]
Hello,

I have discovered a SOA/BPM 12.2.1.4 domain by using WDT 1.9.8 and then after creating the domain I have found this issue with SAF while a BPM server was starting.

> <The JMS store-and-forward (SAF) forwarder failed to connect to the remote destination "null/jms/ExamRemoteInfoQueue", because of j
avax.naming.NameNotFoundException: Unable to resolve 'jms.ExamRemoteInfoQueue'. Resolved 'jms'; remaining name 'ExamRemoteInfoQueue'
        at webExamRemotec.jndi.internal.BasicNamingNode.newNameNotFoundException(BasicNamingNode.java:1292)
        at webExamRemotec.jndi.internal.BasicNamingNode.lookupHere(BasicNamingNode.java:354)

I have checked the model and I have found the SAFImportedDestinations is missing a reference to SAFRemoteContext. Below you can see an example of a proper model I extracted by using the previous version of WDT. Just to be clear, my current model is missing the element in yelow.

![image](https://user-images.githubusercontent.com/25264959/106882696-584b4480-66df-11eb-94e2-522a50f93a75.png)

I will fix the model manually and I will test it again.

Best regards,
TAM

**Comment by textanalyticsman** [comment]
After fixing the model manually the issue has been solved. However, it would be goo if extractDomain online could do it automatically

**Comment by rakillen** [comment]
hi textanalytiicsman - 
I'm able to reproduce this with online discover.
It appears to be related to issue #826 .
Attributes that reference other MBeans are not being discovered correctly.

**Comment by textanalyticsman** [comment]
Thanks a lot.
