### ISSUE TITLE
updateDomain has issues with attribute 'remove_deleted_clusters_and_servers'

### ISSUE THREAD

**Issue by zeusbaba** [oracle/weblogic-deploy-tooling#842]
I'm experimenting with `updateDomain` to add the ability for updating/extending existing domain.  
However, I get an error at the end of the `updateDomain` process.  

Running `updateDomain` with;  
```
$WDT_HOME/bin/updateDomain.sh \
    -oracle_home $ORACLE_HOME \
    -domain_home /u01/theosb/domain/theosb_domain \
    -domain_type OSB \
    -model_file WDT_OSB_template-update.yaml \
    -admin_user weblogic \
    -admin_url t3://theosbadm-testX.elhub.cloud:8011
```
p.s. `WDT_OSB_template-update.yaml`  contains _only_ LDAP Providers, `SecurityConfiguration`  

The whole `updateDomain` process seems to succeed, however at the end throws an error which blocks it from applying those changes.  

```
... 
####<Feb 18, 2021 11:51:14 AM> <INFO> <SecurityProviderCreator> <_create_named_subtype_mbeans> <WLSDPLY-12118> <Creating AuthenticationProvider of type DefaultIdentityAsserter with name DefaultIdentityAsserter at location /SecurityConfiguration/theosb_domain/Realms/myrealm>
Problem invoking WLST - Traceback (innermost last):
  File "/u01/binaries/elhosb/weblogic-deploy/lib/python/update.py", line 303, in ?
  File "/u01/binaries/elhosb/weblogic-deploy/lib/python/update.py", line 288, in main
  File "/u01/binaries/elhosb/weblogic-deploy/lib/python/update.py", line 101, in __update
  File "/u01/binaries/elhosb/weblogic-deploy/lib/python/update.py", line 160, in __update_online
  File "/u01/binaries/elhosb/weblogic-deploy/lib/python/wlsdeploy/tool/deploy/topology_updater.py", line 101, in update
AttributeError: 'wlsdeploy.tool.util.topology_helper.TopologyHelper' object has no attribute 'remove_deleted_clusters_and_servers'
```

p.s. I'm using `WDT` built from master branch 12feb2021  

I did a quick research on this repo, and I noticed that #820 is when `remove_deleted_clusters_and_servers` is introduced. not sure if it is related that error though.  

Your help/feedback is much appreciated

**Comment by rakillen** [comment]
hi zeusbaba -

I ran online update with release 1.9.9, and the method remove_deleted_clusters_and_servers is being called successfully, and I can see it present in the unzipped `topology_helper.py` source file. Is it possible that you have an older version of the **class** file 
```
weblogic-deploy\lib\python\wlsdeploy\tool\util\topology_helper$py.class
```
from a previous build in your target directory? WLST runtime does not seem to automatically detect when there is a newer source files and re-compile. I'd recommend completely removing the target directory before each build.

Hope that helps.

**Comment by zeusbaba** [comment]
Thanks for your response.  
I just check the WDT binaries I've on the server, and it seems that I'm already using `1.9.10-SNAPSHOT` 
```
ls -l /u01/binaries/theosb/weblogic-deploy/
total 24
-rw-r-----. 1 theosb theosb 4673 Nov 11 12:31 LICENSE.txt
-rw-r-----. 1 theosb theosb   39 Feb 15 10:59 VERSION.txt
drwxr-x---. 2 theosb theosb 4096 Feb 16 10:12 bin
drwxr-x---. 2 theosb theosb   32 Feb 16 10:12 etc
drwxr-x---. 6 theosb theosb 4096 Feb 16 10:12 lib
drwxr-x---. 2 theosb theosb 4096 Feb 18 11:51 logs
drwxr-x---. 2 theosb theosb   70 Feb 16 10:12 samples

$ cat  /u01/binaries/theosb/weblogic-deploy/VERSION.txt
WebLogic Deploy Tooling 1.9.10-SNAPSHOT
```

Nevertheless, I'll try your suggestion by deleting and reinstalling WDT binaries. I'll share the result of this soon

**Comment by zeusbaba** [comment]
Your assumption is confirmed. 
Deleting and reinstalling WDT binaries resolved this issue.  

Thanks again for your help
