### ISSUE TITLE
Unable to create user with Weblogic deploy tool and Password digest

### ISSUE THREAD

**Issue by korolar** [oracle/weblogic-deploy-tooling#851]
Using: WebLogic Deploy Tooling 1.9.1 and WL 12.2.1.4

Creating a docker image using yml files and deploy tool to create domain, users etc.
```
The following is set:
          AuthenticationProvider:
                    'DefaultAuthenticator':
                        DefaultAuthenticator:
                            ControlFlag: OPTIONAL
                            PasswordDigestEnabled: true
                    'DefaultIdentityAsserter':
                        DefaultIdentityAsserter:
                         ActiveType: [ 'wsse:PasswordDigest', 'weblogic-jwt-token', 'AuthenticatedUser' ]
```
Users are added in the yml file as well. 

After the domain is created and started. I cannot call any WS with PasswordDigest untill I reset the password for that user in the Realm.

**Comment by CarolynRountree** [comment]
Could you provide the full model? I can provide you a slack channel or email address if you do not want to attach to the issue.

**Comment by korolar** [comment]
> Could you provide the full model? I can provide you a slack channel or email address if you do not want to attach to the issue.

Slack channel please.

**Comment by xiancao** [comment]
here is the stack channel for WDT support: wls-wdt-support

**Comment by korolar** [comment]
Hi,
I tried logging into https://wls-wdt-support.slack.com/ but it doesn't work.

I am a newbie in Slack so kind of lost how to connect to a Slack channel.

Zoran Brajkovic

**Comment by xiancao** [comment]
Sorry, this channel is internal to Oracle customers. Can you try https://oracle-weblogic.slack.com/ and search channel #operator?

**Comment by ddsharpe** [comment]
@korolar Try this link https://oracle-weblogic.slack.com/archives/CE3M4RLBE

**Comment by korolar** [comment]
Hi,
i cannot connect to any of the suggested channels - it says that my user
doesn't exist in that channel.

***@***.***

Zoran Brajkovic
Korolar d.o.o.
***@***.***
Ilica 425, 10000 Zagreb

**Comment by korolar** [comment]
I cannot access any of the channels..

**Comment by korolar** [comment]
> Could you provide the full model? I can provide you a slack channel or email address if you do not want to attach to the issue.

Maybe you can share email address for communication?

**Comment by CarolynRountree** [comment]
carolyn.rountree@oracle.com

**Comment by CarolynRountree** [comment]
Thank you for the model information. We have taken a look at how to enhance WDT to do a single pass for PasswordDigest. This is complicated and will not make the next release, but a future release.

The second issue, we don't currently support adding users in update, only in create.

**Comment by CarolynRountree** [comment]
@korolar We made some changes in 1.9.14 that might have fixed your issue. Can you try this out with latest releae?

**Comment by CarolynRountree** [comment]
[weblogic-deploy.zip](https://github.com/oracle/weblogic-deploy-tooling/files/7856176/weblogic-deploy.zip)

Could you use this file to discover if WebserviceSecurity is in your domain - This might be the missing piece to define passworddigest to the domain. Attach the model or the snippet of the model to email carolyn.rountree@oracle.com

**Comment by robertpatrick** [comment]
@korolar any progress?  Please let us know.

**Comment by korolar** [comment]
Hi,
We have some 'rush' at work. I will try to do this in the next week or two.

pet, 4. velj 2022. 23:40 Robert Patrick ***@***.***> je
napisao:

**Comment by korolar** [comment]
Hi Robert/Carolyn

I just sent the yml file to Carolyn mails.

Zoran Brajkovic
Korolar d.o.o.
***@***.***
Ilica 425, 10000 Zagreb

**Comment by ddsharpe** [comment]
There does not appear to be anything that we can do with WDT that will allow configuration of the user password that supports PasswordDigest.  I am going to close this request for WDT until such time as there is an enhancement in WebLogic Server security that allows offline loading of embedded LDAP.
