### ISSUE TITLE
JMSServer/PersistentStore is not discovered.

### ISSUE THREAD

**Issue by brahankv** [oracle/weblogic-deploy-tooling#856]
With Online Discover domain, JMSServer/PersistentStore is not discovered.
```
####<Mar 8, 2021 3:48:47 PM> <INFO> <JmsResourcesDiscoverer> <get_jms_servers> <WLSDPLY-06471> <Adding JMS Server SOAJMSServer_auto_1>
####<Mar 8, 2021 3:48:48 PM> <INFO> <Discoverer> <_populate_model_parameters> <WLSDPLY-06154> <Attribute PersistentStore for model folder at location /JMSServer is not in the lsa map and is not defined with get to retrieve the attribute value>
```
As the PersistentStore is not discovered, it is defulted to FileStore instead of JDBCStore.
Adding manually PersistentStore in the model, did not set the PersistentStore in the created domain still defaults to FileStore.

**Comment by ddsharpe** [comment]
Fixed by #850
