### ISSUE TITLE
XACMLAuthorizer - Removing and adding a policy

### ISSUE THREAD

**Issue by nocheinAndi** [oracle/weblogic-deploy-tooling#858]
Dear WDT team,

I really like this tool and I was able to cover most of my WebLogic configuration. But the following python snippet I wasn't able to put into the YAML file so far. Is there any possibility to do so?

`cd('/SecurityConfiguration/base_domain/Realms/myrealm/Authorizers/XACMLAuthorizer')
cmo.removePolicy("type=<jdbc>")
cmo.createPolicy('type=<jdbc>', 'Grp(Administrators)')`

I know that there's a security configuration section, but I have clearly no idea how to add something like that.

Thanks for any ideas!

**Comment by ddsharpe** [comment]
@nocheinAndi No. Currently, there is not a way to accomplish this.  The security data is very different than configuration data in WebLogic Server.  We did a partial implementation of some of the security features, but not all.  We do not have an ETA for this option at this time.

**Comment by nocheinAndi** [comment]
@ddsharpe Thanks for answering! Until this is solved I would then keep it as it is.

**Comment by robertpatrick** [comment]
Close, no plans to implement
