### ISSUE TITLE
Float is not getting converted to string for ssl_version

### ISSUE THREAD

**Issue by preethignanesh** [oracle/weblogic-deploy-tooling#868]
**One of the properties to be specified for ATP DB to add a datasource is oracle.net.ssl_version. This is a float number being specified as 1.2. This float value is not getting converted to string value in the latest WDT version of 1.9.11.
If this is passed as - 
oracle.net.ssl_version:
              Value: '1.2'

Conversion from float to string is not happening and we are seeing the following error message - 
 13:55:43  Issue Log for validateModel version 1.9.11 running WebLogic version 12.2.1.4.0 offline mode:
13:55:43  
13:55:43  WARNING Messages:
13:55:43  
13:55:43          1. WLSDPLY-05017: Expected value of the Value attribute at location resources:/JDBCSystemResource/mydatasource/JdbcResource/JDBCRESOURCE-0/JDBCDriverParams/JDBCDRIVERPARAMS-0/Properties/oracle.net.ssl_version to be a string data type, but it was a <type 'float'>
13:55:43  
13:55:43  Total:       WARNING :     1    SEVERE :     0
13:55:43  
13:55:43  [91mvalidateModel.sh completed but with some issues (exit code = 1)
 
To workaround this we need to specify a space after 2 before closing the quotes. If its specified this way, then conversion to string works perfectly.

**Comment by ddsharpe** [comment]
Tested, cannot reproduce.  Please delete the install folder before installing the new version.  The PYC files are not regenerated by WLST if they already exist5.

**Comment by preethignanesh** [comment]
When I try to run the validateModel script directly, I dont see the issue and it works perfectly fine. But when I try to run the imagetool update command to create the MII image which internally invokes the WDT validateModel script, thats when I am seeing the issue still.

**Comment by ddsharpe** [comment]
I have tried with create, update, and validate.  I verified that the same tests failed on the previous version, 1.9.10.  Running these tests on 1.9.11 recognized the float correctly.  I cannot get the current release to fail.  All of my tests are using a JDBC property value like:
```                    Properties:
                        customProp: 
                            Value: '1.0'
```

**Comment by preethignanesh** [comment]
As mentioned previously, issue occurs when the imagetool update command is invoking the WDT validateModel script when creating the MII image. Update command does a copy of the WDT binart to /tmp/imagetool location and unzips the contents without clearing out the previously installed binaries. If the previous install contained the old version of pyc classes they still remain in the install folder which is causing the issue.

This looks to be of more WIT issue rather than WDT. I guess we can close this issue on WDT and open a new issue on WIT. Please suggest.

**Comment by preethignanesh** [comment]
Closing the current issue as WDT validatemodel is working as expected in 1.9.11 version
