### ISSUE TITLE
LogFilter not found

### ISSUE THREAD

**Issue by antobaldu** [oracle/weblogic-deploy-tooling#871]
Hello,
 I wanted to configure a  LogFilter and I added in my model.yaml

```
topology:
         Name: "MyDomain"
         AdminServerName: "admin"
         ProductionModeEnabled: "true"
         LogFilter:
            "wlsDefaultLogFilter":
              FilterExpression: '(MSGID = ''BEA-090779'')'
          Server:
              "admin":
                ListenPort: "7001"
                ListenAddress: "myhost.yyy"
                Log:
                  DomainLogBroadcastSeverity: Off
                  LogFileFilter: wlsDefaultLogFilter
                  StdoutFilter: wlsDefaultLogFilter
                  StdoutSeverity: Critical
                  DomainLogBroadcastFilter: wlsDefaultLogFilter
            .....
```

The "validateModel" is ok but when I try to create a domain I have the following error:

####<Apr 15, 2021 11:33:36 AM> <SEVERE> <create> <main> <WLSDPLY-12409> <createDomain failed to create the domain: LogFilter wlsDefaultLogFilter not found in location topology:/LogFilter>

Issue Log for createDomain version 1.9.11 running WebLogic version 14.1.1.0.0 offline mode:

SEVERE Messages:

        1. WLSDPLY-12409: createDomain failed to create the domain: LogFilter wlsDefaultLogFilter not found in location topology:/LogFilter

Without the LogFilter the creation of the domain works. 

Regards
Antonella

**Comment by ddsharpe** [comment]
Reproduced, and investigating.
