### ISSUE TITLE
Removed server glitch in domain servers directory

### ISSUE THREAD

**Issue by pwninja** [oracle/weblogic-deploy-tooling#903]
I am running using WDT for OSB domain installation.
In the model file I am removing default server by using the exclamation mark notation:
```
    Server:
        # Delete the osb server, which is created by default
        '!osb_server1':
```
This gets interpreted properly that this server is removed.
However, in domain's home servers directory I can find a catalog with "!osb_server" name:
```
-bash-4.2$ ls -al servers
total 8
drwxr-x---.  8 ninjainst ninjainst  143 May 25 12:29 .
drwxr-x---. 36 ninjainst ninjainst 4096 May 25 12:30 ..
drwxr-x---.  9 ninjainst ninjainst   95 May 25 12:28 AdminServer
-rw-r-----.  1 ninjainst ninjainst   14 May 25 12:29 AdminServerTag
drwxr-x---. 10 ninjainst ninjainst  108 May 25 12:31 OsbServer01
drwxr-x---. 10 ninjainst ninjainst  108 May 25 12:32 OsbServer02
drwxr-x---.  3 ninjainst ninjainst   22 May 25 12:27 OsbServer03
drwxr-x---.  3 ninjainst ninjainst   22 May 25 12:27 OsbServer04
drwxr-x---.  3 ninjainst ninjainst   22 May 25 12:27 !osb_server1
```
It contains security and boot.properties file:
```
-bash-4.2$ ls -lR servers/\!osb_server1/
servers/!osb_server1/:
total 0
drwxr-x---. 2 ninjainst ninjainst 29 May 25 12:27 security

servers/!osb_server1/security:
total 4
-rw-r-----. 1 ninjainst ninjainst 157 May 25 12:27 boot.properties
```
I think that at some point WDT ignores the exclamation mark and treats this entry as something to be created.

I am using WDT 1.9.11 version.

**Comment by pwninja** [comment]
It turns out that this code part of domain_creator.py doesn't consider if the server name is "is_delete_name" (from model_helper.py):
```
        server_nodes = dictionary_utils.get_dictionary_element(self._topology, SERVER)
        servers = [self._admin_server_name]

        for model_name in server_nodes:
            name = self.wlst_helper.get_quoted_name_for_wlst(model_name)
            servers.append(name)

        admin_username = self.aliases.decrypt_password(admin_username)
        admin_password = self.aliases.decrypt_password(admin_password)
        encrypted_username = encryptionService.encrypt(admin_username)
        encrypted_password = encryptionService.encrypt(admin_password)
        for server in servers:
            properties = Properties()
            properties.put("username", encrypted_username)
            properties.put("password", encrypted_password)
            file_directory = self._domain_home + "/servers/" + server + "/security"
            file_location = file_directory + "/boot.properties"
```

**Comment by pwninja** [comment]
@rakillen Hi! I can confirm that original issue is fixed (in 1.9.14 version), but I am not sure if in the right way. The reason is that if I have two machines with some OsbServers, then after domain installation I can see folders for all OsbServers in the AdminServer machine. Those that are targetted for other machines have only security/boot.properties file which is "redundant".

**Comment by CarolynRountree** [comment]
Please attach details about what you are seeing in the folder along with the correct model file.

**Comment by pwninja** [comment]
Attaching the ls result of domain_home/servers and topology part of the WDT model:
[wdt-issue-903-domain-servers.txt](https://github.com/oracle/weblogic-deploy-tooling/files/6638127/wdt-issue-903-domain-servers.txt)
[wdt-issue-903-topology.txt](https://github.com/oracle/weblogic-deploy-tooling/files/6638128/wdt-issue-903-topology.txt)

**Comment by CarolynRountree** [comment]
WDT does not create boot.properties on machines other than the admin server. this can be expected if you started your managed server, WLS pushes the boot.properties

**Comment by jshum2479** [comment]
If i understand you correctly.   This is the expected behavior. 

1.  creating the boot.properies are really targeted for developer environment.  If you specify production mode in the model, we do not generate boot.properties

2.  Machine in WDT/WLS is just a construct.   This is not a directly pointing to any particular physical machine.  So, it's not like we have a directory structure machine-A:.../servera|serverb/...

3.  When WDT created a domain it creates the entire domain structure in local disk,   just like any on premise domain $domain/...   So if you zip up the domain structure, you will always have $domain/servers/<server name>/....  for every sever.  

4.  You can always manually remove the unwanted $domain/servers/<server>  directory from each machine or use production mode in the model.

**Comment by pwninja** [comment]
I can confirm that in production mode it works as you wrote and it is acceptable. Thanks!
