### ISSUE TITLE
FMW OSB datasources configuration

### ISSUE THREAD

**Issue by pwninja** [oracle/weblogic-deploy-tooling#918]
I am installing an OSB domain using WDT 1.9.14. By default there are several datasources created (followed by the target):

- LocalSvcTblDataSource	AdminServer
- mds-owsm - AdminServer, OsbCluster
- opss-audit-DBDS - AdminServer, OsbCluster
- opss-audit-viewDS - AdminServer, OsbCluster
- opss-data-source - AdminServer, OsbCluster
- OraSDPMDataSource - OsbCluster
- SOADataSource - AdminServer, OsbCluster
- SOALocalTxDataSource - AdminServer
- wlsbjmsrpDataSource - AdminServer, OsbCluster
- WLSSchemaDataSource - AdminServer, OsbCluster

I can override some of the available settings by defining resources/JDBCSystemResource with the same name. However, if I specify a Target field the value provided will be added to the default target listed above, instead of replacing it.

Our concern here is that we're not sure whom to trust in terms of the proper datasources targetting and that we cannot fully control it from WDT.

From this link we can see some differences of datasources targets:
https://docs.oracle.com/en/middleware/fusion-middleware/12.2.1.4/soedg/targeting-applications-and-resources-servers.html#GUID-D3D3393A-8501-4202-97EB-D76177854DE0

- LocalSvcTblDataSource	AdminServer, ESS_Cluster
- mds-owsm - AdminServer, WSM-PM_Cluster
- opss-audit-DBDS - AdminServer, BAM_Cluster, ESS_Cluster, OSB_Cluster, SOA_Cluster, WSM-PM_Cluster
- opss-audit-viewDS - AdminServer, BAM_Cluster, ESS_Cluster, OSB_Cluster, SOA_Cluster, WSM-PM_Cluster
- opss-data-source - AdminServer, BAM_Cluster, ESS_Cluster, OSB_Cluster, SOA_Cluster, WSM-PM_Cluster
- OraSDPMDataSource - BAM_Cluster, OSB_Cluster, SOA_Cluster
- SOADataSource - AdminServer, OSB_Cluster, SOA_Cluster
- SOALocalTxDataSource - SOA_Cluster
- wlsbjmsrpDataSource - AdminServer, OSB_Cluster

If we should trust official Oracle documentation we'd like to untarget AdminServer from SOALocalTxDataSource, but WDT doesn't allow us to do it.

**Comment by CarolynRountree** [comment]
Try 

Target: "!AdminServer,TargetIWant"   where ! says delete from list.

**Comment by pwninja** [comment]
Thanks @CarolynRountree - it worked this way.
So which settings should we trust? Default ones from WDT or those from Oracle?

**Comment by ddsharpe** [comment]
@pwninja As to what the correct settings are for a SOA/OSB domain, the WDT/WLS team does not have the knowledge or training for that answer.
