### ISSUE TITLE
vadlidateModel only accepts *one* -variable_file <file>, whereas createDomain accepts multiple in commasep list

### ISSUE THREAD

**Issue by kenneth-olwing** [oracle/weblogic-deploy-tooling#920]
createDomain.sh can be run with '-variable_file file1,file2,...' but validateModel.sh accepts only one file, no list. Seems like an oversight, I would expect the same capabilities in validateModel.

Seen with
WDT 1.9.15
Java 11.0.11.0.2+1-LTS-1
WLS 14.1.1.0.201208

**Comment by ddsharpe** [comment]
Agreed, will need to look into this.  Thanks Kenneth.

**Comment by kenneth-olwing** [comment]
Thank you, have a good one.
