### ISSUE TITLE
1.9.15: Exception during validateModel (AttributeError: 'str' object has no attribute 'iteritems')

### ISSUE THREAD

**Issue by kenneth-olwing** [oracle/weblogic-deploy-tooling#921]
A domain created by other means and runs apparently happily. Domain was stopped, and a discovery was made against it. The resulting yaml file fails validation with exception. Obviously the full yaml is larger, but I've narrowed it down to this only:

topology:
    SecurityConfiguration:
      Realm:
        myrealm:
          AuthenticationProvider:
            DefaultIdentityAsserter:
              DefaultIdentityAsserter: ~

I'm not knowledgeable enough in the MBeans involved, but it sort of looks suspicious to me, e.g. a repeat of the same name, and with an undefined value?

Running a yaml file with this content through validateModel causes the stacktrace:

####<Jun 17, 2021 2:48:43 PM> <INFO> <Validator> <__validate_model_section> <WLSDPLY-05008> <Validating the topology section of the model file>
Traceback (most recent call last):
  File "/home/nfs/oktk/ws/wdtglue-docs/wdt/weblogic-deploy-1.9.15/lib/python/validate.py", line 198, in <module>
    main(sys.argv)
  File "/home/nfs/oktk/ws/wdtglue-docs/wdt/weblogic-deploy-1.9.15/lib/python/validate.py", line 174, in main
    __perform_model_file_validation(model_file_name, model_context)
  File "/home/nfs/oktk/ws/wdtglue-docs/wdt/weblogic-deploy-1.9.15/lib/python/validate.py", line 174, in main
    __perform_model_file_validation(model_file_name, model_context)
  File "/home/nfs/oktk/ws/wdtglue-docs/wdt/weblogic-deploy-1.9.15/lib/python/validate.py", line 119, in __perform_model_file_validation
    model_validator.validate_in_standalone_mode(model_dictionary, variable_map,
  File "/home/nfs/oktk/ws/wdtglue-docs/wdt/weblogic-deploy-1.9.15/lib/python/validate.py", line 119, in __perform_model_file_validation
    model_validator.validate_in_standalone_mode(model_dictionary, variable_map,
  File "/home/nfs/oktk/ws/wdtglue-docs/wdt/weblogic-deploy-1.9.15/lib/python/wlsdeploy/tool/validate/validator.py", line 128, in validate_in_standalone_mode
    self.__validate_model_file(cloned_model_dict, variable_map, archive_file_name)
  File "/home/nfs/oktk/ws/wdtglue-docs/wdt/weblogic-deploy-1.9.15/lib/python/wlsdeploy/tool/validate/validator.py", line 240, in _Validator__validate_model_file
    self.__validate_model_section(model.get_model_topology_key(), model_dict,
  File "/home/nfs/oktk/ws/wdtglue-docs/wdt/weblogic-deploy-1.9.15/lib/python/wlsdeploy/tool/validate/validator.py", line 403, in _Validator__validate_model_section
    self.__validate_section_folder(section_dict_value, validation_location)
  File "/home/nfs/oktk/ws/wdtglue-docs/wdt/weblogic-deploy-1.9.15/lib/python/wlsdeploy/tool/validate/validator.py", line 542, in _Validator__validate_section_folder
    self.__process_model_node(model_node, validation_location)
  File "/home/nfs/oktk/ws/wdtglue-docs/wdt/weblogic-deploy-1.9.15/lib/python/wlsdeploy/tool/validate/validator.py", line 588, in _Validator__process_model_node
[HKmT14.zip](https://github.com/oracle/weblogic-deploy-tooling/files/6670325/HKmT14.zip)

    self.__validate_section_folder(value, new_location)
  File "/home/nfs/oktk/ws/wdtglue-docs/wdt/weblogic-deploy-1.9.15/lib/python/wlsdeploy/tool/validate/validator.py", line 490, in _Validator__validate_section_folder
    self.__process_model_node(value_dict, new_location)
  File "/home/nfs/oktk/ws/wdtglue-docs/wdt/weblogic-deploy-1.9.15/lib/python/wlsdeploy/tool/validate/validator.py", line 588, in _Validator__process_model_node
    self.__validate_section_folder(value, new_location)
  File "/home/nfs/oktk/ws/wdtglue-docs/wdt/weblogic-deploy-1.9.15/lib/python/wlsdeploy/tool/validate/validator.py", line 519, in _Validator__validate_section_folder
    self.__process_model_node(value_dict, new_location)
  File "/home/nfs/oktk/ws/wdtglue-docs/wdt/weblogic-deploy-1.9.15/lib/python/wlsdeploy/tool/validate/validator.py", line 586, in _Validator__process_model_node
    self.__validate_attributes(value, valid_attr_infos, new_location)
  File "/home/nfs/oktk/ws/wdtglue-docs/wdt/weblogic-deploy-1.9.15/lib/python/wlsdeploy/tool/validate/validator.py", line 661, in _Validator__validate_attributes
    for attribute_name, attribute_value in attributes_dict.iteritems():
AttributeError: 'str' object has no attribute 'iteritems'

validateModel.sh failed (exit code = 255)

I'm guessing one of three things:
1) The discoverDomain makes a mistake and writing wrong data.
2) The yaml is in fact correct, but the validation makes a mistake
3) My domain is somehow corrupt (causing the discover to write stuff it shouldn't). But domain is otherwise running etc etc.

Any help appreciated, thanks

ken1

**Comment by kenneth-olwing** [comment]
Sorry, obviously the yaml should be indented:

<pre>
topology:
     SecurityConfiguration:
         Realm:
             myrealm:
                 AuthenticationProvider:
                     DefaultIdentityAsserter:
                         DefaultIdentityAsserter: ~
</pre>

**Comment by CarolynRountree** [comment]
What is the tilde in the attribute field? Try removing the tilde and see if it works.

**Comment by kenneth-olwing** [comment]
Hi, thanks for responding.

The tilde is the YAML way to say 'undefined' or 'null', and discoverModel actually spits it out just like shown. And yes, my workaround right this minute is simply to remove the two last lines (as it seems just to be the defaults anyway), and the validation is happy (well, I do have other issues, but still working through them).

But as I say, if discoverModel generates it, I'm guessing it goes south either there or if it indeed is the right thing to generate, then the validation does something wrong with it. Without being certain my guess would be the former; I'm not a guru on the MBean ref docs, but I can't see any reason to have a null DefaultIdentityAsserter attribute on another DefaultIdentityAsserter...? Nothing leaps out when trying too look in the console reagarding this.

ken1

**Comment by CarolynRountree** [comment]
Both DefaultIdentityAsserter are name fields. When creating a Security provider, you give it three fields, the type of provider (here it is an Authentication Provider), a name for the provider (one of the DefaultIdentityAsserter) and then the short or qualified (short name here) of the provider interface name. I have never seen discover put a tilde on the end of one of the names. We wrote our own shortened yaml parser to work with python and jython and it doesn't deal with tilde fields. Particularly on a name field. Please let me know what else you are having problems working through and I will see how I can hellp.

**Comment by kenneth-olwing** [comment]
Ok, thanks. Well, it *is* the discoverModel that puts the tilde there, so...:-/

It appears that I must remove both of the lines entirely; if I remove just the tilde, I still get the stacktrace. If I remove just the last line, I get a SEVERE "1. WLSDPLY-05038: Expected a section with subfolders and attributes in model location topology:/SecurityConfiguration/Realm/myrealm/AuthenticationProvider/DefaultIdentityAsserter", and I guess this makes sense as it really is missing information that should be there.

Thanks, I may return with further issues, but I'm trying to whittle them down to something minimal and recreatable first!

**Comment by kenneth-olwing** [comment]
Looking further into this, I would now like to state that it is the YAML generator during discovery that is at fault. As I've already shown, it *does* generate the 'tilde' value. However, if I request a JSON file instead since it's more stringent, I get this:

<pre>
                        "DefaultIdentityAsserter" : {
                            "DefaultIdentityAsserter" : {
                            }
</pre>

Which, if parsed in and rewritten to YAML becomes:

<pre>
          DefaultIdentityAsserter:
              DefaultIdentityAsserter: {}
</pre>
 
I.e. the value is an *empty object*, rather than a *null value*. Valdating this YAML is fine.

So the YAML generator seems to do the wrong thing and produces something that is not fully 'round-trippable' in this case so it would be useful to fix.

The generated JSON does raise a small question. It generates items like this as an example:

<pre>
     "RotateLogOnStartup" : "false"
</pre>

I understand this to be a boolean setting, which means that ideally, the JSON should be:

<pre>
     "RotateLogOnStartup" : false
</pre>

I.e. note the missing citation marks, making it a false boolean value rather than a string with 'false' in it. Just checking in case it is important, but as it appears to work, I assume that the MBeans (or WDT) parse this to booleans as needed?

**Comment by CarolynRountree** [comment]
About the false, WDT knows that it is a boolean value and not a string and will convert it correctly during createDomain.

I was not able to recreate your scenario. Is there anyway you can zip up your domain directory and email it to carolyn.rountree@oracle.com.

**Comment by CarolynRountree** [comment]
Still unable to create your scenario with your provided domain. The SecurityConfiguration looks perfect.
```
    SecurityConfiguration:
        NodeManagerPasswordEncrypted: '--FIX ME--'
        NodeManagerUsername: system
        Realm:
            myrealm:
                DelegateMBeanAuthorization: true
                Auditor:
                    WlstoolsCfgAuditor:
                        weblogic.management.security.audit.Auditor:
                AuthenticationProvider:
                    DefaultAuthenticator:
                        DefaultAuthenticator:
                            ControlFlag: SUFFICIENT
                    DefaultIdentityAsserter:
                        DefaultIdentityAsserter:
```

**Comment by kenneth-olwing** [comment]
It pains me to admit, but no matter what I try now I can't get it to misbehave now :-(.

Good in a way, but it was very consistent the other day and it is really irritating not to be able to repro it now. I can only surmise a corrupt domain before or a number of changes to the jdk/wls used, and then I switched to using JSON as the output so...I have no idea what's up right now.

I'm gonna close this for now. Assuming I can move forward here I anticipate discovery of a lot of domain; if this ever pops up again, I'll try to nail it down into something reproable then.

Thanks for your help and sorry for appearing to waste your time.

**Comment by kenneth-olwing** [comment]
Not reproable now.
