### ISSUE TITLE
Discover of application PlanPath entries as well as use of them in creating domain goes bonkers

### ISSUE THREAD

**Issue by kenneth-olwing** [oracle/weblogic-deploy-tooling#923]
WDT 1.9.15, WLS14

A discovery of a domain finds a plan for an app, resulting in a model with this:
<pre>
    Application:
      HelloKitty_ear:
        DeploymentOrder: 95
        ModuleType: ear
        PlanPath: '@@DOMAIN_HOME@@/plan/ear_HelloKitty_plan.xml'
        SourcePath: wlsdeploy/applications/HelloKitty.ear
        Target: HKmT14_S2
</pre>
In the original domain, the file is there. However trying to use this model causes errors like this:
<pre>
1. WLSDPLY-06395: Cannot add application binary for application HelloKitty_ear to archive file. The application was removed from target /home/nfs/oktk/slask/conv2wdt/HKmT14.wdtglue/HKmT14/20210620T215958Z/domain/@@DOMAIN_HOME@@/plan/ear_HelloKitty_plan.xml : WLSDeployArchive /home/nfs/oktk/slask/conv2wdt/HKmT14.wdtglue/HKmT14/20210620T215958Z/discover/20210620T220042Z/WDT.zip unable to add file /home/nfs/oktk/slask/conv2wdt/HKmT14.wdtglue/HKmT14/20210620T215958Z/domain/@@DOMAIN_HOME@@/plan/ear_HelloKitty_plan.xml to the archive because the file does not exist
</pre>

Seems like two separate problems:

- discoverModel
I think I would have expected the plan file(s) to be included in the discovered archive, and hence have them listed as something like 'wlsdeploy/plan/...' or whatever is suitable, and hence have them read from the unpacked archive.

- createDomain
Apparently createDomain doesn't do the @@DOMAIN_HOME@@ replacement for a PlanPath entry. Now, it obviously wouldn't have helped here since the file(s) isn't there anyway. So maybe it's not really a problem here, just the initial issue with discovery.

Any suggestions welcome :-)

Thank you

**Comment by CarolynRountree** [comment]
I am attempting to determine where this went wrong and need to know if you had a PLAN_DIR setting on the application in your original domain?

**Comment by kenneth-olwing** [comment]
Hi, thanks for helping,

No, I can't find any trace of having that set. As it happens while the domain I dropbox'ed you is another domain, it produces the same problem if that helps.

**Comment by kenneth-olwing** [comment]
An observation is that if discover the domain in it's 'real' location, I get stuff like:
<pre>
PlanPath: '/home/nfs/oktk/slask/emptydom/XYmT14/@@DOMAIN_HOME@@/plan/web_HelloWorld_plan.xml'
</pre>
but if I copy the domain elsewhere I get more sensible stuff like:
<pre>
PlanPath: /home/nfs/oktk/slask/emptydom/XYmT14/plan/web_HelloWorld_plan.xml
</pre>

Anyway, If I run a discovery like this:
<pre>
/home/nfs/oktk/ws/wdtglue-docs/wdt/weblogic-deploy-1.9.15/bin/discoverDomain.sh -domain_type WLS -java_home /opt/oracle/java/java11 -oracle_home /opt/oracle/wls/wls14/Oracle_Home -domain_home /home/nfs/oktk/slask/emptydom/XYmT14 -model_file test.yaml -archive_file test.zip
</pre>
Note that this is fully path specified, but JAVA_HOME and ORACLE_HOME is also set to the above, as well as PATH having both the JAVA_HOME bin and the weblogic-deploy bin in it.

I get a Warning:
<pre>
####<Jun 21, 2021 8:46:48 PM> <WARNING> <DeploymentsDiscoverer> <add_application_plan_to_archive> <WLSDPLY-06395> <Cannot add application binary for application HelloWorld_war to archive file. The application was removed from target /home/nfs/oktk/slask/emptydom/XYmT14/@@DOMAIN_HOME@@/plan/web_HelloWorld_plan.xml : WLSDeployArchive /home/nfs/oktk/slask/conv2wdt/test.zip unable to add file /home/nfs/oktk/slask/emptydom/XYmT14/@@DOMAIN_HOME@@/plan/web_HelloWorld_plan.xml to the archive because the file does not exist>
</pre>

So clearly, it tries to stuff the plan files in the archive, but obviously fails due to the @@DOMAIN_HOME@@ part.

**Comment by CarolynRountree** [comment]
I'm trying to determine where this is breaking down, because it is working in my environment. The code resolves that token before it determines whether it is an abs path. If its not an abs path, it adds the domain home to the start of the path.

**Comment by kenneth-olwing** [comment]
FWIW, I handpatched my 1.9.15 with your changes and get the plans in the zip and in the model as expected :-)

Great, many thanks.
