### ISSUE TITLE
Error while create domain

### ISSUE THREAD

**Issue by smarovic** [oracle/weblogic-deploy-tooling#934]
Hi, When I run the create domain command:
./createDomain.sh -oracle_home /opt/oracle/Middleware -domain_home /opt/oracle/Middleware/user_projects/domains/INSIS -domain_type WLS -model_file ../../WlsDiscoveredInsisDomain.yaml -variable_file ../../WlsDiscoverDemoDomain.properties -archive_file ../../WlsDiscoveredInsisDomain.zip \
-rcu_db db-server.insis:1521/INSISPDB -rcu_prefix FMW12214 -rcu_db_user SYS

I get the following error:
####<Jul 2, 2021 12:05:36 PM> <INFO> <SecurityProviderCreator> <_create_named_subtype_mbeans> <WLSDPLY-12118> <Creating AuthenticationProvider of type TrustServiceIdentityAsserter with name Trust Service Identity Asserter at location /SecurityConfiguration/INSIS/Realm/myrealm>
####<Jul 2, 2021 12:05:36 PM> <SEVERE> <create> <main> <WLSDPLY-12409> **<createDomain failed to create the domain: Unable to create(Trust Service Identity Asserter, oracle.security.jps.wls.providers.trust.TrustServiceIdentityAsserter, AuthenticationProvider) in offline mode at location /SecurityConfiguration/INSIS/Realm/myrealm : null
 @com.oracle.cie.domain.aspect.AbstractConfigAspect.getAspectClass(AbstractConfigAspect.java:126)>**

Issue Log for createDomain version 1.9.15 running WebLogic version 12.2.1.4.0 offline mode:

SEVERE Messages:

        1. WLSDPLY-12409: createDomain failed to create the domain: Unable to create(Trust Service Identity Asserter, oracle.security.jps.wls.providers.trust.TrustServiceIdentityAsserter, AuthenticationProvider) in offline mode at location /SecurityConfiguration/INSIS/Realm/myrealm : null
 @com.oracle.cie.domain.aspect.AbstractConfigAspect.getAspectClass(AbstractConfigAspect.java:126)

Total:       WARNING :     0    SEVERE :     1

Not sure what could be the issue?

**Comment by CarolynRountree** [comment]
Trust Identity Asserter is a security provider that is installed by domain types RestrictredJRF and JRF. It is not a WLS default provider. Check your model for this asserter and remove from your model if you are creating a WLS type domain.

**Comment by smarovic** [comment]
Thanks, it is JRF domain. Does this mean that when running the discoverDomain.sh script which I use for creating model file and zip archive, I should also add -domain_type JRF, and then when creting domain, I should also use this option for domain type?

**Comment by CarolynRountree** [comment]
Yes you need to add -domain_type JRF on both. There is a problem with the Trusted Identity. For createDomain, you need to build a schema jar for the asserter and put in the correct location. The instructions are located here:
https://oracle.github.io/weblogic-deploy-tooling/samples/securityproviders-model/ and scroll down to Trusted Identity Asserter.

**Comment by smarovic** [comment]
Thanks, managed to fix this error by following the instructions in the manual.
