### ISSUE TITLE
Error in YAML validator

### ISSUE THREAD

**Issue by belfo** [oracle/weblogic-deploy-tooling#940]
Hello,

i generated a model.yaml using the discovery tool.
After that i run the validateModel on this file but it fail as the name of the AuthenticationProvider contain a &

AuthenticationProvider:
          'Test&Identity Asserter':

Removing the & make the validation ok

Regards

**Comment by CarolynRountree** [comment]
I have never seen discover put a & in the Trust Identity Server name. Could you rerun discover and provide the model and also provide the config.xml? You can mail to carolyn.rountree@oracle.com

**Comment by belfo** [comment]
The name of the Authentication provider contain a & on Weblogic.
In the config it's marked as:
<sec:authentication-provider>
<sec:name>Test&amp;Identity Asserter</sec:name>

So the discover correctly recover it as 
myrealm:
        AuthenticationProvider:
          'Test&Identity Asserter':
            weblogic.management.security.authentication.AuthenticationProvider:

But when i wanted to create an image using the model, or just running the validateModel script, it fail to validate the name.

The YAML syntax in the code don't support a & in the name. The fix just add the char to the syntax. And i was able to create the image / validate the model with the fixed version

**Comment by belfo** [comment]
Merged in #954
