### ISSUE TITLE
Roundtripping of adjudicator not possible

### ISSUE THREAD

**Issue by kenneth-olwing** [oracle/weblogic-deploy-tooling#970]
This was seen during investigation for issue #968.

(...and TL;DR, I eventually started to look for the problem below in the code, and yes, I found that it apparently is a known issue :-). Can I assume this is still a 'bug to eventually fix' in a bug database? Any guess to a timeframe to hope for a fix? Any suggested workarounds?)

===

As it happens, doing a createDomain exposed a slightly different problem. As it happens, the original config.xml has this in the realm configuration:
<pre>
      &lt;sec:adjudicator xsi:type="wls:default-adjudicatorType"&gt;
        &lt;wls:require-unanimous-permit&gt;false&lt;/wls:require-unanimous-permit&gt;
      &lt;/sec:adjudicator&gt;
</pre>

This, quite correctly, gives this in the yaml:
<pre>
                Adjudicator:
                    Provider:
                        DefaultAdjudicator:
                            RequireUnanimousPermit: false
</pre>

Unfortunately, a createDomain with this gives a warning:
<pre>
####&lt;2021-aug-20 20:54:03&gt; &lt;VARNING&gt; &lt;SecurityProviderCreator&gt; &lt;_check_provider_type&gt; &lt;WLSDPLY-12137&gt; &lt;Update of security configuration adjudicators is not supported&gt;
</pre>

Since it's seen during discoverDomain, one could reasonably expect it to roundtrip in createDomain.

**Comment by CarolynRountree** [comment]
there is a bug open, right now it is in WDT. We can move it up in the queue

**Comment by kenneth-olwing** [comment]
👍 , I'm good with that.
