### ISSUE TITLE
envinronment.properties files in Domain Home(i.e /u01/domains/sampleDomain)

### ISSUE THREAD

**Issue by manavtidhan** [oracle/weblogic-deploy-tooling#984]
Hi , 

I am not able to find a way how to put evnironement.properties file in Domain Home (this file is loaded by an application), there is No such way I found in Archive Structure defined below link

https://oracle.github.io/weblogic-deploy-tooling/concepts/archive/

I also tried to use configmap to mount the file in Domain Home , but I was getting permission denied , I tried to set up default mode and mode to 0777 still same error. 

Pleaes help me out , I am strulling from a week but not able to place the property file in Domain Home in "FromModel".

**Comment by tbarnes-us** [comment]
This is a duplicate of [WKO Issue 2568](https://github.com/oracle/weblogic-kubernetes-operator/issues/2568)

Both issues were filed by the same filer. 

We will continue the discussion in [WKO Issue 2568](https://github.com/oracle/weblogic-kubernetes-operator/issues/2568) for now as it's not clear whether it's a WKO or a WDT issue.

**Comment by robertpatrick** [comment]
@manavtidhan the current mechanism to do this with a WDT archive file is to put the file in the `wlsdeploy/custom` folder of the zip file.  Of course, you would then need to change your application to look in `$DOMAIN_HOME/wlsdeploy/custom/` directory for the `environment.properties` file.

**Comment by manavtidhan** [comment]
Yes , thanks I did the same way
